'use client'
import { useEffect,useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/utils/supabase/client'
type Unit={id:string;unit_no:string|null;floor:number|null;rooms:number|null;area_m2:number|null;price:number|null;currency:string;status:string;building_id:string}
type Building={id:string;name:string;complex_id:string}
type Complex={id:string;name:string}
const statusLabels:Record<string,string>={available:'Mavjud',reserved:'Bron',sold:'Sotilgan',hidden:'Yashirilgan'}
export default function InventoryPage(){const [complexes,setComplexes]=useState<Complex[]>([]);const [buildings,setBuildings]=useState<Building[]>([]);const [units,setUnits]=useState<Unit[]>([]);const [selected,setSelected]=useState('');const [loading,setLoading]=useState(true)
useEffect(()=>{(async()=>{const db=createClient();const {data:{user}}=await db.auth.getUser();if(!user){setLoading(false);return}const {data:d}=await db.from('developer_profiles').select('id').eq('user_id',user.id).maybeSingle();if(!d){setLoading(false);return}const {data:c}=await db.from('residential_complexes').select('id,name').eq('developer_id',d.id);setComplexes(c||[]);const ids=(c||[]).map(x=>x.id);if(ids.length){const {data:b}=await db.from('residential_buildings').select('id,name,complex_id').in('complex_id',ids);setBuildings(b||[]);const bids=(b||[]).map(x=>x.id);if(bids.length){const {data:u}=await db.from('complex_units').select('id,unit_no,floor,rooms,area_m2,price,currency,status,building_id').in('building_id',bids).order('building_id').order('floor');setUnits(u||[])}}setLoading(false)})()},[])
async function changeStatus(id:string,status:string){const db=createClient();const {error}=await db.from('complex_units').update({status}).eq('id',id);if(!error)setUnits(v=>v.map(u=>u.id===id?{...u,status}:u))}
const filtered=selected?units.filter(u=>u.building_id===selected):units
if(loading)return <main className="p-8">Yuklanmoqda...</main>
return <main className="min-h-screen bg-slate-50 px-4 py-6"><div className="mx-auto max-w-7xl"><header className="flex items-center justify-between"><Link href="/account/developer" className="font-bold text-emerald-700">← Developer kabineti</Link><span className="text-sm font-bold text-slate-500">Inventory</span></header><section className="mt-5 rounded-3xl bg-slate-900 p-7 text-white"><h1 className="text-3xl font-black">Xonadonlar inventari</h1><p className="mt-2 text-sm text-slate-300">Mavjud, bron qilingan va sotilgan xonadonlarni boshqaring.</p></section><div className="mt-5 grid gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-white p-5"><p className="text-xs font-bold text-slate-400">JAMI</p><p className="mt-1 text-2xl font-black">{units.length}</p></div>{['available','reserved','sold'].map(s=><div key={s} className="rounded-2xl bg-white p-5"><p className="text-xs font-bold text-slate-400">{statusLabels[s].toUpperCase()}</p><p className="mt-1 text-2xl font-black">{units.filter(u=>u.status===s).length}</p></div>)}</div><div className="mt-6 rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">Inventar</h2><select value={selected} onChange={e=>setSelected(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold"><option value="">Barcha korpuslar</option>{buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-400"><th className="p-3">Xonadon</th><th className="p-3">Korpus</th><th className="p-3">Qavat</th><th className="p-3">Xona</th><th className="p-3">Maydon</th><th className="p-3">Narx</th><th className="p-3">Holat</th></tr></thead><tbody>{filtered.map(u=>{const b=buildings.find(x=>x.id===u.building_id);return <tr key={u.id} className="border-b border-slate-100"><td className="p-3 font-black">{u.unit_no||'—'}</td><td className="p-3">{b?.name||'—'}</td><td className="p-3">{u.floor??'—'}</td><td className="p-3">{u.rooms??'—'}</td><td className="p-3">{u.area_m2?`${u.area_m2} m²`:'—'}</td><td className="p-3 font-bold">{u.price?`${u.price.toLocaleString('uz-UZ')} ${u.currency}`:'—'}</td><td className="p-3"><select value={u.status} onChange={e=>changeStatus(u.id,e.target.value)} className="rounded-lg border border-slate-200 px-2 py-1.5 text-xs font-bold">{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td></tr>})}</tbody></table>{!filtered.length&&<p className="py-10 text-center text-sm text-slate-500">Xonadonlar topilmadi.</p>}</div></div></div></main>}
