'use client'

import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createClient } from '@/utils/supabase/client'
import ListingLocationPicker from '@/app/components/ListingLocationPicker'
import { UZBEKISTAN_LOCATIONS } from '@/data/uzbekistan-locations'
import { getListingImageStoragePath, isAcceptedListingImage, LISTING_IMAGE_ACCEPT, LISTING_IMAGE_BUCKET, LISTING_IMAGE_MAX_SIZE } from '@/utils/listing-images'

type Lang = 'uz' | 'ru'
type Category = { code:string; parent_code:string|null; name_uz:string; name_ru:string|null; section_code:string; listing_type:string|null; property_type:string|null; entity_type:string; is_mortgage_filter:boolean; is_new_construction_filter:boolean; sort_order:number }
type Attribute = { id:string; category_code:string; code:string; name_uz:string; name_ru:string|null; data_type:string; options:unknown; unit:string|null; is_required:boolean; sort_order:number }
type Img = { file:File; preview:string }

const sections:Record<string,{uz:string;ru:string}> = { sale:{uz:'Sotib olish',ru:'Покупка'}, rent:{uz:'Ijara',ru:'Аренда'}, new_building:{uz:'Yangi uylar',ru:'Новостройки'}, services:{uz:'Xizmatlar',ru:'Услуги'} }
const steps:{uz:string;ru:string}[] = [
 {uz:'Bo‘lim',ru:'Раздел'}, {uz:'Tur',ru:'Тип'}, {uz:'Joylashuv',ru:'Расположение'}, {uz:'Xususiyatlar',ru:'Характеристики'}, {uz:'Narx',ru:'Цена'}, {uz:'Rasmlar',ru:'Фото'}, {uz:'Tekshirish',ru:'Проверка'}
]
const cleanDistrict=(v:string)=>v.replace(/ tumani$/i,'').replace(/ shahri$/i,'')

const getImageDimensions = (file: File): Promise<{ width: number | null; height: number | null }> => new Promise(resolve => {
 const url = URL.createObjectURL(file)
 const image = new Image()
 image.onload = () => { URL.revokeObjectURL(url); resolve({ width: image.naturalWidth, height: image.naturalHeight }) }
 image.onerror = () => { URL.revokeObjectURL(url); resolve({ width: null, height: null }) }
 image.src = url
})

export default function ListingWizard(){
 const router=useRouter()
 const [lang,setLang]=useState<Lang>('uz')
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('')
 const [categories,setCategories]=useState<Category[]>([]); const [attributes,setAttributes]=useState<Attribute[]>([]); const [step,setStep]=useState(1); const [listingId,setListingId]=useState<string|null>(null)
 const [images,setImages]=useState<Img[]>([]); const [mainImage,setMainImage]=useState(0); const [values,setValues]=useState<Record<string,string>>({})
 const [form,setForm]=useState({taxonomy_code:'',listing_type:'sale',property_type:'apartment',title:'',description:'',price:'',currency:'UZS',area_m2:'',rooms:'',floor:'',floors_total:'',city:'Toshkent',district:'',address:'',contact_phone:'',company_name:''})
 const [location,setLocation]=useState<{latitude:number|null;longitude:number|null}>({latitude:null,longitude:null})
 const ru=lang==='ru'
 const selected=categories.find(c=>c.code===form.taxonomy_code)||null
 const region=useMemo(()=>form.city==='Toshkent'?UZBEKISTAN_LOCATIONS.find(x=>x.name==='Toshkent shahri'):UZBEKISTAN_LOCATIONS.find(x=>x.name===form.city),[form.city])
 const districts=region?.districts||[]
 const attrs=useMemo(()=>attributes.filter(a=>a.category_code===form.taxonomy_code&&a.code!=='ownership_type').sort((a,b)=>a.sort_order-b.sort_order),[attributes,form.taxonomy_code])
 const isHouseSale=selected?.code==='sale_house'
 const isOwner=values.ownership_type==='owner'
 const update=(k:keyof typeof form,v:string)=>setForm(x=>({...x,[k]:v}))
 const t=(uz:string,ruText:string)=>ru?ruText:uz

 useEffect(()=>{
   const sync=()=>{ const saved=window.localStorage.getItem('prohouse-lang'); setLang(saved==='ru'?'ru':'uz') }
   sync()
   const onLanguageChange=(event:Event)=>{ const next=(event as CustomEvent<Lang>).detail; if(next==='ru'||next==='uz') setLang(next) }
   window.addEventListener('prohouse-language-change',onLanguageChange)
   return()=>window.removeEventListener('prohouse-language-change',onLanguageChange)
 },[])

 const toggleLanguage=()=>{
   const next:Lang=ru?'uz':'ru'
   setLang(next)
   window.localStorage.setItem('prohouse-lang',next)
   window.dispatchEvent(new CustomEvent('prohouse-language-change',{detail:next}))
 }

 useEffect(()=>{(async()=>{try{const r=await fetch('/api/listings/meta');const d=await r.json();if(!r.ok)throw new Error(d.error||t('Metadata yuklanmadi','Не удалось загрузить данные'));setCategories(d.categories||[]);setAttributes(d.attributes||[])}catch(e){setError(e instanceof Error?e.message:t('Yuklashda xatolik','Ошибка загрузки'))}finally{setLoading(false)}})()},[])
 useEffect(()=>()=>images.forEach(i=>URL.revokeObjectURL(i.preview)),[images])

 const payload=()=>({...form,price:form.price.replace(/\s/g,''),area_m2:form.area_m2,rooms:form.rooms,floor:form.floor,floors_total:form.floors_total,latitude:location.latitude,longitude:location.longitude,attributes:values,ownership_type:isHouseSale&&isOwner?'owner':null})
 const save=async(nextStep:number,status:'draft'|'moderation'='draft')=>{setSaving(true);setError('');try{const r=await fetch('/api/listings/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({listingId,step:nextStep,data:payload(),status})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||t('Saqlashda xatolik','Ошибка сохранения'));setListingId(d.listing.id);setStep(nextStep)}catch(e){setError(e instanceof Error?e.message:t('Saqlashda xatolik','Ошибка сохранения'))}finally{setSaving(false)}}
 const validate=()=>{if(!form.taxonomy_code)return t('Bo‘lim va turini tanlang.','Выберите раздел и тип.');if(step>=3&&(!form.city||!form.district))return t('Joylashuvni to‘liq tanlang.','Полностью выберите расположение.');if(step>=3&&(location.latitude==null||location.longitude==null))return t('Xaritadan joylashuvni belgilang.','Укажите расположение на карте.');if(step>=4&&!form.title.trim())return t('E’lon sarlavhasini kiriting.','Введите заголовок объявления.');if(step>=5&&(!form.price||!Number.isFinite(Number(form.price.replace(/\s/g,'')))))return t('To‘g‘ri narx kiriting.','Введите корректную цену.');if(step>=6&&images.length===0)return t('Kamida 1 ta rasm yuklang.','Загрузите хотя бы 1 фото.');return ''}
 const next=async()=>{const v=validate();if(v){setError(v);return}setError('');if(step<7)await save(step+1)}
 const back=()=>{setError('');setStep(s=>Math.max(1,s-1))}
 const cancelDraft=async()=>{if(!listingId){router.push('/account');return}setSaving(true);setError('');try{const r=await fetch(`/api/listings/draft?listingId=${encodeURIComponent(listingId)}`,{method:'DELETE'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||t('Qoralamani bekor qilishda xatolik','Ошибка отмены черновика'));router.push('/account')}catch(e){setError(e instanceof Error?e.message:t('Qoralamani bekor qilishda xatolik','Ошибка отмены черновика'))}finally{setSaving(false)}}
 const addImages=(e:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(e.target.files||[]);e.target.value='';if(images.length+files.length>10){setError(t('Maksimal 10 ta rasm.','Максимум 10 фото.'));return}const bad=files.find(f=>!isAcceptedListingImage(f)||f.size>LISTING_IMAGE_MAX_SIZE);if(bad){setError(t('Faqat JPG, PNG, WebP yoki GIF rasm yuklash mumkin. Har biri 10 MB gacha.','Можно загрузить только JPG, PNG, WebP или GIF. Максимум 10 МБ на файл.'));return}setImages(x=>[...x,...files.map(file=>({file,preview:URL.createObjectURL(file)}))])}
 const removeImage=(i:number)=>{setImages(x=>x.filter((_,n)=>n!==i));setMainImage(0)}
 const submit=async()=>{const v=validate();if(v){setError(v);return}if(!listingId){setError(t('Qoralama topilmadi. Keyingi bosqichga o‘ting.','Черновик не найден. Перейдите к следующему шагу.'));return}setSaving(true);setError('');const supabase=createClient();const uploadedPaths:string[]=[];let imagesPersisted=false;try{const ordered=[images[mainImage],...images.filter((_,i)=>i!==mainImage)];const rows=[];for(let i=0;i<ordered.length;i++){const file=ordered[i].file;const user=(await supabase.auth.getUser()).data.user;if(!user)throw new Error('AUTH_REQUIRED');const path=getListingImageStoragePath(user.id,listingId,file.name);const u=await supabase.storage.from(LISTING_IMAGE_BUCKET).upload(path,file,{cacheControl:'31536000',upsert:false});if(u.error)throw u.error;uploadedPaths.push(path);const {width,height}=await getImageDimensions(file);const pub=supabase.storage.from(LISTING_IMAGE_BUCKET).getPublicUrl(path);rows.push({listing_id:listingId,image_url:pub.data.publicUrl,storage_path:path,sort_order:i,width,height,size_bytes:file.size,mime_type:file.type})}if(rows.length){const {error:e}=await supabase.from('listing_images').insert(rows);if(e)throw e;imagesPersisted=true}const r=await fetch('/api/listings/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({listingId,step:7,data:payload(),status:'moderation'})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||t('Moderatsiyaga yuborilmadi','Не удалось отправить на модерацию'));setSuccess(t(`E’lon moderatsiyaga yuborildi: ${d.listing.listing_code}`,`Объявление отправлено на модерацию: ${d.listing.listing_code}`));setTimeout(()=>router.push('/account/listings'),700)}catch(e){if(!imagesPersisted&&uploadedPaths.length){await supabase.storage.from(LISTING_IMAGE_BUCKET).remove(uploadedPaths)}setError(e instanceof Error?e.message:t('E’lonni yuborishda xatolik','Ошибка отправки объявления'))}finally{setSaving(false)}}

 if(loading)return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-4xl rounded-3xl bg-white p-10 text-center">{t('Yuklanmoqda...','Загрузка...')}</div></main>
 return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:py-10"><div className="mx-auto max-w-4xl">
   <div className="mb-5 flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-slate-500">PROHOUSE</p><h1 className="mt-1 text-2xl font-bold text-slate-950">{t('E’lon joylashtirish','Разместить объявление')}</h1><p className="mt-1 text-sm text-slate-500">{t('Ma’lumotlar har bosqichda qoralama sifatida saqlanadi.','Данные сохраняются как черновик на каждом шаге.')}</p></div><div className="flex shrink-0 gap-2"><button type="button" onClick={toggleLanguage} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-extrabold text-slate-700 hover:bg-slate-50">{ru?'Ru / O‘z':'O‘z / Ru'}</button><Link href="/account" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50">{t('Shaxsiy kabinet','Личный кабинет')}</Link></div></div>
   <div className="mb-5 grid grid-cols-7 gap-1">{steps.map((x,i)=><div key={x.uz} className={`rounded-xl px-1 py-2 text-center text-[11px] font-semibold ${i+1===step?'bg-slate-950 text-white':i+1<step?'bg-slate-200 text-slate-700':'bg-white text-slate-400'}`}><span className="hidden sm:inline">{i+1}. </span>{ru?x.ru:x.uz}</div>)}</div>
   <section className="rounded-3xl bg-white p-5 shadow-sm sm:p-8">
   {error&&<div className="mb-5 rounded-2xl bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}{success&&<div className="mb-5 rounded-2xl bg-emerald-50 p-4 text-sm font-medium text-emerald-700">{success}</div>}
   {step===1&&<div><h2 className="text-xl font-bold">1. {t('Bo‘limni tanlang','Выберите раздел')}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(sections).map(([code,label])=>{const ok=categories.some(c=>c.section_code===code);return ok?<button key={code} onClick={()=>{update('taxonomy_code','');setStep(2);(window as any).__prohouse_section=code}} className="rounded-2xl border p-5 text-left hover:border-slate-950"><b>{ru?label.ru:label.uz}</b><span className="mt-1 block text-sm text-slate-500">{categories.filter(c=>c.section_code===code).length} {t('ta yo‘nalish','направлений')}</span></button>:null})}</div></div>}
   {step===2&&<div><h2 className="text-xl font-bold">2. {t('Turini tanlang','Выберите тип')}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{categories.filter(c=>c.parent_code).map(c=><button key={c.code} onClick={()=>{setForm(v=>({...v,taxonomy_code:c.code,listing_type:c.listing_type||v.listing_type,property_type:c.property_type||v.property_type}));setStep(2)}} className={`rounded-2xl border p-4 text-left ${selected?.code===c.code?'border-slate-950 bg-slate-50':''}`}><b>{ru?(c.name_ru||c.name_uz):c.name_uz}</b><span className="mt-1 block text-xs text-slate-500">{c.property_type||c.entity_type}</span></button>)}</div><p className="mt-4 text-xs text-slate-400">{t('Tanlovdan so‘ng “Davom etish” tugmasini bosing.','После выбора нажмите «Продолжить».')}</p></div>}
   {step===3&&<div><h2 className="text-xl font-bold">3. {t('Joylashuv','Расположение')}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">{t('Shahar/viloyat','Город/область')}<select value={form.city} onChange={e=>{update('city',e.target.value);update('district','')}} className="mt-2 w-full rounded-xl border p-3"><option>Toshkent</option>{UZBEKISTAN_LOCATIONS.filter(x=>x.name!=='Toshkent shahri').map(x=><option key={x.name}>{x.name}</option>)}</select></label><label className="text-sm font-semibold">{t('Tuman/shahar','Район/город')}<select value={form.district} onChange={e=>update('district',e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="">{t('Tanlang','Выберите')}</option>{districts.map(x=><option key={x}>{cleanDistrict(x)}</option>)}</select></label></div><input value={form.address} onChange={e=>update('address',e.target.value)} placeholder={t('Ko‘cha, uy raqami (ixtiyoriy)','Улица, номер дома (необязательно)')} className="mt-4 w-full rounded-xl border p-3"/><div className="mt-4"><ListingLocationPicker latitude={location.latitude} longitude={location.longitude} onChange={(latitude,longitude)=>setLocation({latitude,longitude})}/></div></div>}
   {step===4&&<div><h2 className="text-xl font-bold">4. {t('Xususiyatlar','Характеристики')}</h2>{isHouseSale&&<label className="mt-5 flex cursor-pointer items-center gap-3 rounded-2xl border p-4 transition hover:border-slate-950"><input type="checkbox" checked={isOwner} onChange={e=>setValues(v=>({...v,ownership_type:e.target.checked?'owner':''}))} className="h-5 w-5 shrink-0"/><span><b>{t('Mulk egasi','Собственник')}</b><small className="block text-slate-500">{t('Men ushbu ko‘chmas mulkning egasiman.','Я являюсь владельцем этой недвижимости.')}</small></span></label>}
   <div className="mt-5 grid gap-4 sm:grid-cols-2">{attrs.map(a=><label key={a.id} className="text-sm font-semibold">{ru?(a.name_ru||a.name_uz):a.name_uz}{a.unit?` (${a.unit})`:''}{a.is_required?' *':''}<input type={a.data_type==='number'?'number':'text'} value={values[a.code]??''} onChange={e=>setValues(v=>({...v,[a.code]:e.target.value}))} className="mt-2 w-full rounded-xl border p-3"/></label>)}</div><input value={form.title} onChange={e=>update('title',e.target.value)} placeholder={t('E’lon sarlavhasi','Заголовок объявления')} className="mt-5 w-full rounded-xl border p-3"/><textarea value={form.description} onChange={e=>update('description',e.target.value)} placeholder={t('Tavsif','Описание')} rows={5} className="mt-4 w-full rounded-xl border p-3"/></div>}
   {step===5&&<div><h2 className="text-xl font-bold">5. {t('Narx va shartlar','Цена и условия')}</h2><div className="mt-5 grid gap-4 sm:grid-cols-3"><input value={form.price} onChange={e=>update('price',e.target.value)} placeholder={t('Narx','Цена')} inputMode="numeric" className="rounded-xl border p-3 sm:col-span-2"/><select value={form.currency} onChange={e=>update('currency',e.target.value)} className="rounded-xl border p-3"><option>UZS</option><option>USD</option></select></div>{(selected?.is_mortgage_filter||form.listing_type==='sale'||form.listing_type==='new_building')&&<label className="mt-5 flex items-center gap-3 rounded-2xl border p-4"><input type="checkbox" checked={Boolean(values.mortgage)} onChange={e=>setValues(v=>({...v,mortgage:e.target.checked?'true':'false'}))}/><span><b>{t('Ipotekaga mumkin','Можно в ипотеку')}</b><small className="block text-slate-500">{t('Xaridor uchun ipoteka imkoniyati mavjud.','Доступна ипотека для покупателя.')}</small></span></label>}</div>}
   {step===6&&<div><h2 className="text-xl font-bold">6. {t('Rasmlar','Фото')}</h2><p className="mt-1 text-sm text-slate-500">{t('10 tagacha rasm. Birinchi tanlangan rasm asosiy rasm bo‘ladi.','До 10 фото. Первое выбранное фото будет основным.')}</p><label className="mt-5 flex cursor-pointer items-center justify-center rounded-2xl border-2 border-dashed p-10 text-sm font-semibold"><input type="file" accept={LISTING_IMAGE_ACCEPT} multiple onChange={addImages} className="hidden"/>{t('Rasmlarni tanlash','Выбрать фото')}</label><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{images.map((im,i)=><div key={im.preview} className="relative overflow-hidden rounded-2xl border"><img src={im.preview} className="aspect-square w-full object-cover"/><button type="button" onClick={()=>removeImage(i)} className="absolute right-2 top-2 rounded-full bg-white px-2 py-1 text-xs">×</button>{i===mainImage&&<span className="absolute bottom-2 left-2 rounded-full bg-slate-950 px-2 py-1 text-[10px] text-white">{t('Asosiy','Основное')}</span>}</div>)}</div></div>}
   {step===7&&<div><h2 className="text-xl font-bold">7. {t('Tekshirish','Проверка')}</h2><div className="mt-5 space-y-3">{[[t('Bo‘lim','Раздел'),ru?(selected?.name_ru||selected?.name_uz||'—'):(selected?.name_uz||'—')],[t('Joylashuv','Расположение'),`${form.city}, ${form.district}`],[t('Manzil','Адрес'),form.address||'—'],[t('Mulk egasi','Собственник'),isOwner?t('Ha','Да'):t('Yo‘q','Нет')],[t('Sarlavha','Заголовок'),form.title||'—'],[t('Narx','Цена'),`${form.price||'—'} ${form.currency}`],[t('Rasmlar','Фото'),`${images.length} ${t('ta','шт.')}`]].map(([a,b])=><div key={a} className="flex justify-between gap-5 rounded-2xl bg-slate-50 p-4 text-sm"><span className="text-slate-500">{a}</span><b className="text-right">{b}</b></div>)}</div><p className="mt-5 text-sm text-slate-500">{t('“E’lonni yuborish” tugmasi bosilgach e’lon moderatsiyaga yuboriladi.','После нажатия «Отправить объявление» оно будет отправлено на модерацию.')}</p></div>}
   <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t pt-5"><div className="flex gap-2"><button type="button" onClick={back} disabled={step===1||saving} className="rounded-xl border px-5 py-3 text-sm font-semibold disabled:opacity-40">{t('Orqaga','Назад')}</button><button type="button" onClick={()=>void cancelDraft()} disabled={saving} className="rounded-xl border border-red-200 bg-red-50 px-5 py-3 text-sm font-semibold text-red-700 disabled:opacity-40">{t('Bekor qilish','Отмена')}</button></div>{step<7?<button type="button" onClick={next} disabled={saving||(step===2&&!form.taxonomy_code)} className="rounded-xl bg-slate-950 px-6 py-3 text-sm font-semibold text-white disabled:opacity-40">{saving?t('Saqlanmoqda...','Сохранение...'):t('Davom etish','Продолжить')}</button>:<button type="button" onClick={submit} disabled={saving} className="rounded-xl bg-slate-950 px-6 py-3 text-sm font-semibold text-white disabled:opacity-40">{saving?t('Yuborilmoqda...','Отправка...'):t('E’lonni yuborish','Отправить объявление')}</button>}</div>
   </section></div></main>
}
