'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'

type Permission={id:string;code:string;name_uz:string}; type Admin={id:string;email:string;role:string;is_active:boolean;permissions:string[]}
export default function Administrators(){const[admins,setAdmins]=useState<Admin[]>([]);const[permissions,setPermissions]=useState<Permission[]>([]);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[selected,setSelected]=useState<string[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[msg,setMsg]=useState('');
 async function load(){const r=await fetch('/api/admin/administrators',{cache:'no-store'});if(r.status===401||r.status===403){location.href='/admin/login';return}const d=await r.json();if(!r.ok){setMsg(d.error||'Xatolik');return}setAdmins(d.admins||[]);setPermissions(d.permissions||[]);setLoading(false)}useEffect(()=>{void load()},[])
 function toggle(code:string){setSelected(x=>x.includes(code)?x.filter(v=>v!==code):[...x,code])}
 async function create(){setSaving(true);setMsg('');const r=await fetch('/api/admin/administrators',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,permissionCodes:selected})});const d=await r.json();if(!r.ok)setMsg(d.error||'Admin yaratilmadi');else{setEmail('');setPassword('');setSelected([]);setMsg('Admin muvaffaqiyatli yaratildi.');await load()}setSaving(false)}
 async function setActive(a:Admin){const r=await fetch('/api/admin/administrators',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({roleId:a.id,isActive:!a.is_active,permissionCodes:a.permissions.map(id=>permissions.find(p=>p.id===id)?.code).filter(Boolean)})});const d=await r.json();if(!r.ok)setMsg(d.error||'O‘zgartirilmadi');else await load()}
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4"><Link href="/admin" className="font-black text-emerald-700">← Admin</Link><span className="font-bold">Administratorlar</span></div></header><div className="mx-auto max-w-6xl px-4 py-8"><h1 className="text-3xl font-black">Administratorlar</h1><p className="mt-2 text-sm text-slate-500">Oddiy adminlar uchun login va vakolatlarni boshqaring.</p><div className="mt-7 grid gap-6 lg:grid-cols-[380px_1fr]"><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">+ Yangi admin</h2><div className="mt-5 space-y-4"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email / login" className="w-full rounded-xl border px-4 py-3"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Vaqtinchalik parol (min. 8)" className="w-full rounded-xl border px-4 py-3"/><div><p className="mb-2 text-sm font-bold">Vakolatlar</p><div className="space-y-2">{permissions.map(p=><label key={p.id} className="flex cursor-pointer items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm"><input type="checkbox" checked={selected.includes(p.code)} onChange={()=>toggle(p.code)}/><span>{p.name_uz}</span></label>)}</div></div><button disabled={saving||!email||password.length<8} onClick={()=>void create()} className="w-full rounded-xl bg-slate-900 px-4 py-3 font-bold text-white disabled:opacity-50">{saving?'Yaratilmoqda...':'Admin yaratish'}</button>{msg&&<p className="rounded-xl bg-slate-50 p-3 text-sm">{msg}</p>}</div></section><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Mavjud adminlar</h2>{loading?<p className="mt-5 text-slate-500">Yuklanmoqda...</p>:<div className="mt-5 space-y-3">{admins.map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border p-4"><div><div className="font-bold">{a.email}</div><div className="mt-1 text-xs text-slate-500">{a.role==='super_admin'?'Bosh admin':`${a.permissions.length} ta vakolat`}</div></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-bold ${a.is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{a.is_active?'Faol':'Bloklangan'}</span>{a.role!=='super_admin'&&<button onClick={()=>void setActive(a)} className="rounded-xl border px-3 py-2 text-sm font-bold">{a.is_active?'Bloklash':'Faollashtirish'}</button>}</div></div>)}</div>}</section></div></div></main>}
