'use client'

import { useEffect } from 'react'
import { createClient } from '@/utils/supabase/client'

type Taxonomy={code:string;name_uz:string;name_ru:string|null}
type Item={uz:string;ru:string;descUz:string;descRu:string;href:string;icon:string;external?:boolean}

export default function GlobalNavigationFix(){
 useEffect(()=>{
  const supabase=createClient();let mounted=true;let userId:string|null=null
  const isRu=()=>window.localStorage.getItem('royalhouse-lang')==='ru'
  const close=()=>{document.querySelector('.prohouse-services-overlay')?.remove();document.querySelector('.prohouse-services-style')?.remove();document.body.style.overflow=''}
  const openServices=async()=>{
   if(document.querySelector('.prohouse-services-overlay'))return
   const ru=isRu();let services:Taxonomy[]=[]
   try{const{data}=await supabase.from('partner_listing_taxonomy').select('code,name_uz,name_ru').eq('section_code','services').eq('parent_code','services').eq('is_active',true).eq('allows_partner_listing',true).order('sort_order');services=(data||[]) as Taxonomy[]}catch{}
   if(!mounted)return
   const icons:Record<string,string>={services_repair:'🔧',services_cleaning:'🧹',services_design:'🎨',services_construction:'🏗️',services_furniture:'🪑',services_plumbing:'🚿',services_electric:'⚡',services_moving:'🚚',services_other:'🛠️',services_landscape:'🌳',services_cctv:'📹',services_ac_installation:'❄️'}
   const finance:Item[]=[
    {uz:'E-Notarius',ru:'E-Notarius',descUz:'Elektron notarial xizmatlar',descRu:'Электронные нотариальные услуги',href:'https://e-notarius.uz/',icon:'📄',external:true},
    {uz:'Mulkni baholash',ru:'Оценка недвижимости',descUz:'Ko‘chmas mulk qiymatini baholash',descRu:'Оценка стоимости недвижимости',href:'/services/request?type=property_valuation',icon:'📊'},
    {uz:'Sug‘urta xizmati',ru:'Страховые услуги',descUz:'Uy va mulkni onlayn sug‘urtalash',descRu:'Онлайн-страхование жилья и имущества',href:'/services/request?type=insurance',icon:'🛡️'}
   ]
   const interactive:Item[]=[
    {uz:'Bino soyasini ko‘rish',ru:'Посмотреть тень здания',descUz:'Bino soyasining uzunligi va yo‘nalishini hisoblash',descRu:'Расчёт длины и направления тени здания',href:'/tools/building-shadow.html',icon:'☀️'},
    {uz:'Qurilishlar statistikasi',ru:'Статистика строительства',descUz:'Qurilish obyektlari bo‘yicha interaktiv ma’lumotlar',descRu:'Интерактивные данные по строительным объектам',href:'https://dshk.shaffofqurilish.uz/oz',icon:'🏗️',external:true}
   ]
   const style=document.createElement('style');style.className='prohouse-services-style';style.textContent=`
.prohouse-services-overlay{position:fixed;inset:0;z-index:9999;background:rgba(4,10,20,.72);backdrop-filter:blur(10px);display:flex;align-items:flex-start;justify-content:center;padding:60px 20px 30px;overflow:auto}
.prohouse-services-modal{position:relative;width:min(1180px,100%);background:#fff;border-radius:24px;box-shadow:0 24px 70px rgba(0,0,0,.28);padding:32px;box-sizing:border-box}
.prohouse-services-head{display:flex;align-items:center;gap:16px;padding-right:50px}.prohouse-services-head-icon{width:58px;height:58px;border-radius:18px;background:#ecfdf5;display:flex;align-items:center;justify-content:center;font-size:28px;flex:none}.prohouse-services-title{margin:0 0 8px;font-size:30px;font-weight:900;color:#0f172a}.prohouse-services-subtitle{margin:0;color:#64748b;font-size:14px}.prohouse-services-close{position:absolute;right:16px;top:12px;border:0;background:#f1f5f9;color:#64748b;border-radius:50%;width:38px;height:38px;font-size:26px;cursor:pointer}
.prohouse-services-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:24px 0 18px}.prohouse-services-tab{border:1px solid #dbe3ea;border-radius:16px;background:#f8fafc;color:#334155;padding:14px 16px;text-align:left;cursor:pointer;font-weight:900;font-size:14px;line-height:1.25}.prohouse-services-tab.active{border-color:#10b981;background:#ecfdf5;color:#047857}.prohouse-services-tab span{display:block;margin-top:4px;color:#64748b;font-size:11px;font-weight:500}
.prohouse-services-search{width:100%;margin:0 0 16px;padding:14px 16px;border:1px solid #dbe3ea;border-radius:16px;background:#f8fafc;color:#0f172a;font-size:15px;outline:none;box-sizing:border-box}.prohouse-services-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.prohouse-service-card{display:flex;align-items:center;gap:14px;min-height:92px;padding:16px;border:1px solid #dbe3ea;border-radius:16px;background:#fff;text-decoration:none;color:#0f172a;box-sizing:border-box;transition:.15s;min-width:0}.prohouse-service-card:hover{border-color:#10b981;background:#f8fffb}.prohouse-service-icon{display:flex;align-items:center;justify-content:center;width:48px;height:48px;border-radius:50%;background:#ecfdf5;font-size:24px;flex:none}.prohouse-service-content{min-width:0;flex:1}.prohouse-service-name{display:block;font-size:15px;font-weight:900;line-height:1.25}.prohouse-service-sub{display:block;margin-top:4px;color:#64748b;font-size:12px;line-height:1.35}.prohouse-service-arrow{font-size:22px;color:#94a3b8}.prohouse-services-note{margin-top:18px;padding:14px 16px;border-radius:14px;background:#f8fafc;color:#64748b;font-size:13px;line-height:1.45}
@media(max-width:640px){.prohouse-services-overlay{padding:12px 8px 18px}.prohouse-services-modal{width:100%;padding:18px 12px 16px;border-radius:28px;background:linear-gradient(180deg,#111827,#172131);color:#f8fafc}.prohouse-services-head{gap:12px;padding:4px 48px 0 2px}.prohouse-services-title{font-size:28px;color:#f8fafc}.prohouse-services-subtitle{color:#94a3b8}.prohouse-services-close{right:14px;top:14px;width:48px;height:48px;background:#475569;color:#dbeafe}.prohouse-services-tabs{grid-template-columns:1fr;gap:8px;margin:18px 0 12px}.prohouse-services-tab{padding:12px 13px;background:rgba(30,41,59,.75);border-color:rgba(100,116,139,.42);color:#f8fafc}.prohouse-services-tab.active{background:rgba(16,185,129,.15);color:#6ee7b7}.prohouse-services-search{height:50px;padding:0 15px;background:rgba(30,41,59,.9);border-color:rgba(148,163,184,.38);color:#f8fafc}.prohouse-services-grid{grid-template-columns:repeat(2,1fr);gap:8px}.prohouse-service-card{min-height:125px;padding:10px 8px;display:flex;flex-direction:column;align-items:flex-start;justify-content:flex-start;gap:7px;border-radius:17px;background:rgba(30,41,59,.74);border-color:rgba(100,116,139,.42);color:#f8fafc}.prohouse-service-icon{width:43px;height:43px;font-size:22px;background:rgba(0,90,75,.55)}.prohouse-service-name{font-size:12.5px;color:#f8fafc}.prohouse-service-sub{font-size:10.5px;color:#94a3b8}.prohouse-service-arrow{display:none}.prohouse-services-note{margin-top:12px;background:rgba(30,41,59,.75);color:#a8b6c9;font-size:12.5px}}
`;document.head.appendChild(style)
   const overlay=document.createElement('div');overlay.className='prohouse-services-overlay';overlay.onclick=close
   const modal=document.createElement('div');modal.className='prohouse-services-modal';modal.onclick=e=>e.stopPropagation()
   const x=document.createElement('button');x.type='button';x.textContent='×';x.className='prohouse-services-close';x.onclick=close
   const head=document.createElement('div');head.className='prohouse-services-head';const hi=document.createElement('div');hi.className='prohouse-services-head-icon';hi.textContent='▦';const ht=document.createElement('div');const h=document.createElement('h2');h.className='prohouse-services-title';h.textContent=ru?'Услуги':'Xizmatlar';const p=document.createElement('p');p.className='prohouse-services-subtitle';p.textContent=ru?'Выберите нужное направление':'Kerakli xizmat yo‘nalishini tanlang';ht.append(h,p);head.append(hi,ht)
   const tabs=document.createElement('div');tabs.className='prohouse-services-tabs';const search=document.createElement('input');search.className='prohouse-services-search';search.type='search';search.placeholder=ru?'Поиск услуги...':'Xizmat qidirish...';const grid=document.createElement('div');grid.className='prohouse-services-grid';let active='home'
   const tabData=[['home','Uy bilan bog‘liq xizmatlar','Услуги для дома','Remont, tozalash, dizayn va boshqalar','Ремонт, клининг, дизайн и другое'],['finance','Moliyaviy va huquqiy xizmatlar','Финансовые и юридические услуги','Notarius, baholash va sug‘urta','Нотариус, оценка va страхование'],['interactive','Interaktiv xizmatlar','Интерактивные сервисы','Soya hisoblash va qurilish statistikasi','Расчёт тени и строительная статистика']]
   const render=()=>{grid.innerHTML='';search.value='';const items=active==='home'?services.map(s=>({uz: s.name_uz,ru:s.name_ru||s.name_uz,descUz:'Xizmat',descRu:'Услуга',href:`/listings?tab=all&taxonomy=${encodeURIComponent(s.code)}`,icon:icons[s.code]||'🛠️'})):active==='finance'?finance:interactive;items.forEach(item=>{const a=document.createElement('a');a.href=item.href;a.className='prohouse-service-card';if(item.external){a.target='_blank';a.rel='noopener noreferrer'}a.dataset.search=`${item.uz} ${item.ru} ${item.descUz} ${item.descRu}`.toLowerCase();const i=document.createElement('span');i.className='prohouse-service-icon';i.textContent=item.icon;const c=document.createElement('span');c.className='prohouse-service-content';const n=document.createElement('strong');n.className='prohouse-service-name';n.textContent=ru?item.ru:item.uz;const s=document.createElement('span');s.className='prohouse-service-sub';s.textContent=ru?item.descRu:item.descUz;const ar=document.createElement('span');ar.className='prohouse-service-arrow';ar.textContent='›';c.append(n,s);a.append(i,c,ar);grid.appendChild(a)})}
   tabData.forEach(t=>{const b=document.createElement('button');b.type='button';b.className='prohouse-services-tab'+(t[0]===active?' active':'');b.innerHTML=`${ru?t[2]:t[1]}<span>${ru?t[4]:t[3]}</span>`;b.onclick=()=>{active=t[0];tabs.querySelectorAll('.prohouse-services-tab').forEach(el=>el.classList.remove('active'));b.classList.add('active');render()};tabs.appendChild(b)})
   search.oninput=()=>{const q=search.value.toLowerCase().trim();grid.querySelectorAll<HTMLElement>('.prohouse-service-card').forEach(c=>c.style.display=!q||c.dataset.search?.includes(q)?'flex':'none')}
   const note=document.createElement('div');note.className='prohouse-services-note';note.textContent=ru?'Существующие услуги дома сохранены. Страхование подготовлено для будущей API-интеграции с партнёрами.':'Mavjud uy xizmatlari saqlandi. Sug‘urta hamkor kompaniyalar API integratsiyasiga tayyorlangan.'
   render();modal.append(x,head,tabs,search,grid,note);overlay.append(modal);document.body.append(overlay);document.body.style.overflow='hidden'
  }
  const updateAccount=()=>{const b=document.querySelector('.account-btn') as HTMLButtonElement|null;if(!b)return;const ru=isRu();const text=userId?(ru?'Личный кабинет':'Shaxsiy kabinet'):(ru?'Войти / Регистрация':'Kirish / Ro‘yxatdan o‘tish');if(b.textContent!==text)b.textContent=text}
  const handle=(e:MouseEvent)=>{const t=e.target as HTMLElement|null;const link=t?.closest('a') as HTMLAnchorElement|null;if(link){const text=link.textContent?.trim()||'';if(text==='Услуги'||text==='Xizmatlar'){e.preventDefault();void openServices();return}}const b=t?.closest('.account-btn') as HTMLButtonElement|null;if(b){e.preventDefault();window.location.assign(userId?'/account':'/register')}}
  const sync=async()=>{try{const{data:{user}}=await supabase.auth.getUser();if(mounted){userId=user?.id??null;updateAccount()}}catch{}}
  document.addEventListener('click',handle);window.addEventListener('royalhouse-language-change',updateAccount);updateAccount();void sync();const{data:listener}=supabase.auth.onAuthStateChange((_e,s)=>{userId=s?.user?.id??null;updateAccount()})
  return()=>{mounted=false;document.removeEventListener('click',handle);window.removeEventListener('royalhouse-language-change',updateAccount);listener.subscription.unsubscribe();close()}
 },[]);return null
}
