'use client'

import { useEffect, useMemo, useState } from 'react'

type RentalState = { max_guests:string; included_guests:string; extra_guest_fee:string; bedrooms:string; single_beds:string; double_beds:string; bathrooms:string; check_in:string; check_out:string; quiet_hours:string; policies:string[]; amenities:string[]; deposit_percent:string; blocked_dates:string[]; date_prices:Record<string,string>; weekday_price:string; weekend_price:string }
const EMPTY:RentalState={max_guests:'',included_guests:'',extra_guest_fee:'',bedrooms:'',single_beds:'',double_beds:'',bathrooms:'',check_in:'14:00',check_out:'12:00',quiet_hours:'22:00–07:00',policies:[],amenities:[],deposit_percent:'15',blocked_dates:[],date_prices:{},weekday_price:'',weekend_price:''}
const amenities=[['pool','Ochiq hovuz'],['indoor_pool','Yopiq hovuz'],['wifi','Wi‑Fi'],['parking','Avtoturargoh'],['kitchen','Oshxona'],['bbq','Barbekyu'],['karaoke','Karaoke'],['billiard','Bilyard'],['tennis','Stol tennisi'],['sauna','Sauna'],['playground','Bolalar maydonchasi'],['jacuzzi','Jakuzi']]
const policies=[['corporate','Korporativ mehmonlar'],['alcohol','Spirtli ichimliklar'],['pets','Uy hayvonlari'],['marriage','Nikoh guvohnomasi']]
const pad=(n:number)=>String(n).padStart(2,'0');const iso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`
const parse=(raw:string):RentalState=>{try{const parsed:any=JSON.parse(raw||'{}');return {...EMPTY,...parsed,included_guests:parsed.included_guests??parsed.included_guest_count??parsed.guests_included??parsed.base_guests??'',extra_guest_fee:parsed.extra_guest_fee??parsed.extra_guest_price??parsed.additional_guest_price??parsed.extra_person_price??parsed.extra_guest_charge??''}}catch{return {...EMPTY}}}
const money=(value:string)=>value?new Intl.NumberFormat('uz-UZ').format(Number(String(value).replace(/\s/g,'')))+' so‘m':'—'

export default function RentalBookingSettings({value,onChange,basePrice,onBasePriceChange: _onBasePriceChange,ru=false}:{value:string;onChange:(v:string)=>void;basePrice:string;onBasePriceChange:(v:string)=>void;ru?:boolean}){
 const [state,setState]=useState<RentalState>(()=>parse(value));const [month,setMonth]=useState(()=>new Date())
 useEffect(()=>{setState(parse(value))},[value])
 const update=(patch:Partial<RentalState>)=>{const next={...state,...patch};setState(next);onChange(JSON.stringify(next))}
 const toggle=(key:'policies'|'amenities',v:string)=>update({[key]:state[key].includes(v)?state[key].filter(x=>x!==v):[...state[key],v]} as Partial<RentalState>)
 const days=useMemo(()=>{const start=new Date(month.getFullYear(),month.getMonth(),1);const end=new Date(month.getFullYear(),month.getMonth()+1,0);const first=(start.getDay()+6)%7;return [...Array(first).fill(null),...Array.from({length:end.getDate()},(_,i)=>new Date(month.getFullYear(),month.getMonth(),i+1))]},[month])
 const monthName=month.toLocaleDateString(ru?'ru-RU':'uz-UZ',{month:'long',year:'numeric'})
 const setDatePrice=(date:string,price:string)=>{const next={...state.date_prices};if(price)next[date]=price;else delete next[date];update({date_prices:next})}
 const effectivePrice=(date:string)=>{if(state.date_prices[date])return state.date_prices[date];const day=new Date(`${date}T00:00:00Z`).getUTCDay();return day===0||day===6?state.weekend_price:state.weekday_price||basePrice}
 return <div className="mt-6 rounded-3xl border border-emerald-100 bg-emerald-50/40 p-5 sm:p-6">
  <div><h3 className="text-lg font-black">{ru?'Данные для аренды и бронирования':'Ijara va bron uchun ma’lumotlar'}</h3><p className="mt-1 text-sm text-slate-500">{ru?'Эти данные будут показаны на странице объявления.':'Bu ma’lumotlar e’lon sahifasida ko‘rsatiladi.'}</p></div>
  <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{([['max_guests',ru?'Макс. гостей':'Maks. mehmonlar'],['included_guests',ru?'Гостей включено в цену':'Narxga kiradigan mehmonlar'],['extra_guest_fee',ru?'Доп. гость / ночь':'Ortiqcha mehmon / kecha'],['bedrooms',ru?'Спален':'Yotoqxonalar'],['single_beds',ru?'Односпальных мест':'Bir kishilik yotoqlar'],['double_beds',ru?'Двуспальных мест':'Ikki kishilik yotoqlar'],['bathrooms',ru?'Санузлов':'Hammom/WC']] as const).map(([k,label])=><label key={k} className="text-sm font-semibold">{label}<input type="number" min="0" value={state[k]} onChange={e=>update({[k]:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3"/>{k==='extra_guest_fee'&&<small className="mt-1 block text-slate-400">{ru?'Для каждого гостя сверх включённого количества.':'Belgilangan mehmon sonidan ortiq har bir mehmon uchun.'}</small>}</label>)}</div>
  <div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm font-semibold">{ru?'Заезд':'Kirish'}<input type="time" value={state.check_in} onChange={e=>update({check_in:e.target.value})} className="mt-2 w-full rounded-xl border bg-white p-3"/></label><label className="text-sm font-semibold">{ru?'Выезд':'Chiqish'}<input type="time" value={state.check_out} onChange={e=>update({check_out:e.target.value})} className="mt-2 w-full rounded-xl border bg-white p-3"/></label><label className="text-sm font-semibold">{ru?'Тихие часы':'Sokin soatlar'}<input value={state.quiet_hours} onChange={e=>update({quiet_hours:e.target.value})} className="mt-2 w-full rounded-xl border bg-white p-3"/></label></div>
  <div className="mt-5"><p className="text-sm font-bold">{ru?'Условия размещения':'Joylashish shartlari'}</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{policies.map(([key,label])=><label key={key} className="flex items-center gap-3 rounded-xl border bg-white p-3 text-sm"><input type="checkbox" checked={state.policies.includes(key)} onChange={()=>toggle('policies',key)}/><span>{ru?({'corporate':'Корпоративные гости','alcohol':'Спиртные напитки','pets':'Домашние животные','marriage':'Свидетельство о браке'} as any)[key]:label}</span></label>)}</div></div>
  <div className="mt-5"><p className="text-sm font-bold">{ru?'Удобства':'Qulayliklar'}</p><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">{amenities.map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-xl border bg-white p-3 text-sm"><input type="checkbox" checked={state.amenities.includes(key)} onChange={()=>toggle('amenities',key)}/><span>{ru?({'pool':'Открытый бассейн','indoor_pool':'Крытый бассейн','wifi':'Wi‑Fi','parking':'Парковка','kitchen':'Кухня','bbq':'Барбекю','karaoke':'Караоке','billiard':'Бильярд','tennis':'Настольный теннис','sauna':'Сауна','playground':'Детская площадка','jacuzzi':'Джакузи'} as any)[key]:label}</span></label>)}</div></div>
  <div className="mt-5 rounded-2xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{ru?'Цены по календарю':'Kalendar bo‘yicha narxlar'}</p><p className="mt-1 text-xs text-slate-500">{ru?'По умолчанию можно задать разные цены для будней и выходных. Отдельная дата имеет приоритет.':'Ish kunlari va dam olish kunlari uchun alohida narx bering. Alohida sana narxi ustun turadi.'}</p></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-sm font-black text-emerald-700">15% {ru?'аванс':'avans'}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">{ru?'Будни':'Ish kunlari'}<input value={state.weekday_price} onChange={e=>update({weekday_price:e.target.value})} inputMode="numeric" placeholder={basePrice?money(basePrice):'Masalan: 2 000 000'} className="mt-2 w-full rounded-xl border p-3"/><small className="mt-1 block text-slate-400">{ru?'Пн–Пт':'Du–Ju'}</small></label><label className="text-sm font-semibold">{ru?'Выходные':'Dam olish kunlari'}<input value={state.weekend_price} onChange={e=>update({weekend_price:e.target.value})} inputMode="numeric" placeholder={basePrice?money(basePrice):'Masalan: 3 000 000'} className="mt-2 w-full rounded-xl border p-3"/><small className="mt-1 block text-slate-400">{ru?'Сб–Вс':'Sha–Ya'}</small></label></div></div>
  <div className="mt-5 rounded-2xl border bg-white p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-bold">{ru?'Календарь доступности':'Mavjudlik kalendari'}</p><p className="text-xs text-slate-500">{ru?'Нажмите на дату, чтобы закрыть или открыть её. Цена под датой — цена за ночь.':'Sanani bosib band/yopiq qilib qo‘ying. Sana ostidagi narx — 1 kecha narxi.'}</p></div><div className="flex gap-1"><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} className="rounded-lg border px-3 py-1">‹</button><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} className="rounded-lg border px-3 py-1">›</button></div></div><div className="mt-4 text-center font-bold capitalize">{monthName}</div><div className="mt-3 grid grid-cols-7 gap-1 text-center text-[10px] font-bold text-slate-400">{['DU','SE','CHO','PA','JU','SHA','YA'].map(x=><span key={x}>{x}</span>)}</div><div className="mt-1 grid grid-cols-7 gap-1">{days.map((d,i)=>d?<div key={iso(d)} className={`rounded-lg border p-1 ${state.blocked_dates.includes(iso(d))?'border-red-200 bg-red-50':'border-slate-100 bg-white'}`}><button type="button" onClick={()=>update({blocked_dates:state.blocked_dates.includes(iso(d))?state.blocked_dates.filter(x=>x!==iso(d)):[...state.blocked_dates,iso(d)]})} className="w-full text-xs font-bold">{d.getDate()}</button><div className="mt-1 text-center text-[9px] font-bold text-slate-500">{money(effectivePrice(iso(d)))}</div><input aria-label={iso(d)} inputMode="numeric" placeholder={ru?'Цена даты':'Sana narxi'} value={state.date_prices[iso(d)]||''} onChange={e=>setDatePrice(iso(d),e.target.value)} className="mt-1 w-full rounded border px-1 py-1 text-[9px]"/></div>:<span key={i}/>)}</div><div className="mt-3 flex flex-wrap gap-3 text-xs"><span>🟢 {ru?'Свободно':'Bo‘sh'}</span><span>🟡 {ru?'Выходной':'Dam olish'}</span><span>🔴 {ru?'Закрыто':'Yopiq'}</span><span className="text-slate-500">{ru?'Отдельная цена даты имеет приоритет':'Alohida sana narxi ustun'}</span></div></div>
 </div>
}
