'use client'

import { useEffect, useMemo, useState } from 'react'

type Day={date:string;status:'free'|'blocked'|'booked';price:number|null}
type RentalSettings={max_guests?:string;check_in?:string;check_out?:string;quiet_hours?:string;amenities?:string[];policies?:string[];blocked_dates?:string[];date_prices?:Record<string,string>;deposit_percent?:string;bedrooms?:string;single_beds?:string;double_beds?:string;bathrooms?:string}
const pad=(n:number)=>String(n).padStart(2,'0')
const iso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`
const parse=(v:unknown):RentalSettings=>{try{return typeof v==='string'?JSON.parse(v||'{}'):(v&&typeof v==='object'?v as RentalSettings:{})}catch{return {}}}

export default function RentalBookingCalendar({listingId,settingsValue,basePrice,currency,ru=false}:{listingId:string;settingsValue:string;basePrice:number;currency:string;ru?:boolean}){
 const [days,setDays]=useState<Day[]>([]);const [month,setMonth]=useState(()=>new Date());const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<string[]>([]);const [guests,setGuests]=useState('1');const [booking,setBooking]=useState(false);const [message,setMessage]=useState('')
 const settings=useMemo(()=>parse(settingsValue),[settingsValue]);const depositPercent=Number(settings.deposit_percent||15)
 const load=async()=>{setLoading(true);try{const from=new Date(month.getFullYear(),month.getMonth(),1);const to=new Date(month.getFullYear(),month.getMonth()+1,0);const r=await fetch(`/api/rentals/availability?listingId=${encodeURIComponent(listingId)}&from=${iso(from)}&to=${iso(to)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Availability error');setDays(d.days||[])}catch(e){setMessage(e instanceof Error?e.message:'Calendarni yuklab bo‘lmadi')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[listingId,month.getFullYear(),month.getMonth()])
 const grid=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1);const offset=(first.getDay()+6)%7;const map=new Map(days.map(d=>[d.date,d]));return [...Array(offset).fill(null),...Array.from({length:new Date(month.getFullYear(),month.getMonth()+1,0).getDate()},(_,i)=>{const date=iso(new Date(month.getFullYear(),month.getMonth(),i+1));return map.get(date)||{date,status:'free',price:basePrice}})]},[days,month,basePrice])
 const nights=selected.length;const total=selected.reduce((sum,date)=>sum+Number(days.find(d=>d.date===date)?.price??settings.date_prices?.[date]??basePrice),0);const deposit=Math.round(total*depositPercent/100)
 const toggle=(day:Day)=>{if(day.status!=='free')return;const current=[...selected].sort();if(!current.length){setSelected([day.date]);return}const start=new Date(`${current[0]}T00:00:00Z`);const end=new Date(`${current[current.length-1]}T00:00:00Z`);const clicked=new Date(`${day.date}T00:00:00Z`);const from=clicked<start?clicked:start;const to=clicked>end?clicked:end;const range:string[]=[];for(let d=new Date(from);d<=to;d.setUTCDate(d.getUTCDate()+1))range.push(d.toISOString().slice(0,10));if(range.some(date=>{const item=days.find(x=>x.date===date);return item&&item.status!=='free'}))return;setSelected(range)}
 const submit=async()=>{if(!selected.length){setMessage(ru?'Выберите свободные даты.':'Avval bo‘sh sanalarni tanlang.');return}setBooking(true);setMessage('');try{const sorted=[...selected].sort();const first=sorted[0];const last=sorted[sorted.length-1];const lastDate=new Date(`${last}T00:00:00Z`);lastDate.setUTCDate(lastDate.getUTCDate()+1);const checkOut=lastDate.toISOString().slice(0,10);const r=await fetch('/api/rentals/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({listingId,checkIn:first,checkOut,guests:Number(guests),paymentProvider:'pending'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Bron qilishda xatolik');setMessage(ru?`Bron so‘rovi yaratildi. Avans: ${d.depositAmount} ${d.currency}.`:`Bron so‘rovi yaratildi. 15% avans: ${d.depositAmount} ${d.currency}.`);setSelected([]);void load()}catch(e){setMessage(e instanceof Error?e.message:'Bron qilishda xatolik')}finally{setBooking(false)}}
 const monthName=month.toLocaleDateString(ru?'ru-RU':'uz-UZ',{month:'long',year:'numeric'})
 return <section className="mt-8 rounded-3xl bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-black">{ru?'Календарь и бронирование':'Kalendar va bron qilish'}</h2><p className="mt-1 text-sm text-slate-500">{ru?'Свободные, занятые даты и цена за день.':'Bo‘sh, band sanalar va kunlik narxlar.'}</p></div><div className="rounded-2xl bg-amber-50 px-4 py-3 text-sm"><b>{depositPercent}% {ru?'предоплата':'avans'}</b><div className="text-xs text-slate-500">Payme / Click uchun tayyor</div></div></div>
 <div className="mt-5 rounded-2xl border p-4"><div className="flex items-center justify-between"><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} className="rounded-lg border px-3 py-1">‹</button><b className="capitalize">{monthName}</b><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} className="rounded-lg border px-3 py-1">›</button></div><div className="mt-4 grid grid-cols-7 gap-1 text-center text-[10px] font-bold text-slate-400">{['DU','SE','CHO','PA','JU','SHA','YA'].map(x=><span key={x}>{x}</span>)}</div>{loading?<div className="py-10 text-center text-sm text-slate-500">{ru?'Загрузка...':'Yuklanmoqda...'}</div>:<div className="mt-1 grid grid-cols-7 gap-1">{grid.map((day,i)=>day?<button type="button" key={day.date} onClick={()=>toggle(day)} disabled={day.status!=='free'} className={`min-h-14 rounded-lg border p-1 text-left ${day.status==='booked'?'bg-red-50 text-red-500':day.status==='blocked'?'bg-slate-100 text-slate-400':'bg-emerald-50 text-slate-800'} ${selected.includes(day.date)?'ring-2 ring-slate-950':''}`}><div className="text-xs font-bold">{Number(day.date.slice(-2))}</div><div className="mt-1 text-[9px]">{day.status==='booked'?(ru?'Занято':'Band'):day.status==='blocked'?(ru?'Закрыто':'Yopiq'):`${new Intl.NumberFormat(ru?'ru-RU':'uz-UZ').format(day.price??basePrice)} ${currency}`}</div></button>:<span key={i}/>)}</div>}</div>
 <div className="mt-3 flex flex-wrap gap-3 text-xs"><span>🟢 {ru?'Свободно':'Bo‘sh'}</span><span>🔴 {ru?'Забронировано':'Band'}</span><span>⚪ {ru?'Закрыто':'Yopiq'}</span></div>
 <div className="mt-5 grid gap-4 sm:grid-cols-[1fr_180px_auto] sm:items-end"><label className="text-sm font-semibold">{ru?'Гости':'Mehmonlar'}<input type="number" min="1" max={Number(settings.max_guests||99)} value={guests} onChange={e=>setGuests(e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label><div className="rounded-xl bg-slate-50 p-3 text-sm"><div>{nights} {ru?'дн.':'kun'}</div><b>{new Intl.NumberFormat(ru?'ru-RU':'uz-UZ').format(total)} {currency}</b><div className="text-xs text-slate-500">15%: {new Intl.NumberFormat(ru?'ru-RU':'uz-UZ').format(deposit)} {currency}</div></div><button type="button" onClick={submit} disabled={booking||!selected.length} className="rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white disabled:opacity-40">{booking?(ru?'Отправка...':'Yuborilmoqda...'):(ru?'Забронировать':'Bron qilish')}</button></div>{message&&<div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">{message}</div>}
 <p className="mt-4 text-xs text-slate-500">{ru?'Оплата 15% будет передана в платежный провайдер после подключения Payme/Click. Сейчас создаётся запрос на бронирование.':'15% avans Payme/Click integratsiyasi ulangach to‘lov provayderiga yuboriladi. Hozir bron so‘rovi yaratiladi.'}</p></section>
}
