'use client'

import { useEffect } from 'react'

type Lang = 'uz' | 'ru'

type Pair = [string, string]

// Detail-page-only compatibility layer.
// It intentionally touches only known platform UI strings. User-entered
// listing title, description, address, district and seller name are never
// translated here.
const UI_PAIRS: Pair[] = [
  ['Xaritani katta ko‘rish →', 'Открыть карту →'],
  ['Xaritani katta ko‘rish', 'Открыть карту'],
  ['Xavfsiz bitim', 'Безопасная сделка'],
  [
    'ProHouse tasdiqlangan e’lonlar va sotuvchilarni ajratib ko‘rsatadi. To‘lov/escrow xizmatlari keyingi integratsiya bosqichida litsenziyalangan hamkor orqali amalga oshiriladi.',
    'ProHouse выделяет проверенные объявления и продавцов. Платёжные/escrow-услуги будут предоставляться через лицензированного партнёра на следующем этапе интеграции.',
  ],
  ['Xaritada aniq joylashuv belgilanmagan.', 'Точное местоположение на карте не указано.'],
]

const normalize = (value: string) => value
  .replace(/[’ʻʼ`]/g, "'")
  .replace(/\s+/g, ' ')
  .trim()

function translateExact(value: string, lang: Lang) {
  const normalized = normalize(value)
  const pairs = lang === 'ru' ? UI_PAIRS : UI_PAIRS.map(([uz, ru]) => [ru, uz] as Pair)
  const found = pairs.find(([from]) => normalize(from) === normalized)
  return found ? found[1] : value
}

function applyProtectedUi(lang: Lang) {
  // The map container is protected from the global i18n walker because its
  // DOM is generated by Leaflet. The button immediately below it is platform
  // UI, so translate only that exact known label.
  document.querySelectorAll<HTMLElement>('[data-no-global-i18n] a').forEach((el) => {
    const value = el.textContent ?? ''
    const next = translateExact(value, lang)
    if (next !== value) el.textContent = next
  })

  // Safe-deal UI is regular page content, but keep an explicit selector so
  // this fix remains reliable even if another compatibility layer changes it.
  document.querySelectorAll<HTMLElement>('section').forEach((section) => {
    const heading = section.querySelector('h2')
    if (!heading) return
    const headingText = normalize(heading.textContent ?? '')
    if (headingText === normalize('Xavfsiz bitim') || headingText === normalize('Безопасная сделка')) {
      heading.textContent = lang === 'ru' ? 'Безопасная сделка' : 'Xavfsiz bitim'
      const paragraph = section.querySelector('p')
      if (paragraph) {
        const value = paragraph.textContent ?? ''
        const next = translateExact(value, lang)
        if (next !== value) paragraph.textContent = next
      }
    }
  })

  // Leaflet creates the price marker after React renders. Its number is
  // generated by Intl.NumberFormat, but the currency suffix is hard-coded
  // in the page component, so switch only that suffix and never the title.
  document.querySelectorAll<HTMLElement>('#listing-detail-map .leaflet-marker-icon').forEach((marker) => {
    const walker = document.createTreeWalker(marker, NodeFilter.SHOW_TEXT)
    const nodes: Text[] = []
    while (walker.nextNode()) nodes.push(walker.currentNode as Text)
    for (const node of nodes) {
      const value = node.nodeValue ?? ''
      const next = lang === 'ru'
        ? value.replace(/so[’ʻʼ`']m\b/gi, 'сум')
        : value.replace(/\bсум\b/gi, 'so‘m')
      if (next !== value) node.nodeValue = next
    }
  })
}

export default function ListingDetailLanguageFix() {
  useEffect(() => {
    let applying = false
    let queued = false

    const getLang = (): Lang => window.localStorage.getItem('prohouse-lang') === 'ru' ? 'ru' : 'uz'

    const run = () => {
      if (applying) return
      applying = true
      try {
        applyProtectedUi(getLang())
      } finally {
        applying = false
      }
    }

    const schedule = () => {
      if (queued) return
      queued = true
      window.requestAnimationFrame(() => {
        queued = false
        run()
      })
    }

    run()
    window.addEventListener('prohouse-language-change', schedule)
    window.addEventListener('storage', schedule)

    const observer = new MutationObserver(schedule)
    observer.observe(document.body, { childList: true, subtree: true, characterData: true })

    return () => {
      window.removeEventListener('prohouse-language-change', schedule)
      window.removeEventListener('storage', schedule)
      observer.disconnect()
    }
  }, [])

  return null
}
