'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { createClient } from '@/utils/supabase/client'
import ListingGallery from './ListingGallery'
import MobileListingActions from './MobileListingActions'
import { useI18n } from '@/app/components/I18nProvider'
import type { Lang } from '@/lib/i18n'

type ListingImage = { image_url: string; sort_order: number | null }
type Listing = {
  id: string; owner_id: string; title: string; title_ru?: string | null; description?: string | null
  listing_type: string; property_type: string; price: number; currency: string
  area_m2: number | null; rooms: number | null; floor: number | null; floors_total: number | null
  district: string | null; city: string; address?: string | null; latitude?: number | null; longitude?: number | null
  seller_type: string; seller_name: string | null; seller_phone?: string | null
  is_mortgage_available: boolean; is_verified: boolean; is_trusted_seller: boolean; is_featured: boolean
  published_at: string | null; listing_images?: ListingImage[]
}

const money = (value: number, currency: string, lang: Lang) => `${new Intl.NumberFormat(lang === 'ru' ? 'ru-RU' : 'uz-UZ').format(value)} ${currency === 'USD' ? '$' : lang === 'ru' ? 'сум' : 'so‘m'}`

function TrustedBadge({ lang }: { lang: Lang }) {
  return <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-extrabold text-emerald-700 ring-1 ring-emerald-100"><span className="flex h-4 w-4 items-center justify-center rounded-full bg-emerald-500 text-[10px] font-black text-white">✓</span>{lang === 'ru' ? 'Надёжный профиль' : 'Ishonchli profil'}</span>
}

function Map({ latitude, longitude, price, currency, title, lang }: { latitude: number | null; longitude: number | null; price: number; currency: string; title: string; lang: Lang }) {
  const [ready, setReady] = useState(false); const mapId = 'listing-detail-map'
  useEffect(() => { if (latitude == null || longitude == null) return; const scriptId = 'prohouse-leaflet-js'; const init = () => setReady(true); if ((window as any).L) { init(); return }; const existing = document.getElementById(scriptId) as HTMLScriptElement | null; if (existing) { existing.addEventListener('load', init); return () => existing.removeEventListener('load', init) }; const script = document.createElement('script'); script.id = scriptId; script.src = 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js'; script.async = true; script.onload = init; document.body.appendChild(script); return () => script.removeEventListener('load', init) }, [latitude, longitude])
  useEffect(() => { if (!ready || latitude == null || longitude == null || !(window as any).L) return; const L = (window as any).L; const element = document.getElementById(mapId); if (!element) return; const css = 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'; if (!document.querySelector(`link[href="${css}"]`)) { const link = document.createElement('link'); link.rel = 'stylesheet'; link.href = css; document.head.appendChild(link) }; const point: [number, number] = [Number(latitude), Number(longitude)]; const map = L.map(element).setView(point, 14); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '&copy; OpenStreetMap contributors', maxZoom: 19 }).addTo(map); const formatted = new Intl.NumberFormat(lang === 'ru' ? 'ru-RU' : 'uz-UZ', { notation: 'compact', maximumFractionDigits: 1 }).format(price); const suffix = currency === 'USD' ? '$' : lang === 'ru' ? 'сум' : 'so‘m'; const marker = L.marker(point, { icon: L.divIcon({ className: '', html: `<div style="background:#10b981;color:#fff;border:2px solid #fff;border-radius:999px;padding:7px 11px;box-shadow:0 3px 12px rgba(0,0,0,.2);font-size:12px;font-weight:800;white-space:nowrap">${formatted} ${suffix}</div>`, iconAnchor: [18, 18] }) }).addTo(map); marker.bindPopup(`<b>${money(price, currency, lang)}</b><br/>${title}`); const timer = window.setTimeout(() => map.invalidateSize(), 100); return () => { window.clearTimeout(timer); map.remove() } }, [ready, latitude, longitude, price, currency, title, lang])
  if (latitude == null || longitude == null) return <div className="flex h-[360px] items-center justify-center rounded-2xl border border-slate-200 bg-slate-50 p-6 text-center text-sm text-slate-500">{lang === 'ru' ? 'Для этого объявления точное местоположение на карте не указано.' : 'Bu e’lon uchun xaritada aniq joylashuv belgilanmagan.'}</div>
  return <div><div id={mapId} className="h-[360px] w-full rounded-2xl border border-slate-200 bg-slate-100" /><a className="mt-3 inline-flex rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold text-slate-700 hover:border-emerald-500 hover:text-emerald-600" target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${latitude}&mlon=${longitude}#map=14/${latitude}/${longitude}`}>{lang === 'ru' ? 'Открыть карту крупнее →' : 'Xaritani katta ko‘rish →'}</a></div>
}

export default function ListingDetailPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const { lang, setLang } = useI18n()
  const [listing, setListing] = useState<Listing | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [contacting, setContacting] = useState<'call' | 'chat' | null>(null); const [contactError, setContactError] = useState(''); const [phoneRevealed, setPhoneRevealed] = useState(false); const [revealedPhone, setRevealedPhone] = useState(''); const [favorite, setFavorite] = useState(false); const [favoriteBusy, setFavoriteBusy] = useState(false); const [isOwner, setIsOwner] = useState(false)

  const text = lang === 'ru'
    ? { loading: 'Загрузка...', notFound: 'Объявление не найдено', back: 'Назад к объявлениям', myListings: 'Мои объявления', listings: 'Объявления', saved: 'Сохранено', save: 'Сохранить', favoriteError: 'Ошибка при работе с сохранёнными объявлениями.', saveError: 'Не удалось сохранить.', seller: 'Продавец', owner: 'От владельца', mortgage: 'Доступна ипотека', verified: 'Проверенный профиль', trustedMyId: 'Надёжный профиль подтверждён через MyID.', showPhone: 'Показать телефон', calling: 'Загрузка...', openChat: 'Написать в чат', openingChat: 'Открываем чат...', call: 'Позвонить', yourListing: 'Ваше объявление', manageListing: 'Это объявление открыто для управления, а не как объявление покупателя.', promote: '🚀 Продвинуть объявление', edit: '✎ Редактировать объявление', backToMyListings: '← Вернуться к моим объявлениям', description: 'Описание', noDescription: 'Описание не указано.', location: 'Расположение', locationHint: 'Местоположение, указанное автором объявления', safeDeal: 'Безопасная сделка', safeDealText: 'ProHouse выделяет проверенные объявления и продавцов. Платёжные и escrow-сервисы будут подключены на следующем этапе через лицензированного партнёра.', area: 'Площадь', rooms: 'Комнаты', floor: 'Этаж', propertyType: 'Тип недвижимости', apartment: 'Квартира', house: 'Частный дом', newBuilding: 'Новостройка', commercial: 'Коммерция', land: 'Земля', sellerDefault: 'Продавец', contactFailed: 'Не удалось отправить обращение.', phoneMissing: 'Номер телефона продавца не указан.' }
    : { loading: 'Yuklanmoqda...', notFound: 'E’lon topilmadi', back: 'E’lonlarga qaytish', myListings: 'E’lonlarim', listings: 'E’lonlar', saved: 'Saqlangan', save: 'Saqlash', favoriteError: 'Saqlanganlar bilan ishlashda xatolik.', saveError: 'Saqlashda xatolik yuz berdi.', seller: 'Sotuvchi', owner: 'Egadan', mortgage: 'Ipotekaga mumkin', verified: 'Tasdiqlangan profil', trustedMyId: 'MyID orqali tasdiqlangan Ishonchli profil.', showPhone: 'Telefonni ko‘rsatish', calling: 'Yuklanmoqda...', openChat: 'Chatga yozish', openingChat: 'Chat ochilmoqda...', call: 'Qo‘ng‘iroq qilish', yourListing: 'Sizning e’loningiz', manageListing: 'Bu e’lonni xaridor sifatida ko‘rish emas, boshqarish uchun ochdingiz.', promote: '🚀 E’lonni ilgari surish', edit: '✎ E’lonni tahrirlash', backToMyListings: '← E’lonlarimga qaytish', description: 'Tavsif', noDescription: 'Tavsif kiritilmagan.', location: 'Joylashuv', locationHint: 'E’lon beruvchi belgilagan joylashuv', safeDeal: 'Xavfsiz bitim', safeDealText: 'ProHouse tasdiqlangan e’lonlar va sotuvchilarni ajratib ko‘rsatadi. To‘lov/escrow xizmatlari keyingi integratsiya bosqichida litsenziyalangan hamkor orqali amalga oshiriladi.', area: 'Maydon', rooms: 'Xonalar', floor: 'Qavat', propertyType: 'Mulk turi', apartment: 'Kvartira', house: 'Xususiy uy', newBuilding: 'Yangi bino', commercial: 'Tijorat', land: 'Yer', sellerDefault: 'Sotuvchi', contactFailed: 'Murojaatni yuborib bo‘lmadi.', phoneMissing: 'Sotuvchi telefon raqami kiritilmagan.' }

  useEffect(() => { let mounted = true; const load = async () => { try { const supabase = createClient(); const [{ data: { user } }, { data, error }] = await Promise.all([supabase.auth.getUser(), supabase.from('listings').select('id,owner_id,title,title_ru,description,listing_type,property_type,price,currency,area_m2,rooms,floor,floors_total,district,city,address,latitude,longitude,seller_type,seller_name,seller_phone,is_mortgage_available,is_verified,is_trusted_seller,is_featured,published_at,listing_images(image_url,sort_order)').eq('id', params.id).eq('status', 'active').maybeSingle()]); if (error) throw error; if (!data) throw new Error(lang === 'ru' ? 'Объявление не найдено или сейчас неактивно.' : 'E’lon topilmadi yoki hozir faol emas'); if (mounted) { setListing(data as Listing); setIsOwner(Boolean(user && data.owner_id === user.id)) } } catch (e: any) { if (mounted) setError(e?.message || text.saveError) } finally { if (mounted) setLoading(false) } }; if (params.id) void load(); return () => { mounted = false } }, [params.id, lang, text.saveError])
  useEffect(() => { if (!listing || isOwner) return; (async()=>{ try { const response=await fetch(`/api/listings/events?listingId=${encodeURIComponent(listing.id)}`); if(response.ok){const result=await response.json();setFavorite(Boolean(result.favorite))} } catch {} })() }, [listing, isOwner])

  const toggleFavorite = async () => {
    if (!listing || favoriteBusy || isOwner) return
    setFavoriteBusy(true)
    try {
      const next = !favorite
      const response = await fetch('/api/listings/events', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ listingId:listing.id, action:next?'favorite':'unfavorite' }) })
      const result = await response.json().catch(()=>({}))
      if (response.status===401) { router.push(`/register?redirect=/listings/${listing.id}`); return }
      if (!response.ok) throw new Error(result.error || text.favoriteError)
      setFavorite(next)
    } catch(e) { setContactError(e instanceof Error?e.message:text.saveError) } finally { setFavoriteBusy(false) }
  }

  const contact = async (type: 'call' | 'chat') => {
    if (!listing || contacting || isOwner) return; setContactError(''); setContacting(type)
    try {
      const response = await fetch('/api/leads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ listingId: listing.id, leadType: type }) })
      const result = await response.json()
      if (!response.ok) { if (response.status === 401) { router.push(`/register?redirect=/listings/${listing.id}`); return }; throw new Error(result.error || text.contactFailed) }
      if (type === 'call') { if (!result.phone) throw new Error(text.phoneMissing); setRevealedPhone(result.phone); setPhoneRevealed(true); return }
      router.push(`/chat?listingId=${listing.id}&conversationId=${result.conversationId}`)
    } catch (e: any) { setContactError(e?.message || text.contactFailed) } finally { setContacting(null) }
  }

  const callSeller = () => { if (revealedPhone) window.location.href = `tel:${revealedPhone}` }
  if (loading) return <main className="min-h-screen bg-[#f6f7f8] p-8 text-center text-slate-500">{text.loading}</main>
  if (error || !listing) return <main className="min-h-screen bg-[#f6f7f8] p-8"><div className="mx-auto max-w-3xl rounded-2xl bg-white p-8 text-center"><h1 className="text-xl font-black">{error || text.notFound}</h1><Link href="/listings" className="mt-5 inline-flex rounded-xl bg-emerald-500 px-5 py-3 font-bold text-white">{text.back}</Link></div></main>

  const images = (listing.listing_images || []).slice().sort((a, b) => (a.sort_order ?? 0) - (b.sort_order ?? 0)); const title = lang === 'ru' ? (listing.title_ru || listing.title) : listing.title; const typeLabel: Record<string, string> = { apartment: text.apartment, house: text.house, new_building: text.newBuilding, commercial: text.commercial, land: text.land }

  return <main className="min-h-screen bg-[#f6f7f8] text-slate-900">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-[1200px] items-center justify-between px-4 sm:px-6"><Link href={isOwner ? '/account/listings' : '/listings'} className="font-black text-emerald-600">← {isOwner ? text.myListings : 'Prohouse'}</Link><div className="flex items-center gap-2">{!isOwner && <button onClick={toggleFavorite} disabled={favoriteBusy} className={`rounded-xl border px-4 py-2 text-sm font-extrabold ${favorite?'border-rose-200 bg-rose-50 text-rose-700':'border-slate-200 bg-white text-slate-700'} disabled:opacity-50`}>{favorite?`♥ ${text.saved}`:`♡ ${text.save}`}</button>}<button onClick={() => setLang(lang === 'uz' ? 'ru' : 'uz')} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">{lang === 'uz' ? 'O‘z / Ru' : 'Ru / O‘z'}</button></div></div></header>
    <div className="mx-auto max-w-[1200px] px-4 py-6 pb-24 sm:px-6 md:pb-6"><div className="mb-5 text-sm text-slate-500"><Link href={isOwner ? '/account/listings' : '/listings'} className="hover:text-emerald-600">{isOwner ? text.myListings : text.listings}</Link> <span className="mx-2">›</span> <span data-no-global-i18n>{title}</span></div>
      <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="grid lg:grid-cols-[1.35fr_.65fr]"><ListingGallery images={images} title={title}/>
        <div className="p-6 sm:p-8"><div className="flex flex-wrap gap-2">{listing.is_featured && <span className="rounded-lg bg-amber-400 px-2.5 py-1 text-xs font-black">TOP</span>}{listing.is_verified && <span className="rounded-lg bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">✓ {text.verified}</span>}{listing.is_trusted_seller && <TrustedBadge lang={lang}/>}</div><h1 data-no-global-i18n className="mt-4 text-2xl font-black sm:text-3xl">{title}</h1><p className="mt-3 text-2xl font-black text-emerald-600">{money(listing.price, listing.currency, lang)}</p><p data-no-global-i18n className="mt-3 text-sm text-slate-500">⌖ {listing.city}{listing.district ? `, ${listing.district}` : ''}{listing.address ? `, ${listing.address}` : ''}</p><div className="mt-6 grid grid-cols-2 gap-3">{listing.area_m2 != null && <div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-400">{text.area}</span><b className="mt-1 block">{listing.area_m2} m²</b></div>}{listing.rooms != null && <div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-400">{text.rooms}</span><b className="mt-1 block">{listing.rooms}</b></div>}{listing.floor != null && <div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-400">{text.floor}</span><b className="mt-1 block">{listing.floor}/{listing.floors_total}</b></div>}<div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-400">{text.propertyType}</span><b className="mt-1 block">{typeLabel[listing.property_type] || listing.property_type}</b></div></div>
          {isOwner ? <div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-emerald-700">{text.yourListing}</p><p className="mt-1 text-sm font-semibold text-slate-700">{text.manageListing}</p><div className="mt-4 grid gap-3"><Link href={`/account/monetization/checkout?listingId=${encodeURIComponent(listing.id)}`} className="rounded-xl bg-emerald-600 px-4 py-3 text-center text-sm font-black text-white hover:bg-emerald-700">{text.promote}</Link><Link href={`/account/listings/${listing.id}/edit`} className="rounded-xl border border-emerald-200 bg-white px-4 py-3 text-center text-sm font-black text-emerald-700 hover:bg-emerald-50">{text.edit}</Link><Link href="/account/listings" className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-center text-sm font-black text-slate-700">{text.backToMyListings}</Link></div></div> : <><div className="mt-6 rounded-2xl border border-emerald-100 bg-emerald-50 p-4"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-bold text-emerald-700">{text.seller}</p>{listing.is_trusted_seller && <TrustedBadge lang={lang}/>}</div><p className="mt-1 font-black">{listing.seller_type==='owner' && <span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{text.owner}</span>}{listing.is_mortgage_available && <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{text.mortgage}</span>}<span data-no-global-i18n>{listing.seller_name || text.sellerDefault}</span></p>{listing.is_verified && <p className="mt-1 text-xs text-emerald-700">✓ {text.verified}</p>}{listing.is_trusted_seller && <p className="mt-1 text-xs font-semibold text-emerald-700">{text.trustedMyId}</p>}{phoneRevealed && revealedPhone && <div className="mt-3 flex flex-wrap items-center gap-2"><span className="rounded-lg bg-white px-3 py-2 text-sm font-black text-slate-900 ring-1 ring-emerald-100">{revealedPhone}</span><button onClick={callSeller} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-black text-white hover:bg-emerald-700">☎ {text.call}</button></div>}</div>
          <div className="mt-5 grid grid-cols-2 gap-3">{phoneRevealed ? <button onClick={callSeller} className="rounded-xl bg-emerald-600 px-4 py-3 font-black text-white hover:bg-emerald-700">☎ {revealedPhone}</button> : <button onClick={() => void contact('call')} disabled={!!contacting} className="rounded-xl bg-emerald-600 px-4 py-3 font-black text-white hover:bg-emerald-700">{contacting === 'call' ? text.calling : `☎ ${text.showPhone}`}</button>}<button onClick={() => void contact('chat')} disabled={!!contacting} className="rounded-xl border border-emerald-200 bg-white px-4 py-3 font-black text-emerald-700 hover:bg-emerald-50 disabled:opacity-60">{contacting === 'chat' ? text.openingChat : `💬 ${text.openChat}`}</button></div>{contactError && <p className="mt-3 rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-700">{contactError}</p>}</>}</div></div></section>
      <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">{text.description}</h2><p data-no-global-i18n className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-600">{listing.description || text.noDescription}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">{text.location}</h2><p className="mt-1 mb-4 text-sm text-slate-500">{text.locationHint}</p><Map latitude={listing.latitude ?? null} longitude={listing.longitude ?? null} price={listing.price} currency={listing.currency} title={title} lang={lang}/></div></section>
      <section className="mt-5 rounded-2xl border border-emerald-100 bg-emerald-50 p-6"><h2 className="text-lg font-black">{text.safeDeal}</h2><p className="mt-1 text-sm text-slate-600">{text.safeDealText}</p></section>
    </div>
    {!isOwner && <MobileListingActions listingId={listing.id} onCall={() => void contact('call')} onChat={() => void contact('chat')} />}
  </main>
}
