'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'

type Lead={id:string;listing_id:string|null;market:string;bank_name:string;program_name:string;customer_name:string;customer_phone:string;property_price:number;down_payment:number;term_months:number;annual_rate:number;monthly_payment:number|null;status:string;created_at:string;listing?:{title:string;price:number}|null}

const money=(n:number)=>new Intl.NumberFormat('ru-RU').format(Math.round(n))+' so‘m'
const ruDate=(s:string)=>new Intl.DateTimeFormat('uz-UZ',{dateStyle:'medium',timeStyle:'short'}).format(new Date(s))

export default function MortgageAdminPage(){
 const [leads,setLeads]=useState<Lead[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 async function load(){setLoading(true);const auth=await fetch('/api/admin/me',{cache:'no-store'});if(!auth.ok){location.href='/admin/login';return};const r=await fetch('/api/admin/mortgage-leads',{cache:'no-store'});const d=await r.json();if(!r.ok){setError(d.error||'Xatolik');setLoading(false);return};setLeads(d.leads||[]);setLoading(false)}
 useEffect(()=>{void load()},[])
 async function status(id:string,status:string){const r=await fetch('/api/admin/mortgage-leads',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});if(r.ok) setLeads(v=>v.map(x=>x.id===id?{...x,status}:x))}
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><Link href="/admin" className="font-black text-emerald-700">← Admin</Link><b>Ipoteka leadlari</b></div></header><div className="mx-auto max-w-7xl px-4 py-8"><div><p className="font-bold text-emerald-600">Royalhouse Admin</p><h1 className="mt-1 text-3xl font-black">Ipoteka arizalari</h1><p className="mt-2 text-sm text-slate-500">Bank, kalkulyator va aniq e’lon bilan bog‘langan leadlar.</p></div>{error&&<div className="mt-5 rounded-2xl bg-red-50 p-4 text-red-700">{error}</div>}{loading?<div className="mt-6 rounded-3xl bg-white p-10 text-center">Yuklanmoqda...</div>:!leads.length?<div className="mt-6 rounded-3xl bg-white p-10 text-center">Hozircha ipoteka arizalari yo‘q.</div>:<div className="mt-6 space-y-4">{leads.map(l=><article key={l.id} className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{l.market==='primary'?'Birlamchi':'Ikkilamchi'}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{l.bank_name} · {l.program_name}</span><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{l.status}</span></div><h2 className="mt-3 text-xl font-black">{l.customer_name}</h2><a href={'tel:'+l.customer_phone} className="text-emerald-700 font-bold">{l.customer_phone}</a></div><div className="text-right text-sm text-slate-500">{ruDate(l.created_at)}<div className="mt-1 font-black text-slate-900">{money(l.property_price)}</div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Badal',money(l.down_payment)],['Muddat',Math.round(l.term_months/12)+' yil'],['Stavka',l.annual_rate+'%'],['Oylik',l.monthly_payment?money(l.monthly_payment):'—'],['Obyekt',l.listing?.title||'Umumiy kalkulyator']].map(([k,v])=><div key={String(k)} className="rounded-2xl bg-slate-50 p-4"><div className="text-xs text-slate-400">{k}</div><div className="mt-1 font-bold">{v}</div></div>)}</div><div className="mt-4 flex flex-wrap gap-2">{l.listing_id&&<Link href={'/listings/'+l.listing_id} className="rounded-xl border px-4 py-2 text-sm font-bold">E’lonni ochish</Link>}{['new','contacted','approved','rejected','closed'].map(s=><button key={s} onClick={()=>void status(l.id,s)} className={'rounded-xl px-4 py-2 text-sm font-bold '+(l.status===s?'bg-slate-950 text-white':'border bg-white')}>{s}</button>)}</div></article>)}</div>}</div></main>
}
