'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createClient } from '@/utils/supabase/client'

type Favorite = { listing_id:string; created_at:string; listing:{ id:string; title:string; title_ru?:string|null; price:number; currency:string; city:string; district:string|null; area_m2:number|null; rooms:number|null; listing_type:string; listing_images?:{image_url:string;sort_order:number|null}[] } | null }
const money=(v:number,c:string)=>`${new Intl.NumberFormat('ru-RU').format(Number(v))} ${c==='USD'?'$':'so‘m'}`

export default function FavoritesPage(){
 const router=useRouter(); const [items,setItems]=useState<Favorite[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState('')
 useEffect(()=>{let mounted=true;(async()=>{try{const db=createClient();const{data:{user}}=await db.auth.getUser();if(!user){router.replace('/register?redirect=/account/favorites');return}const{data,error}=await db.from('listing_favorites').select('listing_id,created_at,listings(id,title,title_ru,price,currency,city,district,area_m2,rooms,listing_type,listing_images(image_url,sort_order))').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;if(mounted)setItems((data||[]) as unknown as Favorite[])}catch(e){if(mounted)setError(e instanceof Error?e.message:'Saqlangan e’lonlarni yuklab bo‘lmadi.')}finally{if(mounted)setLoading(false)}})();return()=>{mounted=false}},[router])
 const remove=async(id:string)=>{setBusy(id);try{const r=await fetch('/api/listings/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({listingId:id,action:'unfavorite'})});if(!r.ok)throw new Error('E’lonni saqlanganlardan olib bo‘lmadi.');setItems(v=>v.filter(x=>x.listing_id!==id))}catch(e){setError(e instanceof Error?e.message:'Xatolik')}finally{setBusy('')}}
 return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:py-10"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><Link href="/account" className="text-sm font-extrabold text-emerald-700">← Shaxsiy kabinet</Link><Link href="/listings" className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">E’lonlarni ko‘rish</Link></header><section className="mt-5 rounded-3xl bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-600">Prohouse</p><h1 className="mt-2 text-3xl font-black">Saqlangan e’lonlar</h1><p className="mt-2 text-sm text-slate-500">Sizga yoqqan uylar va boshqa ko‘chmas mulklarni bir joyda saqlang.</p>{error&&<div className="mt-5 rounded-2xl bg-amber-50 px-4 py-3 text-sm text-amber-800">{error}</div>}{loading?<div className="mt-8 rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-500">Yuklanmoqda...</div>:!items.length?<div className="mt-8 rounded-2xl border border-dashed border-slate-300 p-10 text-center"><div className="text-4xl">♡</div><h2 className="mt-3 font-black">Hali saqlangan e’lon yo‘q</h2><p className="mt-1 text-sm text-slate-500">E’lon kartasidagi yurak tugmasi orqali qiziqqan variantlaringizni saqlang.</p><Link href="/listings" className="mt-5 inline-flex rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black text-white">E’lonlarni ko‘rish</Link></div>:<div className="mt-6 grid gap-4 sm:grid-cols-2">{items.map(f=>{const x=f.listing;if(!x)return null;const image=x.listing_images?.slice().sort((a,b)=>(a.sort_order??0)-(b.sort_order??0))[0]?.image_url;return <article key={f.listing_id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><Link href={`/listings/${x.id}`} className="block"><div className="aspect-[4/3] bg-slate-100">{image?<img src={image} alt={x.title} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-sm text-slate-400">Rasm yo‘q</div>}</div><div className="p-4"><h2 className="line-clamp-2 font-black">{x.title_ru||x.title}</h2><p className="mt-2 text-lg font-black text-emerald-600">{money(x.price,x.currency)}{x.listing_type==='rent'?' / oy':''}{x.listing_type==='daily'?' / kun':''}</p><p className="mt-1 text-sm text-slate-500">⌖ {x.city}{x.district?`, ${x.district}`:''}</p><div className="mt-3 flex gap-2 text-xs font-bold text-slate-500">{x.rooms!=null&&<span className="rounded-lg bg-slate-50 px-2 py-1">{x.rooms} xona</span>}{x.area_m2!=null&&<span className="rounded-lg bg-slate-50 px-2 py-1">{x.area_m2} m²</span>}</div></div></Link><div className="border-t border-slate-100 p-3"><button disabled={busy===x.id} onClick={()=>void remove(x.id)} className="w-full rounded-xl border border-red-100 bg-red-50 py-2.5 text-sm font-extrabold text-red-600 disabled:opacity-50">{busy===x.id?'Yuklanmoqda...':'♡ Saqlanganlardan olib tashlash'}</button></div></article>})}</div>}</section></div></main>
}
