import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/utils/supabase/server'

export default async function DeveloperCabinet(){
 const db=await createClient(); const {data:{user}}=await db.auth.getUser(); if(!user) redirect('/register')
 const {data:partner}=await db.from('partner_profiles').select('id,partner_type,display_name,company_name').eq('user_id',user.id).maybeSingle()
 if(!partner) return <main className="p-8">Developer kabineti faqat hamkor akkauntlari uchun.</main>
 const {data:developer}=await db.from('developer_profiles').select('*').eq('partner_profile_id',partner.id).maybeSingle()
 if(!developer) return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-5xl rounded-3xl bg-white p-8"><h1 className="text-2xl font-black">Developer kabineti</h1><p className="mt-3 text-slate-500">Developer profilingiz hali yaratilmagan.</p></div></main>
 const {data:complexes}=await db.from('residential_complexes').select('id,name,slug,city,district,status,completion_year').eq('developer_id',developer.id).order('created_at',{ascending:false})
 const complexIds=(complexes||[]).map(x=>x.id)
 let unitCount=0
 if(complexIds.length){ const {data:buildings}=await db.from('residential_buildings').select('id').in('complex_id',complexIds); const buildingIds=(buildings||[]).map(x=>x.id); if(buildingIds.length){ const {count}=await db.from('complex_units').select('id',{count:'exact',head:true}).in('building_id',buildingIds); unitCount=count||0 } }
 const {count:leadCount}=await db.from('developer_lead_requests').select('id',{count:'exact',head:true}).eq('developer_id',developer.id)
 return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-6xl"><Link href="/account" className="text-sm font-bold text-emerald-700">← Kabinet</Link><div className="mt-5 rounded-3xl bg-slate-900 p-7 text-white"><p className="text-sm text-slate-300">Developer kabineti</p><h1 className="mt-1 text-3xl font-black">{developer.developer_name}</h1><p className="mt-2 text-sm text-emerald-300">{developer.verification_status==='verified'?'✓ Tasdiqlangan':'Tekshiruv kutilmoqda'}</p></div><div className="mt-6 grid gap-5 sm:grid-cols-3"><div className="rounded-2xl bg-white p-5"><p className="text-xs font-bold text-slate-400">LOYIHALAR</p><p className="mt-2 text-3xl font-black">{complexes?.length||0}</p></div><div className="rounded-2xl bg-white p-5"><p className="text-xs font-bold text-slate-400">XONADONLAR</p><p className="mt-2 text-3xl font-black">{unitCount}</p></div><div className="rounded-2xl bg-white p-5"><p className="text-xs font-bold text-slate-400">LEADLAR</p><p className="mt-2 text-3xl font-black">{leadCount||0}</p></div></div><section className="mt-8"><div className="flex items-end justify-between"><h2 className="text-2xl font-black">Mening loyihalarim</h2><Link href="/new-buildings" className="text-sm font-bold text-emerald-700">Marketplace →</Link></div><div className="mt-4 grid gap-4 md:grid-cols-2">{(complexes||[]).map(c=><Link key={c.id} href={`/new-buildings/${c.slug}`} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><h3 className="font-black">{c.name}</h3><span className="text-xs font-bold text-emerald-600">{c.status}</span></div><p className="mt-2 text-sm text-slate-500">{c.city}{c.district?`, ${c.district}`:''}</p><p className="mt-4 text-xs text-slate-400">Topshirish: {c.completion_year||'—'}</p></Link>)}</div></section></div></main>
}
