'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { createClient } from '@/utils/supabase/client'
import ListingLocationPicker from '@/app/components/ListingLocationPicker'
import ListingImageManager from '@/app/components/ListingImageManager'
import { UZBEKISTAN_LOCATIONS } from '@/data/uzbekistan-locations'

type Category={code:string;parent_code:string|null;name_uz:string;name_ru:string|null;section_code:string;listing_type:string|null;property_type:string|null;entity_type:string;is_mortgage_filter:boolean;is_new_construction_filter:boolean;sort_order:number}
type Attribute={id:string;category_code:string;code:string;name_uz:string;name_ru:string|null;data_type:string;options:unknown;unit:string|null;is_required:boolean;sort_order:number}
type Listing={id:string;listing_code:string;title:string;description:string|null;listing_type:string;property_type:string;status:string;price:number;currency:string;area_m2:number|null;rooms:number|null;floor:number|null;floors_total:number|null;city:string;district:string|null;neighborhood:string|null;address:string|null;latitude:number|null;longitude:number|null;taxonomy_code:string|null;ownership_type:string|null;seller_type:string|null;is_mortgage_available:boolean;draft_data:Record<string,unknown>|null}
const steps=['Bo‘lim','Tur','Joylashuv','Xususiyatlar','Narx','Rasmlar','Tekshirish']
const sections:Record<string,string>={sale:'Sotib olish',rent:'Ijara',new_building:'Yangi uylar'}
const cleanDistrict=(v:string)=>v.replace(/ tumani$/i,'').replace(/ shahri$/i,'')

export default function EditListingWizard(){
 const params=useParams<{id:string}>();const router=useRouter()
 const [listing,setListing]=useState<Listing|null>(null);const [categories,setCategories]=useState<Category[]>([]);const [attributes,setAttributes]=useState<Attribute[]>([]);const [step,setStep]=useState(1);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('')
 const [form,setForm]=useState({taxonomy_code:'',listing_type:'sale',property_type:'apartment',title:'',description:'',price:'',currency:'UZS',area_m2:'',rooms:'',floor:'',floors_total:'',city:'Toshkent',district:'',address:'',neighborhood:''})
 const [location,setLocation]=useState({latitude:null as number|null,longitude:null as number|null});const [values,setValues]=useState<Record<string,string>>({})
 const selected=categories.find(c=>c.code===form.taxonomy_code)||null
 const region=useMemo(()=>form.city==='Toshkent'?UZBEKISTAN_LOCATIONS.find(x=>x.name==='Toshkent shahri'):UZBEKISTAN_LOCATIONS.find(x=>x.name===form.city),[form.city])
 const districts=region?.districts||[];const attrs=useMemo(()=>attributes.filter(a=>a.category_code===form.taxonomy_code&&a.code!=='ownership_type').sort((a,b)=>a.sort_order-b.sort_order),[attributes,form.taxonomy_code])
 const isHouse=form.property_type==='house';const isHouseSale=selected?.code==='sale_house';const isOwner=values.ownership_type==='owner';const mortgage=values.mortgage==='true'
 const update=(k:keyof typeof form,v:string)=>setForm(x=>({...x,[k]:v}))

 useEffect(()=>{let mounted=true;(async()=>{const db=createClient();const{data:{user}}=await db.auth.getUser();if(!user){router.replace('/register');return}const [{data,error:e1},{data:cats,error:e2},{data:attrsData,error:e3}]=await Promise.all([db.from('listings').select('id,listing_code,title,description,listing_type,property_type,status,price,currency,area_m2,rooms,floor,floors_total,city,district,neighborhood,address,latitude,longitude,taxonomy_code,ownership_type,seller_type,is_mortgage_available,draft_data').eq('id',params.id).eq('owner_id',user.id).maybeSingle(),db.from('partner_listing_taxonomy').select('code,parent_code,name_uz,name_ru,section_code,listing_type,property_type,entity_type,is_mortgage_filter,is_new_construction_filter,sort_order').eq('is_active',true).eq('allows_partner_listing',true).order('sort_order'),db.from('category_attributes').select('id,category_code,code,name_uz,name_ru,data_type,options,unit,is_required,sort_order').eq('is_active',true).order('sort_order')]);if(!mounted)return;if(e1){setError(e1.message);setLoading(false);return}if(e2)setError(e2.message);if(e3)setError(e3.message);if(!e1&&data){const row=data as Listing;setListing(row);setCategories((cats||[]) as Category[]);setAttributes((attrsData||[]) as Attribute[]);const draft=(row.draft_data||{}) as Record<string,unknown>;const a=(draft.attributes&&typeof draft.attributes==='object'?draft.attributes:{}) as Record<string,unknown>;setValues(Object.fromEntries(Object.entries(a).map(([k,v])=>[k,String(v??'')])));if(row.ownership_type)setValues(v=>({...v,ownership_type:row.ownership_type||''}));if(row.is_mortgage_available)setValues(v=>({...v,mortgage:'true'}));setForm({taxonomy_code:row.taxonomy_code||'',listing_type:row.listing_type||'sale',property_type:row.property_type||'apartment',title:row.title||'',description:row.description||'',price:String(row.price??''),currency:row.currency||'UZS',area_m2:row.area_m2==null?'':String(row.area_m2),rooms:row.rooms==null?'':String(row.rooms),floor:row.floor==null?'':String(row.floor),floors_total:row.floors_total==null?'':String(row.floors_total),city:row.city||'Toshkent',district:row.district||'',address:row.address||'',neighborhood:row.neighborhood||''});setLocation({latitude:row.latitude,longitude:row.longitude});setLoading(false)}})();return()=>{mounted=false}},[params.id,router])

 const validate=()=>{if(!form.taxonomy_code||!selected)return 'Bo‘lim va turini tanlang.';if((step>=3)&&(!form.city||!form.district))return 'Joylashuvni to‘liq tanlang.';if(step>=3&&(location.latitude==null||location.longitude==null))return 'Xaritadan joylashuvni belgilang.';if(step>=4&&!form.title.trim())return 'E’lon sarlavhasini kiriting.';if(step>=5&&(!form.price||!Number.isFinite(Number(form.price.replace(/\s/g,'')))))return 'To‘g‘ri narx kiriting.';return ''}
 const next=()=>{const e=validate();if(e){setError(e);return}setError('');setStep(s=>Math.min(7,s+1))};const back=()=>{setError('');setStep(s=>Math.max(1,s-1))}
 const save=async()=>{if(!listing)return;const e=validate();if(e){setError(e);return}setSaving(true);setError('');setSuccess('');try{const db=createClient();const{data:{user}}=await db.auth.getUser();if(!user)throw new Error('AUTH_REQUIRED');const price=Number(form.price.replace(/\s/g,''));const area_m2=form.area_m2?Number(form.area_m2):null;const rooms=form.rooms?Number(form.rooms):null;const floor=isHouse?null:(form.floor?Number(form.floor):null);const floors_total=isHouse?null:(form.floors_total?Number(form.floors_total):null);const status=listing.status==='draft'?'draft':'moderation';const draft={...(listing.draft_data||{}),...form,price:form.price.replace(/\s/g,''),latitude:location.latitude,longitude:location.longitude,attributes:values,ownership_type:isHouseSale&&isOwner?'owner':null};const{error:e1}=await db.from('listings').update({taxonomy_code:form.taxonomy_code,title:form.title.trim(),description:form.description.trim()||null,listing_type:selected?.listing_type||form.listing_type,property_type:selected?.property_type||form.property_type,price,currency:form.currency,area_m2,rooms,floor,floors_total,city:form.city,district:form.district,neighborhood:form.neighborhood||null,address:form.address||null,latitude:location.latitude,longitude:location.longitude,ownership_type:isHouseSale&&isOwner?'owner':null,seller_type:isHouseSale&&isOwner?'owner':null,is_mortgage_available:mortgage,draft_data:draft,status,moderation_note:null,moderation_updated_at:null,updated_at:new Date().toISOString()}).eq('id',listing.id).eq('owner_id',user.id);if(e1)throw e1;setListing(v=>v?{...v,status,price,area_m2,rooms,floor,floors_total,taxonomy_code:form.taxonomy_code,title:form.title.trim(),description:form.description.trim()||null,listing_type:selected?.listing_type||form.listing_type,property_type:selected?.property_type||form.property_type,currency:form.currency,city:form.city,district:form.district,neighborhood:form.neighborhood||null,address:form.address||null,latitude:location.latitude,longitude:location.longitude,ownership_type:isHouseSale&&isOwner?'owner':null,seller_type:isHouseSale&&isOwner?'owner':null,is_mortgage_available:mortgage,draft_data:draft}:v);setSuccess(listing.status==='draft'?'Qoralama saqlandi.':'O‘zgarishlar saqlandi va e’lon qayta moderatsiyaga yuborildi.');setTimeout(()=>router.push('/account/listings'),700)}catch(e){setError(e instanceof Error?e.message:'E’lonni saqlashda xatolik yuz berdi.')}finally{setSaving(false)}}

 if(loading)return <main className="min-h-screen bg-slate-50 p-8 text-center text-slate-500">Yuklanmoqda...</main>
 if(!listing)return <main className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-4xl rounded-3xl bg-white p-8 text-center"><p className="font-bold">{error||'E’lon topilmadi'}</p><Link href="/account/listings" className="mt-5 inline-flex rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white">Mening e’lonlarim</Link></div></main>
 return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:py-10"><div className="mx-auto max-w-4xl"><div className="mb-5 flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-slate-500">PROHOUSE</p><h1 className="mt-1 text-2xl font-bold">E’lonni tahrirlash</h1><p className="mt-1 text-sm text-slate-500">E’lon joylashtirishdagi kabi 7 bosqichda tahrirlang.</p></div><Link href="/account" className="shrink-0 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold">Shaxsiy kabinet</Link></div><div className="mb-5 grid grid-cols-7 gap-1">{steps.map((x,i)=><button type="button" key={x} onClick={()=>i+1<=step&&setStep(i+1)} className={`rounded-xl px-1 py-2 text-center text-[11px] font-semibold ${i+1===step?'bg-slate-950 text-white':i+1<step?'bg-slate-200 text-slate-700':'bg-white text-slate-400'}`}><span className="hidden sm:inline">{i+1}. </span>{x}</button>)}</div><section className="rounded-3xl bg-white p-5 shadow-sm sm:p-8">{error&&<div className="mb-5 rounded-2xl bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}{success&&<div className="mb-5 rounded-2xl bg-emerald-50 p-4 text-sm font-medium text-emerald-700">{success}</div>}
 {step===1&&<div><h2 className="text-xl font-bold">1. Bo‘limni tanlang</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(sections).map(([code,label])=><button type="button" key={code} onClick={()=>{const first=categories.find(c=>c.section_code===code&&c.parent_code);if(first)setForm(v=>({...v,taxonomy_code:first.code,listing_type:first.listing_type||v.listing_type,property_type:first.property_type||v.property_type}));setStep(2)}} className="rounded-2xl border p-5 text-left"><b>{label}</b><span className="mt-1 block text-sm text-slate-500">{categories.filter(c=>c.section_code===code).length} ta yo‘nalish</span></button>)}</div></div>}
 {step===2&&<div><h2 className="text-xl font-bold">2. Turini tanlang</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{categories.filter(c=>c.parent_code).map(c=><button type="button" key={c.code} onClick={()=>setForm(v=>({...v,taxonomy_code:c.code,listing_type:c.listing_type||v.listing_type,property_type:c.property_type||v.property_type}))} className={`rounded-2xl border p-4 text-left ${selected?.code===c.code?'border-slate-950 bg-slate-50':''}`}><b>{c.name_uz}</b><span className="mt-1 block text-xs text-slate-500">{c.property_type||c.entity_type}</span></button>)}</div><p className="mt-4 text-xs text-slate-400">Tanlovdan so‘ng “Davom etish” tugmasini bosing.</p></div>}
 {step===3&&<div><h2 className="text-xl font-bold">3. Joylashuv</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Shahar/viloyat<select value={form.city} onChange={e=>{update('city',e.target.value);update('district','')}} className="mt-2 w-full rounded-xl border p-3"><option>Toshkent</option>{UZBEKISTAN_LOCATIONS.filter(x=>x.name!=='Toshkent shahri').map(x=><option key={x.name}>{x.name}</option>)}</select></label><label className="text-sm font-semibold">Tuman/shahar<select value={form.district} onChange={e=>update('district',e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="">Tanlang</option>{districts.map(x=><option key={x}>{cleanDistrict(x)}</option>)}</select></label></div><input value={form.address} onChange={e=>update('address',e.target.value)} placeholder="Ko‘cha, uy raqami (ixtiyoriy)" className="mt-4 w-full rounded-xl border p-3"/><div className="mt-4"><ListingLocationPicker latitude={location.latitude} longitude={location.longitude} onChange={(latitude,longitude)=>setLocation({latitude,longitude})}/></div></div>}
 {step===4&&<div><h2 className="text-xl font-bold">4. Xususiyatlar</h2>{isHouseSale&&<label className="mt-5 flex cursor-pointer items-center gap-3 rounded-2xl border p-4"><input type="checkbox" checked={isOwner} onChange={e=>setValues(v=>({...v,ownership_type:e.target.checked?'owner':''}))} className="h-5 w-5 shrink-0"/><span><b>Mulk egasi</b><small className="block text-slate-500">Men ushbu ko‘chmas mulkning egasiman.</small></span></label>}<div className="mt-5 grid gap-4 sm:grid-cols-2">{attrs.map(a=><label key={a.id} className="text-sm font-semibold">{a.name_uz}{a.unit?` (${a.unit})`:''}{a.is_required?' *':''}<input type={a.data_type==='number'?'number':'text'} value={values[a.code]??''} onChange={e=>setValues(v=>({...v,[a.code]:e.target.value}))} className="mt-2 w-full rounded-xl border p-3"/></label>)}</div>{!isHouse&&<div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Uy qavati<input type="number" value={form.floor} onChange={e=>update('floor',e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label><label className="text-sm font-semibold">Qavatlar soni<input type="number" value={form.floors_total} onChange={e=>update('floors_total',e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label></div>}<input value={form.title} onChange={e=>update('title',e.target.value)} placeholder="E’lon sarlavhasi" className="mt-5 w-full rounded-xl border p-3"/><textarea value={form.description} onChange={e=>update('description',e.target.value)} placeholder="Tavsif" rows={5} className="mt-4 w-full rounded-xl border p-3"/></div>}
 {step===5&&<div><h2 className="text-xl font-bold">5. Narx va shartlar</h2><div className="mt-5 grid gap-4 sm:grid-cols-3"><input value={form.price} onChange={e=>update('price',e.target.value)} placeholder="Narx" inputMode="numeric" className="rounded-xl border p-3 sm:col-span-2"/><select value={form.currency} onChange={e=>update('currency',e.target.value)} className="rounded-xl border p-3"><option>UZS</option><option>USD</option></select></div><label className="mt-5 flex items-center gap-3 rounded-2xl border p-4"><input type="checkbox" checked={mortgage} onChange={e=>setValues(v=>({...v,mortgage:e.target.checked?'true':'false'}))}/><span><b>Ipotekaga mumkin</b><small className="block text-slate-500">Xaridor uchun ipoteka imkoniyati mavjud.</small></span></label></div>}
 {step===6&&<div><h2 className="text-xl font-bold">6. Rasmlar</h2><p className="mt-1 text-sm text-slate-500">Mavjud rasmlarni shu yerda boshqaring.</p><div className="mt-5"><ListingImageManager listingId={listing.id}/></div></div>}
 {step===7&&<div><h2 className="text-xl font-bold">7. Tekshirish</h2><div className="mt-5 space-y-3">{[['Bo‘lim',selected?.name_uz||'—'],['Joylashuv',`${form.city}, ${form.district}`],['Manzil',form.address||'—'],['Mulk egasi',isOwner?'Ha':'Yo‘q'],['Sarlavha',form.title||'—'],['Narx',`${form.price||'—'} ${form.currency}`],['Rasmlar','Mavjud rasmlar saqlanadi']].map(([a,b])=><div key={a} className="flex justify-between gap-5 rounded-2xl bg-slate-50 p-4 text-sm"><span className="text-slate-500">{a}</span><b className="text-right">{b}</b></div>)}</div><p className="mt-5 text-sm text-slate-500">Saqlash bosilganda o‘zgarishlar e’lon joylashtirishdagi kabi tekshiruvdan o‘tadi.</p></div>}
 <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t pt-5"><Link href="/account" className="rounded-xl border px-5 py-3 text-sm font-semibold">Shaxsiy kabinet</Link><div className="flex gap-2"><button type="button" onClick={back} disabled={step===1||saving} className="rounded-xl border px-5 py-3 text-sm font-semibold disabled:opacity-40">Orqaga</button>{step<7?<button type="button" onClick={next} disabled={saving} className="rounded-xl bg-slate-950 px-6 py-3 text-sm font-semibold text-white disabled:opacity-40">Davom etish</button>:<button type="button" onClick={()=>void save()} disabled={saving} className="rounded-xl bg-slate-950 px-6 py-3 text-sm font-semibold text-white disabled:opacity-40">{saving?'Saqlanmoqda...':'Saqlash va yuborish'}</button>}</div></div>
 </section></div></main>
}
