export type MortgageMarket = 'primary' | 'secondary'

export type MortgageProgram = {
  id: string
  bank: string
  bankShort: string
  program: string
  programRu: string
  markets: MortgageMarket[]
  rateLabel: string
  rateMin: number
  rateMax: number
  downPaymentLabel: string
  downPaymentMin: number
  termMonths: number
  maxAmount: number | null
  maxAmountLabel: string
  description: string
  descriptionRu: string
  borrower?: string
  property?: string
  notes?: string[]
  sourceUrl: string
}

export const mortgagePrograms: MortgageProgram[] = [
  {id:'xb-qulay',bank:'Xalq banki',bankShort:'XB',program:'Qulay ipoteka',programRu:'Льготная ипотека «Qulay»',markets:['primary','secondary'],rateLabel:'23–24%',rateMin:23,rateMax:24,downPaymentLabel:'25–40%',downPaymentMin:25,termMonths:180,maxAmount:1200000000,maxAmountLabel:'1,2 mlrd so‘mgacha',description:'Birlamchi va ikkilamchi bozordan uy-joy xaridi uchun.',descriptionRu:'Для покупки жилья на первичном и вторичном рынке.',sourceUrl:'https://xb.uz/page/qulay-ipoteka-krediti'},
  {id:'xb-oilaviy',bank:'Xalq banki',bankShort:'XB',program:'Oilaviy ipoteka krediti',programRu:'Семейная ипотека',markets:['secondary'],rateLabel:'21,5%',rateMin:21.5,rateMax:21.5,downPaymentLabel:'25%',downPaymentMin:25,termMonths:240,maxAmount:1000000000,maxAmountLabel:'Toshkentda 1 mlrd so‘mgacha',description:'Ikkilamchi bozor uchun. Toshkentda 1 mlrd, hududlarda 550 mln so‘mgacha.',descriptionRu:'Для вторичного рынка. До 1 млрд сумов в Ташкенте и до 550 млн в регионах.',sourceUrl:'https://xb.uz/page/oilaviy-ipoteka-krediti'},
  {id:'ipotekabank-maqul',bank:'Ipoteka-bank',bankShort:'IB',program:'Ma’qul',programRu:'«Ma’qul»',markets:['secondary'],rateLabel:'21,5%',rateMin:21.5,rateMax:21.5,downPaymentLabel:'26% dan',downPaymentMin:26,termMonths:240,maxAmount:800000000,maxAmountLabel:'800 mln so‘mgacha',description:'Jismoniy shaxsdan tayyor xonadon sotib olish uchun.',descriptionRu:'Для покупки готовой квартиры у физического лица.',borrower:'3 tagacha hamqarz',sourceUrl:'https://www.ipotekabank.uz/crediting/mortgage/'},
  {id:'ipotekabank-tijorat',bank:'Ipoteka-bank',bankShort:'IB',program:'Tijorat',programRu:'«Tijorat»',markets:['primary','secondary'],rateLabel:'22,5%',rateMin:22.5,rateMax:22.5,downPaymentLabel:'20% dan',downPaymentMin:20,termMonths:240,maxAmount:1700000000,maxAmountLabel:'1,7 mlrd so‘mgacha',description:'Birlamchi va ikkilamchi bozorda turar-joy uchun.',descriptionRu:'Для жилья на первичном и вторичном рынке.',borrower:'O‘zini o‘zi band qilganlar uchun ham mos',sourceUrl:'https://www.ipotekabank.uz/crediting/mortgage/'},
  {id:'ipotekabank-oson',bank:'Ipoteka-bank',bankShort:'IB',program:'Oson',programRu:'«Oson»',markets:['primary'],rateLabel:'16,99% dan',rateMin:16.99,rateMax:16.99,downPaymentLabel:'15% dan',downPaymentMin:15,termMonths:240,maxAmount:480000000,maxAmountLabel:'480 mln so‘mgacha',description:'Pastroq stavkali yangi qurilishga ipoteka.',descriptionRu:'Ипотека на новостройку по сниженной ставке.',borrower:'O‘zini o‘zi band qilganlar uchun mos; hamqarzisiz mumkin',sourceUrl:'https://www.ipotekabank.uz/crediting/mortgage/'},
  {id:'ipotekabank-imkoniyat',bank:'Ipoteka-bank',bankShort:'IB',program:'Imkoniyat',programRu:'«Imkoniyat»',markets:['primary'],rateLabel:'0–23%',rateMin:0,rateMax:23,downPaymentLabel:'15% dan',downPaymentMin:15,termMonths:240,maxAmount:1700000000,maxAmountLabel:'1,7 mlrd so‘mgacha',description:'Qurilish bosqichida hamkor quruvchilardan yangi uylar uchun.',descriptionRu:'Для новостроек от партнёров-застройщиков на этапе строительства.',sourceUrl:'https://www.ipotekabank.uz/crediting/mortgage/'},
  {id:'trast-refinance-market',bank:'Trastbank',bankShort:'TB',program:'Birlamchi va ikkilamchi bozor ipotekasi',programRu:'Ипотека на первичном и вторичном рынке',markets:['primary','secondary'],rateLabel:'21–21,5%',rateMin:21,rateMax:21.5,downPaymentLabel:'25–40%',downPaymentMin:25,termMonths:180,maxAmount:800000000,maxAmountLabel:'Toshkent 800 mln / hududlar 500 mln',description:'Kadastri mavjud foydalanishga topshirilgan turar-joy uchun.',descriptionRu:'Для введённого в эксплуатацию жилья с кадастром.',borrower:'18–60 yosh; doimiy daromad',property:'Kvartira yoki turar-joy',notes:['Boshlang‘ich badal: 25% → 21,5%; 40% → 21%','Annuitet yoki differensial','Imtiyozli davr yo‘q'],sourceUrl:'https://trastbank.uz/en/private/crediting/trastbank-mortgage-loan-for-purchasing-housing-in-primary-and-secondary-markets/'},
  {id:'trast-primary',bank:'Trastbank',bankShort:'TB',program:'Birlamchi bozordan uy-joy ipotekasi',programRu:'Ипотека на новостройку',markets:['primary'],rateLabel:'17% dan',rateMin:17,rateMax:17,downPaymentLabel:'—',downPaymentMin:0,termMonths:240,maxAmount:null,maxAmountLabel:'Shartlarga ko‘ra',description:'Birlamchi bozordagi ko‘p qavatli uylardan kvartira uchun.',descriptionRu:'Для покупки квартиры в многоквартирном доме на первичном рынке.',sourceUrl:'https://trastbank.uz/uz/private/crediting/birlamchi-bozordan-uy-sotib-olish-uchun-ipoteka-krediti/'},
  {id:'asaka-secondary',bank:'Asakabank',bankShort:'AB',program:'Universal Ipoteka 2.0',programRu:'Universal Ipoteka 2.0',markets:['primary','secondary'],rateLabel:'21,99%',rateMin:21.99,rateMax:21.99,downPaymentLabel:'25% dan',downPaymentMin:25,termMonths:240,maxAmount:800000000,maxAmountLabel:'Toshkent 800 mln so‘mgacha',description:'Birlamchi va ikkilamchi bozordan uy-joy xaridi uchun.',descriptionRu:'Для покупки жилья на первичном и вторичном рынке.',sourceUrl:'https://www.asakabank.uz/uz/physical-persons/credits/ipoteka-universal'},
  {id:'nbu-secondary',bank:'O‘zbekiston Milliy banki',bankShort:'NBU',program:'Ikkilamchi bozor uchun ipoteka',programRu:'Ипотека на вторичном рынке',markets:['secondary'],rateLabel:'21–21,5%',rateMin:21,rateMax:21.5,downPaymentLabel:'20–25%',downPaymentMin:20,termMonths:240,maxAmount:800000000,maxAmountLabel:'Toshkent 800 mln / hududlar 500 mln',description:'Ikkilamchi bozordan uy-joy xaridi uchun standart ipoteka.',descriptionRu:'Стандартная ипотека для покупки жилья на вторичном рынке.',notes:['Rasmiy daromadli mijozlar uchun 21%','Ish haqi loyihasi ishtirokchilari uchun 21,5%'],sourceUrl:'https://nbu.uz/jismoniy-shaxslarga-kreditlar/ipoteka-kreditlari'},
  {id:'brb-secondary',bank:'Biznesni rivojlantirish banki (BRB)',bankShort:'BRB',program:'Ikkilamchi',programRu:'«Иккиламчи»',markets:['secondary'],rateLabel:'22,9–24%',rateMin:22.9,rateMax:24,downPaymentLabel:'20%',downPaymentMin:20,termMonths:180,maxAmount:4400000000,maxAmountLabel:'Toshkent 4,4 mlrd / hududlar 2,2 mlrd',description:'Birlamchi va ikkilamchi bozorda uy-joy/xonadon xaridi.',descriptionRu:'Для покупки жилья и квартир на первичном и вторичном рынке.',sourceUrl:'https://brb.uz/jismoniy-shaxslarga/ipoteka'},
  {id:'brb-commercial',bank:'Biznesni rivojlantirish banki (BRB)',bankShort:'BRB',program:'Tijoriy',programRu:'«Коммерческая ипотека»',markets:['primary','secondary'],rateLabel:'19,5% dan',rateMin:19.5,rateMax:19.5,downPaymentLabel:'25% dan',downPaymentMin:25,termMonths:180,maxAmount:1000000000,maxAmountLabel:'1 mlrd so‘mgacha',description:'Birlamchi va ikkilamchi bozorda uy-joy xaridi uchun.',descriptionRu:'Для покупки жилья на первичном и вторичном рынке.',sourceUrl:'https://brb.uz/jismoniy-shaxslarga/ipoteka'},
  {id:'brb-online',bank:'Biznesni rivojlantirish banki (BRB)',bankShort:'BRB',program:'Onlayn ipoteka',programRu:'Онлайн-ипотека',markets:['primary'],rateLabel:'16,99%',rateMin:16.99,rateMax:16.99,downPaymentLabel:'15%',downPaymentMin:15,termMonths:240,maxAmount:480000000,maxAmountLabel:'480 mln so‘mgacha',description:'Yangi binoda uy xaridi uchun onlayn ariza.',descriptionRu:'Для покупки жилья в новостройке с онлайн-заявкой.',sourceUrl:'https://brb.uz/jismoniy-shaxslarga/ipoteka'},
  {id:'brb-madad',bank:'Biznesni rivojlantirish banki (BRB)',bankShort:'BRB',program:'Madad',programRu:'«Madad»',markets:['primary'],rateLabel:'22–23%',rateMin:22,rateMax:23,downPaymentLabel:'20%',downPaymentMin:20,termMonths:180,maxAmount:1100000000,maxAmountLabel:'1,1 mlrd so‘mgacha',description:'Yangi uydan xonadon xaridi uchun.',descriptionRu:'Для покупки квартиры в новостройке.',sourceUrl:'https://brb.uz/jismoniy-shaxslarga/ipoteka'},
  {id:'agro-yangi-hayot',bank:'Agrobank',bankShort:'AG',program:'Yangi hayot',programRu:'«Yangi hayot»',markets:['primary','secondary'],rateLabel:'21,99%',rateMin:21.99,rateMax:21.99,downPaymentLabel:'25%',downPaymentMin:25,termMonths:240,maxAmount:800000000,maxAmountLabel:'800 mln so‘mgacha',description:'Birlamchi va ikkilamchi uy-joy uchun.',descriptionRu:'Для покупки жилья на первичном и вторичном рынке.',sourceUrl:'https://agrobank.uz/uz/person/loans'},
  {id:'sqb-secondary',bank:'O‘zsanoatqurilishbank (SQB)',bankShort:'SQB',program:'Mulk ipoteka',programRu:'«Мулк ипотека»',markets:['secondary'],rateLabel:'21–24%',rateMin:21,rateMax:24,downPaymentLabel:'30%',downPaymentMin:30,termMonths:240,maxAmount:1500000000,maxAmountLabel:'Toshkent 1,5 mlrd / hududlar 800 mln',description:'Birlamchi yoki ikkilamchi bozordan uy-joy — kvartira yoki yakka tartibdagi uy sotib olish uchun.',descriptionRu:'Для покупки квартиры или частного дома на первичном или вторичном рынке.',notes:['Ikkilamchi bozor uchun boshlang‘ich badal kamida 30%','Differensial to‘lovda 12 oygacha imtiyozli davr','Stavka mijoz toifasi va muddatiga qarab 21–24%'],sourceUrl:'https://sqb.uz/uz/individuals/ipoteka/mulk-ipoteka-uz3831/'},
  {id:'sqb-primary',bank:'O‘zsanoatqurilishbank (SQB)',bankShort:'SQB',program:'Birlamchi uyga ipoteka',programRu:'«Ипотека на первичное жильё»',markets:['primary'],rateLabel:'19%',rateMin:19,rateMax:19,downPaymentLabel:'25%',downPaymentMin:25,termMonths:240,maxAmount:800000000,maxAmountLabel:'Toshkent 800 mln / hududlar 500 mln',description:'Foydalanishga topshirilgan ko‘p qavatli uydagi xonadonlar uchun.',descriptionRu:'Для квартир в сданных многоквартирных домах на первичном рынке.',notes:['Annuitet yoki differensial','Qarz yuki 50% gacha'],sourceUrl:'https://sqb.uz/uz/individuals/ipoteka/ipoteka-na-pervichnoe-zhile-uz/'},
  {id:'sqb-yangi-toshkent',bank:'O‘zsanoatqurilishbank (SQB)',bankShort:'SQB',program:'Yangi Toshkent',programRu:'«Новый Ташкент»',markets:['primary'],rateLabel:'18%',rateMin:18,rateMax:18,downPaymentLabel:'—',downPaymentMin:0,termMonths:240,maxAmount:1000000000,maxAmountLabel:'1 mlrd so‘mgacha',description:'Yangi Toshkent loyihalari uchun.',descriptionRu:'Для проектов «Новый Ташкент».',sourceUrl:'https://sqb.uz/uz/individuals/ipoteka/'},
  {id:'octo',bank:'Octobank',bankShort:'OCTO',program:'Uy-joy ipotekasi',programRu:'Ипотека на жильё',markets:['primary','secondary'],rateLabel:'20% dan',rateMin:20,rateMax:20,downPaymentLabel:'20% dan',downPaymentMin:20,termMonths:120,maxAmount:null,maxAmountLabel:'Shartlarga ko‘ra',description:'Yangi qurilgan va ikkilamchi uylar uchun.',descriptionRu:'Для новостроек и вторичного жилья.',notes:['Qat’iy stavka','Barcha turdagi turar joylar','Maosh loyihasi mijozlariga alohida shartlar'],sourceUrl:'https://octobank.uz/jismoniy-shaxslarga/ipoteka-octobank'},
  {id:'ipakyuli-secondary',bank:'Ipak Yo‘li Bank',bankShort:'IYB',program:'Ipoteka',programRu:'Ипотека',markets:['primary','secondary'],rateLabel:'21,9% dan',rateMin:21.9,rateMax:24.9,downPaymentLabel:'20% dan',downPaymentMin:20,termMonths:120,maxAmount:1500000000,maxAmountLabel:'1,5 mlrd so‘mgacha',description:'Birlamchi va ikkilamchi bozorda uy-joy uchun.',descriptionRu:'Для покупки жилья на первичном и вторичном рынке.',notes:['84 oy: 20% badal → 22,9%; 40% badal → 21,9%','120 oy: 20% badal → 23,9%','Norasmiy daromadda stavka 23,9–24,9%'],sourceUrl:'https://ipakyulibank.uz/physical/kreditlar/ipoteka/ipoteka-24'},
  {id:'ipakyuli-new',bank:'Ipak Yo‘li Bank',bankShort:'IYB',program:'Yangi qurilgan uylarga ipoteka',programRu:'Ипотека на новостройки',markets:['primary'],rateLabel:'16,5% dan',rateMin:16.5,rateMax:17.5,downPaymentLabel:'—',downPaymentMin:0,termMonths:240,maxAmount:480000000,maxAmountLabel:'480 mln so‘mgacha',description:'Toshkentda 17–17,5%, hududlarda 16,5% dan.',descriptionRu:'В Ташкенте 17–17,5%, в регионах от 16,5%.',borrower:'Rasmiy daromadsiz ham mavjud',sourceUrl:'https://ipakyulibank.uz/physical/kreditlar/ipoteka/yangi-qurilgan-uylarga-ipoteka'},
  {id:'aloqa-secondary',bank:'Aloqabank',bankShort:'ALOQA',program:'Ipoteka krediti',programRu:'Ипотека',markets:['primary','secondary'],rateLabel:'24%',rateMin:24,rateMax:24,downPaymentLabel:'20%',downPaymentMin:20,termMonths:240,maxAmount:800000000,maxAmountLabel:'800 mln so‘mgacha',description:'Kvartira yoki yakka tartibdagi uy-joy uchun.',descriptionRu:'Для квартиры или индивидуального жилого дома.',notes:['12 oygacha asosiy qarz bo‘yicha imtiyozli davr','Annuitet yoki differensial'],sourceUrl:'https://aloqabank.uz/uz/private/crediting/ipoteka-secondary/'},
  {id:'aloqa-primary',bank:'Aloqabank',bankShort:'ALOQA',program:'Yangi Toshkent / Ulushdor',programRu:'«Новый Ташкент» / долевая ипотека',markets:['primary'],rateLabel:'18–23%',rateMin:18,rateMax:23,downPaymentLabel:'—',downPaymentMin:0,termMonths:240,maxAmount:1280000000,maxAmountLabel:'1,28 mlrd so‘mgacha',description:'Hamkor quruvchilarning yangi loyihalari uchun.',descriptionRu:'Для новых проектов партнёрских застройщиков.',sourceUrl:'https://aloqabank.uz/uz/private/crediting/'},
  {id:'tenge-secondary',bank:'Tenge Bank',bankShort:'TENGE',program:'Ikkilamchi uy-joy uchun ipoteka',programRu:'Ипотека на вторичное жильё',markets:['secondary'],rateLabel:'24,6%',rateMin:24.6,rateMax:24.6,downPaymentLabel:'28%',downPaymentMin:28,termMonths:120,maxAmount:820000000,maxAmountLabel:'820 mln so‘mgacha',description:'Ikkilamchi uy-joy xaridi uchun.',descriptionRu:'Для покупки вторичного жилья.',sourceUrl:'https://tengebank.uz/credits'},
  {id:'tenge-new',bank:'Tenge Bank',bankShort:'TENGE',program:'Yangi turarjoyga ipoteka',programRu:'Ипотека на новостройку',markets:['primary'],rateLabel:'23,9% dan',rateMin:23.9,rateMax:23.9,downPaymentLabel:'25% dan',downPaymentMin:25,termMonths:180,maxAmount:null,maxAmountLabel:'Shartlarga ko‘ra',description:'Yangi turarjoy uchun.',descriptionRu:'Для нового жилья.',sourceUrl:'https://tengebank.uz/credits'},
  {id:'hamkor-secondary',bank:'Hamkorbank',bankShort:'HAMKOR',program:'Uy-joy ipotekasi',programRu:'Ипотека на жильё',markets:['secondary'],rateLabel:'25–27%',rateMin:25,rateMax:27,downPaymentLabel:'25–30%',downPaymentMin:25,termMonths:120,maxAmount:1000000000,maxAmountLabel:'1 mlrd so‘mgacha',description:'Birlamchi va ikkilamchi bozordagi uy-joylarni sotib olish uchun.',descriptionRu:'Для покупки жилья на первичном и вторичном рынке.',notes:['DTI ≤50%: 25–26% stavkalar','DTI 50–100%: 26–27% stavkalar','Boshlang‘ich badal 25–30%'],sourceUrl:'https://hamkorbank.uz/uz/physical/mortgage/bank-mortgage/'},
  {id:'hamkor-new',bank:'Hamkorbank',bankShort:'HAMKOR',program:'Yangi qurilgan uylardan uy-joy xaridi',programRu:'Ипотека на новостройки',markets:['primary'],rateLabel:'17% dan',rateMin:17,rateMax:17.5,downPaymentLabel:'15% dan',downPaymentMin:15,termMonths:240,maxAmount:1000000000,maxAmountLabel:'1 mlrd so‘mgacha',description:'Yangi qurilgan ko‘p qavatli uylardan xonadonlar uchun.',descriptionRu:'Для квартир в новых многоквартирных домах.',borrower:'18–60 yosh',sourceUrl:'https://hamkorbank.uz/uz/physical/mortgage/mortgage-new/'},
  {id:'mkbank-secondary',bank:'Mikrokreditbank (MKBank)',bankShort:'MKB',program:'Universal ipoteka',programRu:'«Universal ipoteka»',markets:['secondary'],rateLabel:'24–26%',rateMin:24,rateMax:26,downPaymentLabel:'25%',downPaymentMin:25,termMonths:240,maxAmount:1600000000,maxAmountLabel:'1,6 mlrd so‘mgacha',description:'Ikkilamchi bozordan yashash uchun uy-joy sotib olish.',descriptionRu:'Для покупки жилого дома на вторичном рынке.',notes:['5, 10 yoki 20 yil','25% boshlang‘ich badal','Stavka muddatga qarab 24%, 25% yoki 26%'],sourceUrl:'https://mkbank.uz/uz/private/crediting/mortgage-loan-secondary-market/'},
]

export const getMortgagePrograms = (market: MortgageMarket) => mortgagePrograms.filter(p => p.markets.includes(market))
