'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/utils/supabase/client'
import { getListingImageUrl } from '@/lib/listing-image'
import { useI18n } from '@/app/components/I18nProvider'

type Listing={id:string;title:string;title_ru?:string|null;description?:string|null;price:number;currency:string;city:string;district:string|null;property_type:string|null;listing_type:string;taxonomy_code:string|null;seller_name:string|null;is_verified:boolean;is_trusted_seller:boolean;is_featured:boolean;published_at:string|null;primary_image_url?:string|null}

export default function NewBuildingsPage(){
 const {lang}=useI18n()
 const ru=lang==='ru'
 const tx=(uz:string,rr:string)=>ru?rr:uz
 const [items,setItems]=useState<Listing[]>([])
 const [query,setQuery]=useState('')
 const [city,setCity]=useState('')
 const [sort,setSort]=useState('newest')
 const [loading,setLoading]=useState(true)
 const [error,setError]=useState('')

 useEffect(()=>{(async()=>{try{const db=createClient();const{data,error}=await db.from('listings').select('id,title,title_ru,description,price,currency,city,district,property_type,listing_type,taxonomy_code,seller_name,is_verified,is_trusted_seller,is_featured,published_at,primary_image_url').eq('status','active').in('taxonomy_code',['sale_new_building','new_building_complexes','new_building_apartments']).order('is_featured',{ascending:false}).order('published_at',{ascending:false});if(error)throw error;setItems((data||[]) as Listing[])}catch(e){setError(e instanceof Error?e.message:tx('Yangi uylarni yuklab bo‘lmadi.','Не удалось загрузить новостройки.'))}finally{setLoading(false)}})()},[ru])

 const cities=useMemo(()=>Array.from(new Set(items.map(x=>x.city).filter(Boolean))).sort(),[items])
 const visible=useMemo(()=>items.filter(x=>!city||x.city===city).filter(x=>!query||`${x.title} ${x.title_ru||''} ${x.seller_name||''} ${x.city} ${x.district||''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='priceLow'?a.price-b.price:sort==='priceHigh'?b.price-a.price:new Date(b.published_at||0).getTime()-new Date(a.published_at||0).getTime()),[items,city,query,sort])
 const money=(v:number,c:string)=>`${new Intl.NumberFormat(ru?'ru-RU':'uz-UZ').format(Number(v))} ${c==='USD'?'$':ru?'сум':'so‘m'}`

 return <main className="min-h-screen bg-[#f6f7f8] text-slate-900">
  <header className="border-b bg-white"><div className="mx-auto flex min-h-16 max-w-[1440px] items-center justify-between px-4"><Link href="/" className="text-xl font-black">Royal<span className="text-emerald-500">house</span></Link><div className="flex gap-2"><Link href="/listings?tab=sale&type=new_building" className="rounded-xl border px-3 py-2 text-xs font-bold">{tx('Barcha e’lonlar','Все объявления')}</Link><Link href="/listings/new" className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white">{tx('E’lon joylashtirish','Разместить объявление')}</Link></div></div></header>
  <section className="border-b bg-white"><div className="mx-auto max-w-[1440px] px-4 py-8"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-600">Royalhouse</p><h1 className="mt-2 text-4xl font-black sm:text-5xl">{tx('Yangi qurilishlar','Новостройки')}</h1><p className="mt-3 max-w-3xl text-base leading-7 text-slate-500">{tx('Quruvchilar va yangi uylar bo‘yicha takliflarni bir joyda toping. Xonadon, turar joy majmuasi va yangi bino takliflarini solishtiring.','Найдите предложения от застройщиков в одном месте: квартиры, жилые комплексы и новые дома.')}</p><div className="mt-6 grid gap-3 md:grid-cols-[1fr_220px_180px]"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tx('Majmua, quruvchi yoki hudud...','Комплекс, застройщик или район...')} className="h-12 rounded-xl border px-4 outline-none focus:border-emerald-500"/><select value={city} onChange={e=>setCity(e.target.value)} className="h-12 rounded-xl border px-4"><option value="">{tx('Barcha hududlar','Все регионы')}</option>{cities.map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} className="h-12 rounded-xl border px-4"><option value="newest">{tx('Yangi','Новые')}</option><option value="priceLow">{tx('Arzonidan','Сначала дешевле')}</option><option value="priceHigh">{tx('Qimmatidan','Сначала дороже')}</option></select></div></div></section>
  <section className="mx-auto max-w-[1440px] px-4 py-7">{error&&<div className="mb-5 rounded-2xl bg-amber-50 px-4 py-3 text-sm text-amber-800">{error}</div>}{loading?<div className="rounded-3xl bg-white p-12 text-center text-slate-500">{tx('Yangi qurilishlar yuklanmoqda...','Загрузка новостроек...')}</div>:!visible.length?<div className="rounded-3xl border border-dashed bg-white p-12 text-center"><h2 className="font-black">{tx('Hozircha yangi qurilish takliflari yo‘q','Пока нет предложений по новостройкам')}</h2><p className="mt-2 text-sm text-slate-500">{tx('Yangi qurilish e’lonlari paydo bo‘lganda shu yerda ko‘rinadi.','Новые предложения появятся здесь после публикации.')}</p></div>:<><div className="mb-4 flex items-center justify-between"><b>{visible.length} {tx('ta taklif','предложений')}</b><span className="text-sm text-slate-400">{tx('Quruvchi va yangi uylar','Застройщики и новостройки')}</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visible.map(x=>{const image=x.primary_image_url?getListingImageUrl(x.primary_image_url,'card'):undefined;const title=ru?(x.title_ru||x.title):x.title;return <Link key={x.id} href={`/listings/${x.id}`} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><div className="relative aspect-[4/3] overflow-hidden bg-slate-100">{image?<img src={image} alt={title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<div className="flex h-full items-center justify-center text-sm text-slate-400">{tx('Rasm yo‘q','Нет изображения')}</div>}{x.is_featured&&<span className="absolute left-3 top-3 rounded-lg bg-amber-400 px-2 py-1 text-xs font-black">TOP</span>}{x.is_verified&&<span className="absolute right-3 top-3 rounded-lg bg-white px-2 py-1 text-xs font-bold text-emerald-700">✓ {tx('Tasdiqlangan','Проверено')}</span>}</div><div className="p-5"><p className="text-xs font-bold text-emerald-600">{x.taxonomy_code==='new_building_complexes'?tx('Turar joy majmuasi','Жилой комплекс'):tx('Yangi xonadon','Новая квартира')}</p><h2 className="mt-2 line-clamp-2 text-lg font-black">{title}</h2>{x.description&&<p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{x.description}</p>}<div className="mt-4 text-lg font-black text-emerald-600">{x.price>0?money(x.price,x.currency):tx('Narx so‘rov bo‘yicha','Цена по запросу')}</div><p className="mt-2 text-xs font-bold text-slate-400">⌖ {x.city}{x.district?`, ${x.district}`:''}</p><div className="mt-4 border-t pt-3 text-xs font-bold text-slate-600">{x.seller_name||tx('Quruvchi / sotuvchi','Застройщик / продавец')}</div></div></Link>})}</div></>}</section>
  <section className="mx-auto max-w-[1440px] px-4 pb-10"><div className="grid gap-4 md:grid-cols-3"><div className="rounded-3xl bg-slate-900 p-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-emerald-400">01</p><h2 className="mt-2 text-xl font-black">{tx('Majmuani toping','Найдите комплекс')}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{tx('Hudud, narx va takliflar bo‘yicha yangi uylarni solishtiring.','Сравнивайте новостройки по району, цене и предложениям.')}</p></div><div className="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><p className="text-xs font-black uppercase tracking-widest text-emerald-600">02</p><h2 className="mt-2 text-xl font-black">{tx('Quruvchini tekshiring','Проверьте застройщика')}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{tx('Tasdiqlangan sotuvchi va quruvchi belgilariga e’tibor bering.','Обращайте внимание на отметки проверенных продавцов и застройщиков.')}</p></div><div className="rounded-3xl bg-emerald-600 p-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-emerald-100">03</p><h2 className="mt-2 text-xl font-black">{tx('Keyingi bosqich','Следующий этап')}</h2><p className="mt-2 text-sm leading-6 text-emerald-50">{tx('Majmua profili, blok/xonadon inventari va quruvchi kabineti shu ekotizimga ulanadi.','Профили комплексов, инвентарь квартир и кабинет застройщика будут подключены к этой экосистеме.')}</p></div></div></section>
 </main>
}
