'use client'

import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createClient } from '@/utils/supabase/client'
import ListingLocationPicker from '@/app/components/ListingLocationPicker'
import { UZBEKISTAN_LOCATIONS } from '@/data/uzbekistan-locations'
import { getListingImageStoragePath, isAcceptedListingImage, LISTING_IMAGE_ACCEPT, LISTING_IMAGE_BUCKET, LISTING_IMAGE_MAX_SIZE } from '@/utils/listing-images'

type Lang = 'uz' | 'ru'
type LocationNode = { name: string; districts: string[] }
type Category = { code:string; parent_code:string|null; name_uz:string; name_ru:string|null; section_code:string; listing_type:string|null; property_type:string|null; entity_type:string; is_listable?: boolean; sort_order:number }
type Img = { file:File; preview:string }
type ServiceRegion = { scope:'all'|'province'|'district'; province:string; district?:string }

const STEPS:{uz:string;ru:string}[] = [
  {uz:'Xizmat turi',ru:'Услуга'}, {uz:'Ma’lumotlar',ru:'Данные'}, {uz:'Hudud',ru:'Регион'},
  {uz:'Narx',ru:'Цена'}, {uz:'Rasmlar',ru:'Фото'}, {uz:'Tekshirish',ru:'Проверка'},
]
const cleanDistrict=(v:string)=>v.replace(/ tumani$/i,'').replace(/ shahri$/i,'')
const provinceLabel=(v:string)=>v==='Toshkent shahri'?'Toshkent shahri':v

export default function ServiceListingWizardV2(){
  const router=useRouter(); const db=createClient()
  const [lang,setLang]=useState<Lang>('uz'); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false)
  const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [categories,setCategories]=useState<Category[]>([])
  const [step,setStep]=useState(1); const [listingId,setListingId]=useState<string|null>(null); const [partnerType,setPartnerType]=useState<string|null>(null); const [selectedCode,setSelectedCode]=useState('')
  const [images,setImages]=useState<Img[]>([]); const [mainImage,setMainImage]=useState(0)
  const [form,setForm]=useState({taxonomy_code:'',listing_type:'service',property_type:'service',title:'',description:'',price:'',currency:'UZS',city:'Toshkent',district:'',address:'',contact_phone:'',company_name:''})
  const [location,setLocation]=useState<{latitude:number|null;longitude:number|null}>({latitude:null,longitude:null})
  const [regions,setRegions]=useState<ServiceRegion[]>([]); const [expanded,setExpanded]=useState<string|null>(null)
  const ru=lang==='ru'; const t=(uz:string,ruText:string)=>ru?ruText:uz
  const selected=categories.find(c=>c.code===selectedCode)||null

  const locationNodes=useMemo<LocationNode[]>(()=>UZBEKISTAN_LOCATIONS.map(x=>({name:x.name,districts:x.districts||[]})),[])
  const allSelected=regions.some(x=>x.scope==='all')
  const selectedProvinceNames=useMemo(()=>new Set(regions.filter(x=>x.scope==='province').map(x=>x.province)),[regions])
  const selectedDistrictKeys=useMemo(()=>new Set(regions.filter(x=>x.scope==='district').map(x=>`${x.province}::${x.district}`)),[regions])

  const update=(key:keyof typeof form,value:string)=>setForm(v=>({...v,[key]:value}))
  const provinceForCity=(city:string)=>city==='Toshkent'?locationNodes.find(x=>x.name==='Toshkent shahri'):locationNodes.find(x=>x.name===city)

  useEffect(()=>{const saved=window.localStorage.getItem('prohouse-lang');if(saved==='ru')setLang('ru');const onLanguageChange=(e:Event)=>{const n=(e as CustomEvent<Lang>).detail;if(n==='uz'||n==='ru')setLang(n)};window.addEventListener('prohouse-language-change',onLanguageChange);return()=>window.removeEventListener('prohouse-language-change',onLanguageChange)},[])
  useEffect(()=>{(async()=>{try{const r=await fetch('/api/listings/meta',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||t('Ma’lumotlar yuklanmadi','Не удалось загрузить данные'));const cs=(d.categories||[]).filter((c:Category)=>c.section_code==='services'&&c.entity_type==='service'&&c.is_listable!==false);setCategories(cs);setPartnerType(d.partnerType||null);if(!cs.length)throw new Error(t('Hozircha xizmat e’loni joylashtirish uchun mavjud yo‘nalish topilmadi.','Сейчас нет доступных направлений для размещения услуг.'))}catch(e){setError(e instanceof Error?e.message:t('Yuklashda xatolik','Ошибка загрузки'))}finally{setLoading(false)}})()},[])
  useEffect(()=>()=>images.forEach(i=>URL.revokeObjectURL(i.preview)),[images])

  const regionSummary=()=>{if(allSelected)return t('Butun O‘zbekiston','Весь Узбекистан');const p=regions.filter(x=>x.scope==='province').map(x=>provinceLabel(x.province));const d=regions.filter(x=>x.scope==='district').map(x=>`${provinceLabel(x.province)} / ${cleanDistrict(x.district||'')}`);return [...p,...d].join(', ')||t('Tanlanmagan','Не выбрано')}
  const toggleAll=()=>{setRegions(allSelected?[]:[{scope:'all',province:'O‘zbekiston'}]);setForm(v=>({...v,city:'',district:''}))}
  const toggleProvince=(province:string)=>{setRegions(prev=>{if(prev.some(x=>x.scope==='all'))return prev;if(prev.some(x=>x.scope==='province'&&x.province===province))return prev.filter(x=>!(x.scope==='province'&&x.province===province));return [...prev.filter(x=>!(x.scope==='district'&&x.province===province)),{scope:'province',province}]})}
  const toggleDistrict=(province:string,district:string)=>{setRegions(prev=>{if(prev.some(x=>x.scope==='all'||(x.scope==='province'&&x.province===province)))return prev;const key=`${province}::${district}`;if(prev.some(x=>x.scope==='district'&&`${x.province}::${x.district}`===key))return prev.filter(x=>!(x.scope==='district'&&`${x.province}::${x.district}`===key));return [...prev,{scope:'district',province,district}]})}
  const removeRegion=(r:ServiceRegion)=>setRegions(prev=>prev.filter(x=>!(x.scope===r.scope&&x.province===r.province&&x.district===r.district)))

  const primaryArea=regions.find(x=>x.scope==='province'||x.scope==='district')
  const payload=()=>({...form,taxonomy_code:selectedCode,listing_type:'service',property_type:'service',price:form.price.replace(/\s/g,''),latitude:location.latitude,longitude:location.longitude,service_area_scope:allSelected?'all':'selected',service_regions:regions})

  const ensureSession=async()=>{let u=(await db.auth.getUser()).data.user;if(!u){await db.auth.refreshSession();u=(await db.auth.getUser()).data.user}return u}
  const save=async(nextStep:number,status:'draft'|'moderation'='draft')=>{setSaving(true);setError('');try{const u=await ensureSession();if(!u)throw new Error('AUTH_REQUIRED');const r=await fetch('/api/listings/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({listingId,step:nextStep,data:payload(),status})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||t('Saqlashda xatolik','Ошибка сохранения'));setListingId(d.listing.id);setStep(nextStep)}catch(e){setError(e instanceof Error?e.message:t('Saqlashda xatolik','Ошибка сохранения'))}finally{setSaving(false)}}

  const validate=()=>{
    if(!selectedCode)return t('Xizmat turini tanlang.','Выберите услугу.')
    if(step>=2&&!form.title.trim())return t('Xizmat sarlavhasini kiriting.','Введите заголовок услуги.')
    if(step>=2&&!form.description.trim())return t('Xizmat tavsifini kiriting.','Введите описание услуги.')
    if(step>=3&&!regions.length)return t('Kamida bitta xizmat hududini tanlang.','Выберите хотя бы один регион оказания услуги.')
    if(step>=4&&(!form.price||!Number.isFinite(Number(form.price.replace(/\s/g,'')))))return t('To‘g‘ri narx kiriting.','Введите корректную цену.')
    if(step>=5&&images.length===0)return t('Kamida 1 ta rasm yuklang.','Загрузите хотя бы 1 фото.')
    return ''
  }
  const next=async()=>{const v=validate();if(v){setError(v);return}setError('');if(step<6)await save(step+1)}
  const back=()=>{setError('');setStep(s=>Math.max(1,s-1))}
  const cancel=async()=>{if(!listingId){router.push('/account');return}setSaving(true);try{const u=await ensureSession();if(!u)throw new Error('AUTH_REQUIRED');const r=await fetch(`/api/listings/draft?listingId=${encodeURIComponent(listingId)}`,{method:'DELETE'});if(!r.ok)throw new Error(t('Qoralamani bekor qilib bo‘lmadi.','Не удалось отменить черновик.'));router.push('/account')}catch(e){setError(e instanceof Error?e.message:t('Xatolik yuz berdi.','Произошла ошибка.'))}finally{setSaving(false)}}
  const addImages=(e:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(e.target.files||[]);e.target.value='';if(images.length+files.length>10){setError(t('Maksimal 10 ta rasm.','Максимум 10 фото.'));return}const bad=files.find(f=>!isAcceptedListingImage(f)||f.size>LISTING_IMAGE_MAX_SIZE);if(bad){setError(t('Faqat JPG, PNG, WebP yoki GIF rasm. Har biri 10 MB gacha.','Только JPG, PNG, WebP или GIF. Максимум 10 МБ на файл.'));return}setImages(x=>[...x,...files.map(file=>({file,preview:URL.createObjectURL(file)}))])}
  const removeImage=(i:number)=>{const target=images[i];if(target)URL.revokeObjectURL(target.preview);setImages(x=>x.filter((_,n)=>n!==i));setMainImage(0)}
  const getImageDimensions=(file:File):Promise<{width:number|null;height:number|null}>=new Promise(resolve=>{const url=URL.createObjectURL(file);const image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve({width:image.naturalWidth,height:image.naturalHeight})};image.onerror=()=>{URL.revokeObjectURL(url);resolve({width:null,height:null})};image.src=url})
  const submit=async()=>{const v=validate();if(v){setError(v);return}if(!listingId){setError(t('Qoralama topilmadi.','Черновик не найден.'));return}setSaving(true);setError('');const uploaded:string[]=[];let persisted=false;try{const u=await ensureSession();if(!u)throw new Error('AUTH_REQUIRED');const ordered=[images[mainImage],...images.filter((_,i)=>i!==mainImage)];const rows=[];for(let i=0;i<ordered.length;i++){const file=ordered[i].file;const path=getListingImageStoragePath(u.id,listingId,file.name);const up=await db.storage.from(LISTING_IMAGE_BUCKET).upload(path,file,{cacheControl:'31536000',upsert:false});if(up.error)throw up.error;uploaded.push(path);const {width,height}=await getImageDimensions(file);const pub=db.storage.from(LISTING_IMAGE_BUCKET).getPublicUrl(path);rows.push({listing_id:listingId,image_url:pub.data.publicUrl,storage_path:path,sort_order:i,width,height,size_bytes:file.size,mime_type:file.type})}if(rows.length){const {error:e}=await db.from('listing_images').insert(rows);if(e)throw e;persisted=true}const r=await fetch('/api/listings/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({listingId,step:6,data:payload(),status:'moderation'})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||t('Moderatsiyaga yuborilmadi','Не удалось отправить на модерацию'));setSuccess(t(`Xizmat e’loni moderatsiyaga yuborildi: ${d.listing.listing_code}`,`Объявление об услуге отправлено на модерацию: ${d.listing.listing_code}`));setTimeout(()=>router.push('/account/listings'),700)}catch(e){if(!persisted&&uploaded.length)await db.storage.from(LISTING_IMAGE_BUCKET).remove(uploaded);setError(e instanceof Error?e.message:t('E’lonni yuborishda xatolik','Ошибка отправки объявления'))}finally{setSaving(false)}}

  if(loading)return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-4xl rounded-3xl bg-white p-10 text-center">{t('Yuklanmoqda...','Загрузка...')}</div></main>
  return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:py-10"><div className="mx-auto max-w-4xl">
    <div className="mb-5 flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-slate-500">PROHOUSE</p><h1 className="mt-1 text-2xl font-bold text-slate-950">{t('Xizmat e’loni joylashtirish','Разместить объявление об услуге')}</h1><p className="mt-1 text-sm text-slate-500">{t('Xizmat ko‘rsatuvchi uchun alohida e’lon formasi.','Отдельная форма для поставщика услуг.')}</p></div><div className="flex shrink-0 gap-2"><button type="button" onClick={()=>{const n:Lang=ru?'uz':'ru';setLang(n);window.localStorage.setItem('prohouse-lang',n);window.dispatchEvent(new CustomEvent('prohouse-language-change',{detail:n}))}} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-extrabold text-slate-700">{ru?'Ru / O‘z':'O‘z / Ru'}</button><Link href="/account" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700">{t('Shaxsiy kabinet','Личный кабинет')}</Link></div></div>
    {partnerType&&<div className="mb-5 rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-sm text-emerald-800">{t('Xizmat e’lonlari xizmat ko‘rsatuvchi professional hamkorlar uchun mo‘ljallangan.','Объявления об услугах предназначены для профессиональных партнёров.')}</div>}
    <div className="mb-5 grid grid-cols-6 gap-1">{STEPS.map((x,i)=><div key={x.uz} className={`rounded-xl px-1 py-2 text-center text-[11px] font-semibold ${i+1===step?'bg-slate-950 text-white':i+1<step?'bg-slate-200 text-slate-700':'bg-white text-slate-400'}`}><span className="hidden sm:inline">{i+1}. </span>{ru?x.ru:x.uz}</div>)}</div>
    <section className="rounded-3xl bg-white p-5 shadow-sm sm:p-8">{error&&<div className="mb-5 rounded-2xl bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}{success&&<div className="mb-5 rounded-2xl bg-emerald-50 p-4 text-sm font-medium text-emerald-700">{success}</div>}
      {step===1&&<div><h2 className="text-xl font-bold">1. {t('Xizmat turini tanlang','Выберите услугу')}</h2><p className="mt-1 text-sm text-slate-500">{t('Siz taklif qiladigan xizmat yo‘nalishini tanlang.','Выберите направление услуги, которую вы предлагаете.')}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{categories.map(c=><button key={c.code} type="button" onClick={()=>{setSelectedCode(c.code);setForm(v=>({...v,taxonomy_code:c.code}))}} className={`rounded-2xl border p-5 text-left transition ${selectedCode===c.code?'border-emerald-500 bg-emerald-50':'hover:border-slate-950'}`}><b>{ru?(c.name_ru||c.name_uz):c.name_uz}</b><span className="mt-1 block text-sm text-slate-500">{t('Xizmat','Услуга')}</span></button>)}</div></div>}
      {step===2&&<div><h2 className="text-xl font-bold">2. {t('Xizmat ma’lumotlari','Данные об услуге')}</h2><input value={form.title} onChange={e=>update('title',e.target.value)} placeholder={t('Xizmat sarlavhasi','Заголовок услуги')} className="mt-5 w-full rounded-xl border p-3"/><textarea value={form.description} onChange={e=>update('description',e.target.value)} placeholder={t('Xizmatni batafsil tasvirlang','Подробно опишите услугу')} rows={7} className="mt-4 w-full rounded-xl border p-3"/><div className="mt-4 grid gap-4 sm:grid-cols-2"><input value={form.company_name} onChange={e=>update('company_name',e.target.value)} placeholder={t('Kompaniya yoki usta nomi (ixtiyoriy)','Название компании или мастера (необязательно)')} className="rounded-xl border p-3"/><input value={form.contact_phone} onChange={e=>update('contact_phone',e.target.value)} placeholder={t('Aloqa telefoni (ixtiyoriy)','Контактный телефон (необязательно)')} className="rounded-xl border p-3"/></div></div>}
      {step===3&&<div><h2 className="text-xl font-bold">3. {t('Xizmat ko‘rsatiladigan hududlar','Регионы оказания услуги')}</h2><p className="mt-1 text-sm text-slate-500">{t('Bir nechta viloyat, tuman yoki butun O‘zbekistonni tanlashingiz mumkin.','Можно выбрать несколько областей, районов или весь Узбекистан.')}</p>
        <button type="button" onClick={toggleAll} className={`mt-5 flex w-full items-center justify-between rounded-2xl border p-4 text-left ${allSelected?'border-emerald-500 bg-emerald-50':'border-slate-200'}`}><span><b>{t('Butun O‘zbekiston','Весь Узбекистан')}</b><span className="mt-1 block text-sm text-slate-500">{t('Barcha hududlarda xizmat ko‘rsataman','Работаю по всему Узбекистану')}</span></span><span className="text-sm font-bold">{allSelected?'✓':''}</span></button>
        {!allSelected&&<div className="mt-4 space-y-2">{locationNodes.map(node=>{const provinceChecked=selectedProvinceNames.has(node.name);const open=expanded===node.name;return <div key={node.name} className="overflow-hidden rounded-2xl border border-slate-200"><div className="flex items-center gap-3 p-3"><button type="button" onClick={()=>toggleProvince(node.name)} className={`flex flex-1 items-center gap-3 rounded-xl p-2 text-left ${provinceChecked?'bg-emerald-50':''}`}><span className={`flex h-5 w-5 items-center justify-center rounded border text-xs ${provinceChecked?'border-emerald-500 bg-emerald-500 text-white':'border-slate-300'}`}>{provinceChecked?'✓':''}</span><span><b>{provinceLabel(node.name)}</b><span className="ml-2 text-xs text-slate-500">{node.districts.length} {t('tuman/shahar','районов/городов')}</span></span></button><button type="button" disabled={provinceChecked} onClick={()=>setExpanded(open?null:node.name)} className="rounded-xl px-3 py-2 text-sm font-bold text-slate-600 disabled:opacity-30">{open?'−':'+'}</button></div>{open&&!provinceChecked&&<div className="grid gap-2 border-t bg-slate-50 p-3 sm:grid-cols-2">{node.districts.map(d=>{const checked=selectedDistrictKeys.has(`${node.name}::${d}`);return <button key={d} type="button" onClick={()=>toggleDistrict(node.name,d)} className={`rounded-xl border p-3 text-left text-sm ${checked?'border-emerald-500 bg-emerald-50 font-semibold':'border-slate-200 bg-white'}`}><span className="mr-2">{checked?'✓':'○'}</span>{cleanDistrict(d)}</button>})}</div>}</div>})}</div>}
        <div className="mt-5 rounded-2xl bg-slate-50 p-4"><div className="text-xs font-bold uppercase tracking-wide text-slate-500">{t('Tanlangan hududlar','Выбранные регионы')}</div>{regions.length===0?<div className="mt-2 text-sm text-slate-500">{t('Hali tanlanmagan','Пока ничего не выбрано')}</div>:allSelected?<div className="mt-2 font-semibold">{t('Butun O‘zbekiston','Весь Узбекистан')}</div>:<div className="mt-3 flex flex-wrap gap-2">{regions.map((r,i)=><button key={`${r.province}-${r.district}-${i}`} type="button" onClick={()=>removeRegion(r)} className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold shadow-sm">{r.scope==='province'?provinceLabel(r.province):`${provinceLabel(r.province)} / ${cleanDistrict(r.district||'')}`} ×</button>)}</div>}</div>
        <div className="mt-4"><ListingLocationPicker latitude={location.latitude} longitude={location.longitude} onChange={(latitude,longitude)=>setLocation({latitude,longitude})}/><p className="mt-2 text-xs text-slate-500">{t('Xarita ixtiyoriy: bir nechta hudud tanlanganda asosiy xizmat nuqtasini ko‘rsatish uchun foydalaning.','Карта необязательна: при нескольких регионах используйте её для указания основной точки оказания услуги.')}</p></div>
      </div>}
      {step===4&&<div><h2 className="text-xl font-bold">4. {t('Narx va shartlar','Цена и условия')}</h2><div className="mt-5 grid gap-4 sm:grid-cols-3"><input value={form.price} onChange={e=>update('price',e.target.value)} placeholder={t('Narx','Цена')} inputMode="numeric" className="rounded-xl border p-3 sm:col-span-2"/><select value={form.currency} onChange={e=>update('currency',e.target.value)} className="rounded-xl border p-3"><option>UZS</option><option>USD</option></select></div><p className="mt-3 text-sm text-slate-500">{t('Masalan: 150 000 so‘mdan yoki xizmat hajmiga qarab.','Например: от 150 000 сум или по объёму работ.')}</p></div>}
      {step===5&&<div><h2 className="text-xl font-bold">5. {t('Rasmlar','Фото')}</h2><p className="mt-1 text-sm text-slate-500">{t('Xizmatingiz namunalaridan 10 tagacha rasm yuklang.','Загрузите до 10 фото с примерами вашей работы.')}</p><label className="mt-5 flex cursor-pointer items-center justify-center rounded-2xl border-2 border-dashed p-10 text-sm font-semibold"><input type="file" accept={LISTING_IMAGE_ACCEPT} multiple onChange={addImages} className="hidden"/>{t('Rasmlarni tanlash','Выбрать фото')}</label><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{images.map((im,i)=><button type="button" key={im.preview} onClick={()=>setMainImage(i)} className="relative overflow-hidden rounded-2xl border text-left"><img src={im.preview} className="aspect-square w-full object-cover"/><span onClick={e=>{e.stopPropagation();removeImage(i)}} className="absolute right-2 top-2 rounded-full bg-white px-2 py-1 text-xs">×</span>{i===mainImage&&<span className="absolute bottom-2 left-2 rounded-full bg-slate-950 px-2 py-1 text-[10px] text-white">{t('Asosiy','Основное')}</span>}</button>)}</div></div>}
      {step===6&&<div><h2 className="text-xl font-bold">6. {t('Tekshirish','Проверка')}</h2><div className="mt-5 space-y-3">{[[t('Xizmat turi','Услуга'),ru?(selected?.name_ru||selected?.name_uz||'—'):(selected?.name_uz||'—')],[t('Sarlavha','Заголовок'),form.title||'—'],[t('Hududlar','Регионы'),regionSummary()],[t('Manzil','Адрес'),form.address||'—'],[t('Narx','Цена'),`${form.price||'—'} ${form.currency}`],[t('Rasmlar','Фото'),`${images.length} ${t('ta','шт.')}`]].map(([a,b])=><div key={a} className="flex justify-between gap-5 rounded-2xl bg-slate-50 p-4 text-sm"><span className="text-slate-500">{a}</span><b className="max-w-[70%] text-right">{b}</b></div>)}</div><p className="mt-5 text-sm text-slate-500">{t('E’lon moderatsiyaga yuborilgach, tasdiqlangandan so‘ng xizmatlar katalogida ko‘rsatiladi.','После отправки на модерацию объявление появится в каталоге услуг после подтверждения.')}</p></div>}
      <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t pt-5"><div className="flex gap-2"><button type="button" onClick={back} disabled={step===1||saving} className="rounded-xl border px-5 py-3 text-sm font-semibold disabled:opacity-40">{t('Orqaga','Назад')}</button><button type="button" onClick={()=>void cancel()} disabled={saving} className="rounded-xl border border-red-200 bg-red-50 px-5 py-3 text-sm font-semibold text-red-700 disabled:opacity-40">{t('Bekor qilish','Отмена')}</button></div>{step<6?<button type="button" onClick={next} disabled={saving||(step===1&&!selectedCode)} className="rounded-xl bg-slate-950 px-6 py-3 text-sm font-semibold text-white disabled:opacity-40">{saving?t('Saqlanmoqda...','Сохранение...'):t('Davom etish','Продолжить')}</button>:<button type="button" onClick={submit} disabled={saving} className="rounded-xl bg-slate-950 px-6 py-3 text-sm font-semibold text-white disabled:opacity-40">{saving?t('Yuborilmoqda...','Отправка...'):t('Xizmat e’lonini yuborish','Отправить объявление')}</button>}</div>
    </section></div></main>
}
