'use client'
import { FormEvent, useState } from 'react'
export default function LeadForm({developerId,complexId}:{developerId:string|null;complexId:string}){
 const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [message,setMessage]=useState(''); const [state,setState]=useState<'idle'|'sending'|'done'|'error'>('idle')
 async function submit(e:FormEvent){e.preventDefault();setState('sending');try{const r=await fetch('/api/developer/leads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({developer_id:developerId,complex_id:complexId,name,phone,message,source:'complex'})});if(!r.ok)throw new Error();setState('done')}catch{setState('error')}}
 if(!developerId)return <div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Loyiha bo‘yicha so‘rov</h2><p className="mt-2 text-sm text-slate-500">Developer ma’lumoti hali biriktirilmagan.</p></div>
 if(state==='done')return <div className="rounded-3xl bg-white p-6 shadow-sm"><div className="text-3xl">✓</div><h2 className="mt-3 text-xl font-black">So‘rovingiz yuborildi</h2><p className="mt-2 text-sm leading-6 text-slate-500">Developer vakili siz bilan bog‘lanadi.</p></div>
 return <form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Loyiha bo‘yicha so‘rov</h2><p className="mt-2 text-sm text-slate-500">Narx, mavjud xonadonlar yoki ko‘rish haqida ma’lumot oling.</p><div className="mt-5 space-y-3"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ismingiz" className="w-full rounded-xl border px-4 py-3 outline-none focus:border-emerald-500"/><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Telefon raqami" className="w-full rounded-xl border px-4 py-3 outline-none focus:border-emerald-500"/><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Savolingiz (ixtiyoriy)" rows={4} className="w-full rounded-xl border px-4 py-3 outline-none focus:border-emerald-500"/></div>{state==='error'&&<p className="mt-3 text-sm text-red-600">So‘rov yuborilmadi. Qayta urinib ko‘ring.</p>}<button disabled={state==='sending'} className="mt-4 w-full rounded-xl bg-emerald-600 px-4 py-3 font-black text-white disabled:opacity-50">{state==='sending'?'Yuborilmoqda...':'Murojaat yuborish'}</button><p className="mt-3 text-center text-[11px] text-slate-400">Ma’lumotlaringiz loyiha bo‘yicha aloqa uchun ishlatiladi.</p></form>
}
