'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/utils/supabase/client'

type Lang='uz'|'ru'
type Listing={id:string;title:string;title_ru?:string|null;price:number;currency:string;city:string;district:string|null;property_type:string;accommodation_type?:string|null;area_m2:number|null;rooms:number|null;image_url?:string}

const fallback:Listing[]=[
 {id:'demo-1',title:'Toshkent markazida qulay mehmonxona',title_ru:'Уютный отель в центре Ташкента',price:450000,currency:'UZS',city:'Toshkent',district:'Yunusobod',property_type:'house',accommodation_type:'hotel',area_m2:null,rooms:1,image_url:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=85'},
 {id:'demo-2',title:'Shinam kvartira — kunlik ijara',title_ru:'Уютная квартира — посуточная аренда',price:350000,currency:'UZS',city:'Toshkent',district:'Mirobod',property_type:'apartment',accommodation_type:'property',area_m2:55,rooms:2,image_url:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85'},
]

const money=(v:number,c:string)=>`${new Intl.NumberFormat('ru-RU').format(v)} ${c==='USD'?'$':'so‘m'}`

export default function DailyPage(){
 const [lang,setLang]=useState<Lang>('uz'); const [city,setCity]=useState(''); const [checkIn,setCheckIn]=useState(''); const [checkOut,setCheckOut]=useState(''); const [guests,setGuests]=useState('1'); const [listings,setListings]=useState< Listing[]>(fallback); const [searched,setSearched]=useState(false)
 useEffect(()=>{const saved=localStorage.getItem('prohouse-lang');if(saved==='ru')setLang('ru');(async()=>{try{const db=createClient();const {data}=await db.from('listings').select('*,listing_images(image_url,sort_order)').eq('status','active').eq('listing_type','daily').order('published_at',{ascending:false});if(data?.length)setListings(data.map((r:any)=>({...r,image_url:r.listing_images?.slice().sort((a:any,b:any)=>(a.sort_order??0)-(b.sort_order??0))?.[0]?.image_url}))) }catch{}})()},[])
 const ru=lang==='ru'
 const search=(e:FormEvent)=>{e.preventDefault();setSearched(true)}
 const filtered=listings.filter(x=>!city||`${x.city} ${x.district||''}`.toLowerCase().includes(city.toLowerCase())).filter(x=>x.accommodation_type==='hotel'||x.property_type==='apartment'||x.property_type==='house')
 return <main className="min-h-screen bg-[#f3f5f7] text-slate-900">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-[1180px] items-center justify-between px-4"><Link href="/" className="text-2xl font-black">Pro<span className="text-emerald-500">house</span></Link><div className="flex items-center gap-2"><button onClick={()=>{const n=lang==='uz'?'ru':'uz';setLang(n);localStorage.setItem('prohouse-lang',n)}} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">{lang==='uz'?'O‘z / Ru':'Ru / O‘z'}</button><Link href="/daily/new" className="rounded-xl bg-emerald-600 px-4 py-2.5 text-xs font-black text-white">{ru?'Разместить отель':'Mehmonxona e’loni joylashtirish'}</Link></div></div></header>
  <section className="mx-auto max-w-[1180px] px-4 pb-8 pt-10"><div className="grid gap-8 md:grid-cols-[1.05fr_.95fr] md:items-center"><div><p className="text-xs font-black tracking-[.18em] text-emerald-600">{ru?'ПОСУТОЧНАЯ АРЕНДА':'KUNLIK IJARA'}</p><h1 className="mt-3 text-4xl font-black leading-tight sm:text-5xl">{ru?'Найдём, где остановиться':'Qayerda qolishingizni birga topamiz'}</h1><p className="mt-4 max-w-xl text-base leading-7 text-slate-500">{ru?'Квартиры, апартаменты, коттеджи, дома и отели — выбирайте место, даты и количество гостей.':'Kvartira, apartament, kottej, uy va mehmonxonalar — joylashuv, sana va mehmonlar sonini kiriting.'}</p></div><div className="h-48 rounded-3xl bg-[url('https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=85')] bg-cover bg-center"/></div>
   <form onSubmit={search} className="mt-8 rounded-3xl bg-white p-4 shadow-xl"><div className="grid gap-2 lg:grid-cols-[1.2fr_1fr_1fr_.7fr_auto]"><label className="rounded-xl bg-slate-50 p-3"><small className="block text-[10px] text-slate-400">{ru?'Город или место':'Shahar yoki joy'}</small><input value={city} onChange={e=>setCity(e.target.value)} placeholder={ru?'Город или населённый пункт':'Shahar yoki aholi punkti'} className="mt-1 w-full bg-transparent text-sm font-bold outline-none" /></label><label className="rounded-xl bg-slate-50 p-3"><small className="block text-[10px] text-slate-400">{ru?'Заезд':'Kelish'}</small><input type="date" value={checkIn} onChange={e=>setCheckIn(e.target.value)} className="mt-1 w-full bg-transparent text-sm font-bold outline-none" required /></label><label className="rounded-xl bg-slate-50 p-3"><small className="block text-[10px] text-slate-400">{ru?'Выезд':'Ketish'}</small><input type="date" value={checkOut} min={checkIn||undefined} onChange={e=>setCheckOut(e.target.value)} className="mt-1 w-full bg-transparent text-sm font-bold outline-none" required /></label><label className="rounded-xl bg-slate-50 p-3"><small className="block text-[10px] text-slate-400">{ru?'Гости':'Mehmonlar'}</small><select value={guests} onChange={e=>setGuests(e.target.value)} className="mt-1 w-full bg-transparent text-sm font-bold outline-none">{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{i+1} {ru?'гость':'kishi'}</option>)}</select></label><button className="rounded-xl bg-emerald-600 px-7 py-3 text-sm font-black text-white">⌕ {ru?'Найти':'Qidirish'}</button></div><div className="mt-3 flex flex-wrap gap-3 text-xs font-semibold text-slate-500"><span>📍 Toshkent</span><span>📍 Samarqand</span><span>📍 Buxoro</span><span>📍 Xiva</span></div></form>
  </section>
  <section className="mx-auto max-w-[1180px] px-4 pb-12"><div className="grid gap-8 md:grid-cols-[1.35fr_.65fr]"><div><div className="mb-5 flex items-end justify-between"><div><h2 className="text-2xl font-black">{ru?'Варианты размещения':'Qolish variantlari'}</h2><p className="mt-1 text-sm text-slate-500">{searched?(ru?'Результаты по вашему запросу':'So‘rovingiz bo‘yicha natijalar'):(ru?'Отели и жильё на сутки':'Mehmonxona va kunlik uy-joylar')}</p></div></div><div className="grid gap-5 sm:grid-cols-2">{filtered.map(x=><Link key={x.id} href={`/listings/${x.id}`} className="overflow-hidden rounded-2xl bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-48 bg-slate-100 bg-cover bg-center" style={{backgroundImage:`url(${x.image_url||fallback[0].image_url})`}}/><div className="p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-black">{ru?(x.title_ru||x.title):x.title}</h3><span className="shrink-0 rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-black text-emerald-700">{x.accommodation_type==='hotel'?(ru?'Отель':'Mehmonxona'):(ru?'Жильё':'Uy-joy')}</span></div><p className="mt-2 text-xs text-slate-500">📍 {x.city}{x.district?`, ${x.district}`:''}</p><p className="mt-3 text-lg font-black text-emerald-600">{money(x.price,x.currency)} <span className="text-xs font-semibold text-slate-400">/ {ru?'сутки':'kun'}</span></p></div></Link>)}</div></div>
   <aside className="rounded-3xl bg-white p-6 shadow-sm"><h3 className="text-xl font-black">{ru?'Безопасная аренда с Prohouse':'Prohouse bilan xavfsiz ijara'}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{ru?'Проверяйте данные объекта, условия оплаты и связывайтесь с владельцем через Prohouse.':'E’lon ma’lumotlarini tekshiring, to‘lov shartlarini ko‘ring va mulk egasi bilan Prohouse orqali bog‘laning.'}</p><div className="mt-5 grid gap-3"><div className="rounded-2xl bg-slate-50 p-4"><b>✓ {ru?'Проверенные объявления':'Tekshirilgan e’lonlar'}</b><p className="mt-1 text-xs text-slate-500">{ru?'Проверяем важные данные объекта.':'Mulk haqidagi muhim ma’lumotlarni tekshirishga yordam beramiz.'}</p></div><div className="rounded-2xl bg-slate-50 p-4"><b>🛡️ {ru?'Поддержка':'Qo‘llab-quvvatlash'}</b><p className="mt-1 text-xs text-slate-500">{ru?'Поддержка на этапах аренды.':'Ijara jarayonida qo‘llab-quvvatlash.'}</p></div></div></aside></div></section>
 </main>
}
