'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/utils/supabase/client'

type Lang='uz'|'ru'
type Listing={id:string;title:string;listing_type:string;property_type:string;price:number;currency:string;area_m2:number|null;rooms:number|null;floor:number|null;floors_total:number|null;district:string|null;city:string;seller_type:string;seller_name:string|null;is_mortgage_available:boolean;is_verified:boolean;is_featured:boolean;published_at:string|null;image_url?:string}

type Filters={tab:string;query:string;district:string;propertyType:string;currency:string;min:string;max:string;rooms:string;owner:boolean;mortgage:boolean;verified:boolean;featured:boolean;sort:string}

const ru:Record<string,string>={'2 xonali zamonaviy kvartira':'Современная 2-комнатная квартира','Yangi qurilgan premium uy':'Новый дом премиум-класса','3 xonali yorug‘ kvartira':'Светлая 3-комнатная квартира','Keng hovlili xususiy uy':'Просторный частный дом с двором','Hovlili uy, tayyor holatda':'Готовый дом с двором','2 xonali kvartira':'2-комнатная квартира','Tijorat uchun qulay bino':'Коммерческое помещение'}
const demo:Listing[]=[
{id:'1',title:'2 xonali zamonaviy kvartira',listing_type:'sale',property_type:'apartment',price:860000000,currency:'UZS',area_m2:58,rooms:2,floor:5,floors_total:9,district:'Yunusobod',city:'Toshkent',seller_type:'owner',seller_name:'Sotuvchi',is_mortgage_available:true,is_verified:true,is_featured:true,published_at:null,image_url:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85'},
{id:'2',title:'Yangi qurilgan premium uy',listing_type:'sale',property_type:'new_building',price:1240000000,currency:'UZS',area_m2:120,rooms:4,floor:2,floors_total:2,district:'Mirzo Ulug‘bek',city:'Toshkent',seller_type:'developer',seller_name:'Rieltor',is_mortgage_available:true,is_verified:true,is_featured:true,published_at:null,image_url:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85'},
{id:'3',title:'3 xonali yorug‘ kvartira',listing_type:'sale',property_type:'apartment',price:950000000,currency:'UZS',area_m2:72,rooms:3,floor:7,floors_total:12,district:'Chilonzor',city:'Toshkent',seller_type:'owner',seller_name:'Sotuvchi',is_mortgage_available:true,is_verified:true,is_featured:true,published_at:null,image_url:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85'},
{id:'4',title:'Keng hovlili xususiy uy',listing_type:'sale',property_type:'house',price:185000,currency:'USD',area_m2:190,rooms:5,floor:2,floors_total:2,district:'Mirzo Ulug‘bek',city:'Toshkent',seller_type:'owner',seller_name:'Sotuvchi',is_mortgage_available:false,is_verified:true,is_featured:false,published_at:null,image_url:'https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1000&q=85'},
{id:'5',title:'Hovlili uy, tayyor holatda',listing_type:'sale',property_type:'house',price:149000,currency:'USD',area_m2:200,rooms:5,floor:2,floors_total:2,district:'Sergeli',city:'Toshkent',seller_type:'realtor',seller_name:'Rieltor',is_mortgage_available:false,is_verified:true,is_featured:false,published_at:null,image_url:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85'},
{id:'6',title:'2 xonali kvartira',listing_type:'sale',property_type:'apartment',price:90000,currency:'USD',area_m2:64,rooms:2,floor:4,floors_total:9,district:'Yakkasaroy',city:'Toshkent',seller_type:'owner',seller_name:'Sotuvchi',is_mortgage_available:false,is_verified:true,is_featured:false,published_at:null,image_url:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=85'},
{id:'7',title:'Tijorat uchun qulay bino',listing_type:'sale',property_type:'commercial',price:135000,currency:'USD',area_m2:123,rooms:null,floor:1,floors_total:1,district:'Chilonzor',city:'Toshkent',seller_type:'realtor',seller_name:'Rieltor',is_mortgage_available:false,is_verified:true,is_featured:false,published_at:null,image_url:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1000&q=85'}]

const text={uz:{sale:'Sotuv',rent:'Ijara',daily:'Kunlik',new:'Yangi uylar',all:'Barchasi',property:'Ko‘chmas mulk',home:'Bosh sahifa',search:'Qidirish',placeholder:'Manzil, tuman yoki e’lon nomi',filters:'Filtrlar',reset:'Tozalash',district:'Tuman',districts:'Barcha tumanlar',type:'Mulk turi',types:'Barcha turlar',apartment:'Kvartira',house:'Xususiy uy',land:'Yer uchastkasi',commercial:'Tijorat',newBuilding:'Yangi bino',price:'Narx',min:'dan',max:'gacha',currency:'Valyuta',rooms:'Xonalar',any:'Istalgan',owner:'Egasi',mortgage:'Ipotekaga mumkin',verified:'Tasdiqlangan',top:'TOP e’lonlar',sort:'Saralash',newest:'Yangi qo‘shilganlar',low:'Arzonidan',high:'Qimmatidan',area:'Maydoni katta',grid:'Setka',list:'Ro‘yxat',no:'E’lon topilmadi',noText:'Filtrlarni kengaytirib yoki tozalab qayta urinib ko‘ring.',apply:'Qo‘llash',login:'Kirish',post:'E’lon joylashtirish',found:'ta e’lon',clear:'Tozalash'},ru:{sale:'Продажа',rent:'Аренда',daily:'Посуточно',new:'Новостройки',all:'Все',property:'Недвижимость',home:'Главная',search:'Найти',placeholder:'Адрес, район или название объявления',filters:'Фильтры',reset:'Сбросить',district:'Район',districts:'Все районы',type:'Тип недвижимости',types:'Все типы',apartment:'Квартира',house:'Частный дом',land:'Земля',commercial:'Коммерция',newBuilding:'Новостройка',price:'Цена',min:'от',max:'до',currency:'Валюта',rooms:'Комнаты',any:'Любое',owner:'От владельца',mortgage:'Ипотека доступна',verified:'Проверенные',top:'TOP объявления',sort:'Сортировка',newest:'Новые',low:'Сначала дешевле',high:'Сначала дороже',area:'Большая площадь',grid:'Сетка',list:'Список',no:'Объявления не найдены',noText:'Расширьте или сбросьте фильтры и попробуйте снова.',apply:'Применить',login:'Войти',post:'Разместить объявление',found:'объявлений',clear:'Сбросить'}}

const money=(n:number,c:string)=>new Intl.NumberFormat('ru-RU').format(n)+(c==='USD'?' у.е.':' сўм')

export default function PropertiesPage(){
 const [lang,setLang]=useState<Lang>('uz'),[rows,setRows]=useState<Listing[]>(demo),[loading,setLoading]=useState(true),[total,setTotal]=useState(7),[page,setPage]=useState(1),[view,setView]=useState<'grid'|'list'>('grid')
 const [f,setF]=useState<Filters>({tab:'sale',query:'',district:'',propertyType:'',currency:'',min:'',max:'',rooms:'',owner:false,mortgage:false,verified:false,featured:false,sort:'newest'})
 const T=text[lang],perPage=9
 useEffect(()=>{const saved=localStorage.getItem('prohouse-lang') as Lang|null;if(saved)setLang(saved)},[])
 const update=(patch:Partial<Filters>)=>{setF(x=>({...x,...patch}));setPage(1)}
 const clear=()=>{setF({tab:'sale',query:'',district:'',propertyType:'',currency:'',min:'',max:'',rooms:'',owner:false,mortgage:false,verified:false,featured:false,sort:'newest'});setPage(1)}
 useEffect(()=>{let dead=false;const load=async()=>{setLoading(true);try{const s=createClient();let q:any=s.from('listings').select('*, listing_images(image_url,sort_order)',{count:'exact'}).eq('status','active');if(f.tab!=='all')q=q.eq('listing_type',f.tab);if(f.tab==='new_building')q=q.eq('property_type','new_building');if(f.district)q=q.eq('district',f.district);if(f.propertyType)q=q.eq('property_type',f.propertyType);if(f.currency)q=q.eq('currency',f.currency);if(f.min)q=q.gte('price',Number(f.min.replace(/\D/g,'')));if(f.max)q=q.lte('price',Number(f.max.replace(/\D/g,'')));if(f.rooms)q=f.rooms==='5+'?q.gte('rooms',5):q.eq('rooms',Number(f.rooms));if(f.owner)q=q.eq('seller_type','owner');if(f.mortgage)q=q.eq('is_mortgage_available',true);if(f.verified)q=q.eq('is_verified',true);if(f.featured)q=q.eq('is_featured',true);if(f.query.trim()){const x=f.query.trim().replace(/,/g,' ');q=q.or(`title.ilike.%${x}%,district.ilike.%${x}%,city.ilike.%${x}%`)}if(f.sort==='price_asc')q=q.order('price',{ascending:true});else if(f.sort==='price_desc')q=q.order('price',{ascending:false});else if(f.sort==='area_desc')q=q.order('area_m2',{ascending:false});else q=q.order('is_featured',{ascending:false}).order('published_at',{ascending:false});const {data,count,error}=await q.range((page-1)*perPage,page*perPage-1);if(error)throw error;if(dead)return;setTotal(count||0);setRows((data||[]).map((r:any)=>({...r,image_url:r.listing_images?.sort((a:any,b:any)=>a.sort_order-b.sort_order)?.[0]?.image_url}))) }catch{if(dead)return;let r=demo.filter(x=>f.tab==='all'||x.listing_type===f.tab);if(f.tab==='new_building')r=r.filter(x=>x.property_type==='new_building');if(f.district)r=r.filter(x=>x.district===f.district);if(f.propertyType)r=r.filter(x=>x.property_type===f.propertyType);if(f.currency)r=r.filter(x=>x.currency===f.currency);if(f.min)r=r.filter(x=>x.price>=Number(f.min.replace(/\D/g,'')));if(f.max)r=r.filter(x=>x.price<=Number(f.max.replace(/\D/g,'')));if(f.rooms)r=r.filter(x=>f.rooms==='5+'?(x.rooms||0)>=5:x.rooms===Number(f.rooms));if(f.owner)r=r.filter(x=>x.seller_type==='owner');if(f.mortgage)r=r.filter(x=>x.is_mortgage_available);if(f.verified)r=r.filter(x=>x.is_verified);if(f.featured)r=r.filter(x=>x.is_featured);if(f.query)r=r.filter(x=>`${x.title} ${x.city} ${x.district}`.toLowerCase().includes(f.query.toLowerCase()));if(f.sort==='price_asc')r.sort((a,b)=>a.price-b.price);if(f.sort==='price_desc')r.sort((a,b)=>b.price-a.price);if(f.sort==='area_desc')r.sort((a,b)=>(b.area_m2||0)-(a.area_m2||0));setTotal(r.length);setRows(r.slice((page-1)*perPage,page*perPage))}finally{if(!dead)setLoading(false)}};load();return()=>{dead=true}},[f,page])
 const districts=Array.from(new Set([...demo,...rows].map(x=>x.district).filter(Boolean) as string[])),pages=Math.max(1,Math.ceil(total/perPage))
 return <main className="catalog-page"><header className="header"><div className="container nav"><a className="brand" href="/"><span className="brand-mark">⌂</span><span>Pro<span>house</span></span></a><nav className="main-nav"><a className="active" href="/properties">{T.sale}</a><a href="#">{T.rent}</a><a href="#">{T.new}</a><a href="#">{lang==='uz'?'Ipoteka':'Ипотека'}</a><a href="#">{lang==='uz'?'Xizmatlar':'Услуги'}</a></nav><div className="nav-actions"><button className="language-btn" onClick={()=>{const n=lang==='uz'?'ru':'uz';setLang(n);localStorage.setItem('prohouse-lang',n)}}>{lang==='uz'?'O‘z/Ru':'Ru/O‘z'}</button><span className="location-pill">⌖ Toshkent</span><button className="round-btn">♡</button><button className="account-btn">{T.login}</button></div></div></header>
 <section className="catalog-top"><div className="container"><div className="breadcrumbs"><a href="/">{T.home}</a><span>›</span><b>{T.property}</b></div><div className="catalog-title"><div><span className="hero-kicker">PROHOUSE MARKETPLACE</span><h1>{T.property}</h1><p>{lang==='uz'?'O‘zbekiston bo‘ylab uy, kvartira va boshqa ko‘chmas mulklarni toping.':'Найдите квартиры, дома и другую недвижимость по всему Узбекистану.'}</p></div><a className="post-outline" href="#">+ {T.post}</a></div><div className="catalog-search"><input value={f.query} onChange={e=>update({query:e.target.value})} placeholder={T.placeholder}/><button>{T.search}</button></div><div className="catalog-tabs">{[['sale',T.sale],['rent',T.rent],['daily',T.daily],['new_building',T.new],['all',T.all]].map(([id,label])=><button key={id} className={f.tab===id?'active':''} onClick={()=>update(id==='new_building'?{tab:id,propertyType:'new_building'}:{tab:id,propertyType:f.propertyType==='new_building'?'':f.propertyType})}>{label}</button>)}</div></div></section>
 <section className="container catalog-body"><aside className="filter-panel"><div className="filter-head"><div><b>{T.filters}</b><span>{new Intl.NumberFormat('ru-RU').format(total)} {T.found}</span></div><button onClick={clear}>{T.reset}</button></div><label className="filter-field"><span>{T.district}</span><select value={f.district} onChange={e=>update({district:e.target.value})}><option value="">{T.districts}</option>{districts.map(d=><option key={d}>{d}</option>)}</select></label><label className="filter-field"><span>{T.type}</span><select value={f.propertyType} onChange={e=>update({propertyType:e.target.value})}><option value="">{T.types}</option><option value="apartment">{T.apartment}</option><option value="house">{T.house}</option><option value="land">{T.land}</option><option value="commercial">{T.commercial}</option><option value="new_building">{T.newBuilding}</option></select></label><div className="filter-block"><span>{T.price}</span><div className="price-inputs"><input value={f.min} onChange={e=>update({min:e.target.value})} placeholder={T.min}/><input value={f.max} onChange={e=>update({max:e.target.value})} placeholder={T.max}/></div><select className="currency-select" value={f.currency} onChange={e=>update({currency:e.target.value})}><option value="">{T.currency}: —</option><option value="UZS">so‘m</option><option value="USD">USD</option></select></div><label className="filter-field"><span>{T.rooms}</span><select value={f.rooms} onChange={e=>update({rooms:e.target.value})}><option value="">{T.any}</option>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}<option>5+</option></select></label><div className="check-list"><label><input type="checkbox" checked={f.owner} onChange={e=>update({owner:e.target.checked})}/><span>{T.owner}</span></label><label><input type="checkbox" checked={f.mortgage} onChange={e=>update({mortgage:e.target.checked})}/><span>{T.mortgage}</span></label><label><input type="checkbox" checked={f.verified} onChange={e=>update({verified:e.target.checked})}/><span>{T.verified}</span></label><label><input type="checkbox" checked={f.featured} onChange={e=>update({featured:e.target.checked})}/><span>{T.top}</span></label></div><button className="filter-apply" onClick={()=>setPage(1)}>{T.apply}</button></aside>
 <div className="results-area"><div className="results-head"><div><h2>{loading?'…':new Intl.NumberFormat('ru-RU').format(total)} <span>{T.found}</span></h2><p>Toshkent · {f.tab==='sale'?T.sale:f.tab==='rent'?T.rent:f.tab==='daily'?T.daily:f.tab==='new_building'?T.new:T.all}</p></div><div className="result-actions"><select value={f.sort} onChange={e=>update({sort:e.target.value})}><option value="newest">{T.newest}</option><option value="price_asc">{T.low}</option><option value="price_desc">{T.high}</option><option value="area_desc">{T.area}</option></select><div className="view-toggle"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')}>▦</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}>☷</button></div></div></div>{loading?<div className="loading-grid">{Array.from({length:6}).map((_,i)=><div className="skeleton-card" key={i}/>)}</div>:rows.length?<div className={`catalog-grid ${view==='list'?'list-view':''}`}>{rows.map(p=><article className="catalog-card" key={p.id}><a className="catalog-image" href={`/properties/${p.id}`} style={{backgroundImage:`url(${p.image_url})`}}><span className={`catalog-badge ${p.is_featured?'vip':''}`}>{p.is_featured?'TOP':p.is_verified?'✓ '+T.verified:T.new}</span><button className="catalog-heart" onClick={e=>e.preventDefault()}>♡</button></a><div className="catalog-card-body"><div className="catalog-price">{money(p.price,p.currency)}</div><h3>{lang==='ru'?(ru[p.title]||p.title):p.title}</h3><div className="catalog-location">⌖ {p.city}{p.district?`, ${p.district}`:''}</div><div className="catalog-meta"><span>{p.area_m2?`${p.area_m2} m²`:'—'}</span><span>{p.rooms?`${p.rooms} xona`:''}</span><span>{p.floor&&p.floors_total?`${p.floor}/${p.floors_total}`:''}</span></div><div className="catalog-seller"><span className="verified-dot">●</span>{p.seller_name||T.owner}</div></div></article>)}</div>:<div className="empty-state"><div>⌂</div><h3>{T.no}</h3><p>{T.noText}</p><button onClick={clear}>{T.clear}</button></div>}<div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>{lang==='uz'?'← Oldingi':'← Назад'}</button><div>{Array.from({length:Math.min(pages,5)},(_,i)=><button key={i} className={page===i+1?'active':''} onClick={()=>setPage(i+1)}>{i+1}</button>)}</div><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>{lang==='uz'?'Keyingi →':'Далее →'}</button></div></div></section>
 </main>
}
