'use client'

import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/utils/supabase/client'

type Lang = 'uz' | 'ru'
type View = 'grid' | 'list'
type Sort = 'newest' | 'price_asc' | 'price_desc' | 'area_desc'

type Listing = {
  id:string; title:string; listing_type:string; property_type:string; price:number; currency:string
  area_m2:number|null; rooms:number|null; floor:number|null; floors_total:number|null
  district:string|null; city:string; seller_type:string; seller_name:string|null
  is_mortgage_available:boolean; is_verified:boolean; is_featured:boolean; published_at:string|null; image_url?:string
}

const fallback:Listing[]=[
 {id:'1',title:'2 xonali zamonaviy kvartira',listing_type:'sale',property_type:'apartment',price:860000000,currency:'UZS',area_m2:58,rooms:2,floor:5,floors_total:9,district:'Yunusobod',city:'Toshkent',seller_type:'owner',seller_name:'Sotuvchi',is_mortgage_available:true,is_verified:true,is_featured:true,published_at:null,image_url:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85'},
 {id:'2',title:'Yangi qurilgan premium uy',listing_type:'sale',property_type:'new_building',price:1240000000,currency:'UZS',area_m2:120,rooms:4,floor:2,floors_total:2,district:'Mirzo Ulug‘bek',city:'Toshkent',seller_type:'developer',seller_name:'Rieltor',is_mortgage_available:true,is_verified:true,is_featured:true,published_at:null,image_url:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85'},
 {id:'3',title:'3 xonali yorug‘ kvartira',listing_type:'sale',property_type:'apartment',price:950000000,currency:'UZS',area_m2:72,rooms:3,floor:7,floors_total:12,district:'Chilonzor',city:'Toshkent',seller_type:'owner',seller_name:'Sotuvchi',is_mortgage_available:true,is_verified:true,is_featured:true,published_at:null,image_url:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85'},
 {id:'4',title:'Keng hovlili xususiy uy',listing_type:'sale',property_type:'house',price:185000,currency:'USD',area_m2:190,rooms:5,floor:2,floors_total:2,district:'Mirzo Ulug‘bek',city:'Toshkent',seller_type:'owner',seller_name:'Sotuvchi',is_mortgage_available:false,is_verified:true,is_featured:false,published_at:null,image_url:'https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1000&q=85'},
 {id:'5',title:'Hovlili uy, tayyor holatda',listing_type:'sale',property_type:'house',price:149000,currency:'USD',area_m2:200,rooms:5,floor:2,floors_total:2,district:'Sergeli',city:'Toshkent',seller_type:'realtor',seller_name:'Rieltor',is_mortgage_available:false,is_verified:true,is_featured:false,published_at:null,image_url:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85'},
 {id:'6',title:'2 xonali kvartira',listing_type:'sale',property_type:'apartment',price:90000,currency:'USD',area_m2:64,rooms:2,floor:4,floors_total:9,district:'Yakkasaroy',city:'Toshkent',seller_type:'owner',seller_name:'Sotuvchi',is_mortgage_available:false,is_verified:true,is_featured:false,published_at:null,image_url:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=85'},
 {id:'7',title:'Tijorat uchun qulay bino',listing_type:'sale',property_type:'commercial',price:135000,currency:'USD',area_m2:123,rooms:null,floor:1,floors_total:1,district:'Chilonzor',city:'Toshkent',seller_type:'realtor',seller_name:'Rieltor',is_mortgage_available:false,is_verified:true,is_featured:false,published_at:null,image_url:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1000&q=85'}
]

const ruTitles:Record<string,string>={
 '2 xonali zamonaviy kvartira':'Современная 2-комнатная квартира','Yangi qurilgan premium uy':'Новый дом премиум-класса','3 xonali yorug‘ kvartira':'Светлая 3-комнатная квартира','Keng hovlili xususiy uy':'Просторный частный дом с двором','Hovlili uy, tayyor holatda':'Готовый дом с двором','2 xonali kvartira':'2-комнатная квартира','Tijorat uchun qulay bino':'Коммерческое помещение'
}

const c={
 uz:{sale:'Sotuv',rent:'Ijara',daily:'Kunlik',new:'Yangi uylar',search:'Qidirish',placeholder:'Manzil, tuman yoki e’lon nomi',filters:'Filtrlar',reset:'Tozalash',found:'ta e’lon',district:'Tuman',allDistricts:'Barcha tumanlar',type:'Mulk turi',allTypes:'Barcha turlar',price:'Narx',min:'dan',max:'gacha',currency:'Valyuta',rooms:'Xonalar',any:'Istalgan',owner:'Egasi',mortgage:'Ipotekaga mumkin',verified:'Tasdiqlangan',top:'TOP e’lonlar',sort:'Saralash',newest:'Yangi qo‘shilganlar',low:'Arzonidan',high:'Qimmatidan',area:'Maydoni katta',apartment:'Kvartira',house:'Xususiy uy',land:'Yer uchastkasi',commercial:'Tijorat',newBuilding:'Yangi bino',all:'Barchasi',apply:'Qo‘llash',no:'E’lon topilmadi',noText:'Filtrlarni kengaytirib yoki tozalab qayta urinib ko‘ring.',clear:'Filtrlarni tozalash',home:'Bosh sahifa',login:'Kirish',post:'E’lon joylashtirish',property:'Ko‘chmas mulk',back:'← Oldingi',next:'Keyingi →',map:'Xarita'},
 ru:{sale:'Продажа',rent:'Аренда',daily:'Посуточно',new:'Новостройки',search:'Найти',placeholder:'Адрес, район или название объявления',filters:'Фильтры',reset:'Сбросить',found:'объявлений',district:'Район',allDistricts:'Все районы',type:'Тип недвижимости',allTypes:'Все типы',price:'Цена',min:'от',max:'до',currency:'Валюта',rooms:'Комнаты',any:'Любое',owner:'От владельца',mortgage:'Ипотека доступна',verified:'Проверенные',top:'TOP объявления',sort:'Сортировка',newest:'Новые',low:'Сначала дешевле',high:'Сначала дороже',area:'Большая площадь',apartment:'Квартира',house:'Частный дом',land:'Земля',commercial:'Коммерция',newBuilding:'Новостройка',all:'Все',apply:'Применить',no:'Объявления не найдены',noText:'Расширьте или сбросьте фильтры и попробуйте снова.',clear:'Сбросить фильтры',home:'Главная',login:'Войти',post:'Разместить объявление',property:'Недвижимость',back:'← Назад',next:'Далее →',map:'Карта'}
}

const money=(n:number,cur:string)=>new Intl.NumberFormat('ru-RU').format(n)+(cur==='USD'?' у.е.':' сўм')

export default function PropertiesPage(){
 const [lang,setLang]=useState<Lang>('uz'),[rows,setRows]=useState<Listing[]>(fallback),[loading,setLoading]=useState(true),[total,setTotal]=useState(7)
 const [tab,setTab]=useState('sale'),[query,setQuery]=useState(''),[district,setDistrict]=useState(''),[type,setType]=useState(''),[currency,setCurrency]=useState(''),[min,setMin]=useState(''),[max,setMax]=useState(''),[rooms,setRooms]=useState('')
 const [owner,setOwner]=useState(false),[mortgage,setMortgage]=useState(false),[verified,setVerified]=useState(false),[featured,setFeatured]=useState(false),[sort,setSort]=useState<Sort>('newest'),[page,setPage]=useState(1),[view,setView]=useState<View>('grid')
 const perPage=9,text=c[lang]
 useEffect(()=>{const saved=localStorage.getItem('prohouse-lang') as Lang|null;if(saved==='uz'||saved==='ru')setLang(saved)},[])
 const districts=useMemo(()=>Array.from(new Set([...fallback,...rows].map(x=>x.district).filter(Boolean) as string[])).sort(),[rows])
 useEffect(()=>{let dead=false;const load=async()=>{setLoading(true);try{const s=createClient();let q:any=s.from('listings').select('*, listing_images(image_url,sort_order)',{count:'exact'}).eq('status','active')
   if(tab!=='all')q=q.eq('listing_type',tab);if(tab==='new_building')q=q.eq('property_type','new_building');if(district)q=q.eq('district',district);if(type)q=q.eq('property_type',type);if(currency)q=q.eq('currency',currency)
   if(min)q=q.gte('price',Number(min.replace(/\D/g,'')));if(max)q=q.lte('price',Number(max.replace(/\D/g,'')));if(rooms)q=rooms==='5+'?q.gte('rooms',5):q.eq('rooms',Number(rooms));if(owner)q=q.eq('seller_type','owner');if(mortgage)q=q.eq('is_mortgage_available',true);if(verified)q=q.eq('is_verified',true);if(featured)q=q.eq('is_featured',true)
   if(query.trim()){const safe=query.trim().replace(/,/g,' ');q=q.or(`title.ilike.%${safe}%,district.ilike.%${safe}%,city.ilike.%${safe}%`)}
   if(sort==='price_asc')q=q.order('price',{ascending:true});else if(sort==='price_desc')q=q.order('price',{ascending:false});else if(sort==='area_desc')q=q.order('area_m2',{ascending:false});else q=q.order('is_featured',{ascending:false}).order('published_at',{ascending:false})
   const from=(page-1)*perPage,{data,count,error}=await q.range(from,from+perPage-1);if(error)throw error;if(dead)return;setTotal(count||0);setRows((data||[]).map((r:any)=>({...r,image_url:r.listing_images?.sort((a:any,b:any)=>a.sort_order-b.sort_order)?.[0]?.image_url})))
  }catch{if(dead)return;let r=fallback.filter(x=>tab==='all'||x.listing_type===tab);if(tab==='new_building')r=r.filter(x=>x.property_type==='new_building');if(district)r=r.filter(x=>x.district===district);if(type)r=r.filter(x=>x.property_type===type);if(currency)r=r.filter(x=>x.currency===currency);if(min)r=r.filter(x=>x.price>=Number(min.replace(/\D/g,'')));if(max)r=r.filter(x=>x.price<=Number(max.replace(/\D/g,'')));if(rooms)r=r.filter(x=>rooms==='5+'?(x.rooms||0)>=5:x.rooms===Number(rooms));if(owner)r=r.filter(x=>x.seller_type==='owner');if(mortgage)r=r.filter(x=>x.is_mortgage_available);if(verified)r=r.filter(x=>x.is_verified);if(featured)r=r.filter(x=>x.is_featured);if(query.trim())r=r.filter(x=>`${x.title} ${x.city} ${x.district}`.toLowerCase().includes(query.toLowerCase()));if(sort==='price_asc')r.sort((a,b)=>a.price-b.price);if(sort==='price_desc')r.sort((a,b)=>b.price-a.price);if(sort==='area_desc')r.sort((a,b)=>(b.area_m2||0)-(a.area_m2||0));setTotal(r.length);setRows(r.slice((page-1)*perPage,page*perPage))}finally{if(!dead)setLoading(false)}};load();return()=>{dead=true}},[tab,query,district,type,currency,min,max,rooms,owner,mortgage,verified,featured,sort,page])
 useEffect(()=>setPage(1),[tab,query,district,type,currency,min,max,rooms,owner,mortgage,verified,featured,sort])
 const langSet=(x:Lang)=>{setLang(x);localStorage.setItem('prohouse-lang',x)},clear=()=>{setQuery('');setDistrict('');setType('');setCurrency('');setMin('');setMax('');setRooms('');setOwner(false);setMortgage(false);setVerified(false);setFeatured(false);setSort('newest');setTab('sale');setPage(1)},pages=Math.max(1,Math.ceil(total/perPage))
 const tabSet=(x:string)=>{if(x==='new_building'){setTab('new_building');setType('new_building')}else{setTab(x);if(type==='new_building')setType('')}}
 return <main className="catalog-page">
  <header className="header"><div className="container nav"><a className="brand" href="/"><span className="brand-mark">⌂</span><span>Pro<span>house</span></span></a><nav className="main-nav"><a className="active" href="/properties">{text.sale}</a><a href="#">{text.rent}</a><a href="#">{text.new}</a><a href="#">{lang==='uz'?'Ipoteka':'Ипотека'}</a><a href="#">{lang==='uz'?'Xizmatlar':'Услуги'}</a></nav><div className="nav-actions"><button className="language-btn" onClick={()=>langSet(lang==='uz'?'ru':'uz')}>{lang==='uz'?'O‘z/Ru':'Ru/O‘z'}</button><span className="location-pill">⌖ Toshkent</span><button className="round-btn">♡</button><button className="account-btn">{text.login}</button></div></div></header>
  <section className="catalog-top"><div className="container"><div className="breadcrumbs"><a href="/">{text.home}</a><span>›</span><b>{text.property}</b></div><div className="catalog-title"><div><span className="hero-kicker">PROHOUSE MARKETPLACE</span><h1>{text.property}</h1><p>{lang==='uz'?'O‘zbekiston bo‘ylab uy, kvartira va boshqa ko‘chmas mulklarni toping.':'Найдите квартиры, дома и другую недвижимость по всему Узбекистану.'}</p></div><a className="post-outline" href="#">+ {text.post}</a></div><div className="catalog-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={text.placeholder}/><button onClick={()=>setPage(1)}>⌕ {text.search}</button></div><div className="catalog-tabs">{[['sale',text.sale],['rent',text.rent],['daily',text.daily],['new_building',text.new],['all',text.all]].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>tabSet(id)}>{label}</button>)}</div></div></section>
  <section className="container catalog-body"><aside className="filter-panel"><div className="filter-head"><div><b>{text.filters}</b><span>{new Intl.NumberFormat('ru-RU').format(total)} {text.found}</span></div><button onClick={clear}>{text.reset}</button></div><label className="filter-field"><span>{text.district}</span><select value={district} onChange={e=>setDistrict(e.target.value)}><option value="">{text.allDistricts}</option>{districts.map(d=><option key={d}>{d}</option>)}</select></label><label className="filter-field"><span>{text.type}</span><select value={type} onChange={e=>setType(e.target.value)}><option value="">{text.allTypes}</option><option value="apartment">{text.apartment}</option><option value="house">{text.house}</option><option value="land">{text.land}</option><option value="commercial">{text.commercial}</option><option value="new_building">{text.newBuilding}</option></select></label><div className="filter-block"><span>{text.price}</span><div className="price-inputs"><input value={min} onChange={e=>setMin(e.target.value)} placeholder={text.min}/><input value={max} onChange={e=>setMax(e.target.value)} placeholder={text.max}/></div><select className="currency-select" value={currency} onChange={e=>setCurrency(e.target.value)}><option value="">{text.currency}: —</option><option value="UZS">so‘m</option><option value="USD">USD</option></select></div><label className="filter-field"><span>{text.rooms}</span><select value={rooms} onChange={e=>setRooms(e.target.value)}><option value="">{text.any}</option>{[1,2,3,4].map(n=><option key={n} value={n}>{n}</option>)}<option value="5+">5+</option></select></label><div className="check-list"><label><input type="checkbox" checked={owner} onChange={e=>setOwner(e.target.checked)}/><span>{text.owner}</span></label><label><input type="checkbox" checked={mortgage} onChange={e=>setMortgage(e.target.checked)}/><span>{text.mortgage}</span></label><label><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/><span>{text.verified}</span></label><label><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)}/><span>{text.top}</span></label></div><button className="filter-apply" onClick={()=>setPage(1)}>{text.apply}</button></aside>
   <div className="results-area"><div className="results-head"><div><h2>{loading?'…':new Intl.NumberFormat('ru-RU').format(total)} <span>{text.found}</span></h2><p>Toshkent · {tab==='sale'?text.sale:tab==='rent'?text.rent:tab==='daily'?text.daily:tab==='new_building'?text.new:text.all}</p></div><div className="result-actions"><select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="newest">{text.newest}</option><option value="price_asc">{text.low}</option><option value="price_desc">{text.high}</option><option value="area_desc">{text.area}</option></select><div className="view-toggle"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')}>▦</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}>☷</button><button>⌖</button></div></div></div>{loading?<div className="loading-grid">{Array.from({length:6}).map((_,i)=><div className="skeleton-card" key={i}/>)}</div>:rows.length?<div className={`catalog-grid ${view==='list'?'list-view':''}`}>{rows.map(p=><Card key={p.id} p={p} lang={lang} text={text}/>)}</div>:<div className="empty-state"><div>⌂</div><h3>{text.no}</h3><p>{text.noText}</p><button onClick={clear}>{text.clear}</button></div>}<div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>Math.max(1,p-1))}>{text.back}</button><div>{Array.from({length:Math.min(pages,5)},(_,i)=><button key={i} className={page===i+1?'active':''} onClick={()=>setPage(i+1)}>{i+1}</button>)}</div><button disabled={page===pages} onClick={()=>setPage(p=>Math.min(pages,p+1))}>{text.next}</button></div></div>
  </section>
  <footer className="catalog-footer"><div className="container"><div><a className="brand" href="/"><span className="brand-mark">⌂</span><span>Pro<span>house</span></span></a><p>{lang==='uz'?'O‘zbekistonning zamonaviy ko‘chmas mulk platformasi.':'Современная платформа недвижимости Узбекистана.'}</p></div><div><b>{text.property}</b><a href="/properties">{text.sale}</a><a href="#">{text.rent}</a><a href="#">{text.new}</a></div><div><b>{lang==='uz'?'Xizmatlar':'Услуги'}</b><a href="#">{lang==='uz'?'Ipoteka':'Ипотека'}</a><a href="#">{lang==='uz'?'Rieltorlar':'Риелторы'}</a><a href="#">{lang==='uz'?'Yordam':'Помощь'}</a></div></div><div className="container catalog-footer-bottom">© 2026 Prohouse · {lang==='uz'?'Barcha huquqlar himoyalangan':'Все права защищены'}</div></footer>
 </main>
}

function Card({p,lang,text}:{p:Listing;lang:Lang;text:any}){return <article className="catalog-card"><a href={`/properties/${p.id}`} className="catalog-image" style={{backgroundImage:`url(${p.image_url||'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85'})`}}><span className={`catalog-badge ${p.is_featured?'vip':''}`}>{p.is_featured?'TOP':p.is_verified?'✓ '+text.verified:text.new}</span><button className="catalog-heart" onClick={e=>e.preventDefault()}>♡</button></a><div className="catalog-card-body"><div className="catalog-price">{money(p.price,p.currency)}</div><h3>{lang==='ru'?(ruTitles[p.title]||p.title):p.title}</h3><div className="catalog-location">⌖ {p.city}{p.district?`, ${p.district}`:''}</div><div className="catalog-meta"><span>{p.area_m2?`${p.area_m2} m²`:'—'}</span><span>{p.rooms?`${p.rooms} xona`:''}</span><span>{p.floor&&p.floors_total?`${p.floor}/${p.floors_total}`:''}</span></div><div className="catalog-seller"><span className="verified-dot">●</span>{p.seller_name||text.owner}</div></div></article>}
