'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { createClient } from '@/utils/supabase/client'

type Developer={id:string;developer_name:string;description:string|null;logo_url:string|null;verification_status:string}
type Complex={id:string;name:string;slug:string;city:string;district:string|null;status:string;completion_year:number|null;is_verified:boolean;is_featured:boolean;developer_id:string|null}

export default function DevelopersPage(){
 const [developers,setDevelopers]=useState<Developer[]>([])
 const [complexes,setComplexes]=useState<Complex[]>([])
 useEffect(()=>{(async()=>{const db=createClient(); const [{data:d},{data:c}]=await Promise.all([db.from('developer_profiles').select('*').in('verification_status',['pending','verified']).order('developer_name'),db.from('residential_complexes').select('*').order('is_featured',{ascending:false}).order('created_at',{ascending:false})]); if(d)setDevelopers(d); if(c)setComplexes(c)})()},[])
 return <main className="min-h-screen bg-[#f6f7f8] text-slate-900"><header className="border-b bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><Link href="/" className="text-2xl font-black">Pro<span className="text-emerald-500">house</span></Link><Link href="/account" className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Kabinet</Link></div></header><section className="mx-auto max-w-7xl px-4 py-10"><p className="text-xs font-black tracking-[.18em] text-emerald-600">PROHOUSE MARKETPLACE</p><h1 className="mt-2 text-4xl font-black">Quruvchi kompaniyalar</h1><p className="mt-3 max-w-2xl text-slate-500">Tasdiqlangan developerlar va ularning yangi turar-joy majmualarini bir joyda ko‘ring.</p><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{developers.map(d=><article key={d.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center overflow-hidden rounded-xl bg-slate-100 font-black">{d.logo_url?<img src={d.logo_url} alt="" className="h-full w-full object-cover"/>:'D'}</div><div><h2 className="font-black">{d.developer_name}</h2><span className="text-xs text-emerald-600">✓ Tasdiqlangan</span></div></div><p className="mt-4 line-clamp-2 text-sm text-slate-500">{d.description||'Yangi turar-joy loyihalari.'}</p><div className="mt-5 text-sm font-bold">{complexes.filter(c=>c.developer_id===d.id).length} loyiha</div></article>)}</div><div className="mt-14"><div className="flex items-end justify-between"><div><p className="text-xs font-black tracking-[.18em] text-emerald-600">NEW BUILDINGS</p><h2 className="mt-1 text-2xl font-black">Turar-joy majmualari</h2></div><Link href="/new-buildings" className="text-sm font-bold text-emerald-700">Barchasi →</Link></div><div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{complexes.map(c=><Link href={`/new-buildings/${c.slug}`} key={c.id} className="rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5"><div className="flex items-center justify-between"><h3 className="font-black">{c.name}</h3>{c.is_verified&&<span className="text-xs font-bold text-emerald-600">✓</span>}</div><p className="mt-2 text-sm text-slate-500">{c.city}{c.district?`, ${c.district}`:''}</p><div className="mt-4 flex justify-between text-xs text-slate-500"><span>{c.status}</span><span>{c.completion_year||'—'}</span></div></Link>)}</div></div></section></main>
}
