'use client'

import { useMemo, useState } from 'react'

type Lang = 'uz' | 'ru'
type Agent = { name:string; agency:string; rating:number; reviews:number; deals:number; listings:number; experience:string; specialty:string; image:string }

const agents:Agent[] = [
 {name:'Madina Karimova',agency:'Prohouse Realty',rating:5,reviews:48,deals:37,listings:19,experience:'8 yil',specialty:'Kvartira va yangi uylar',image:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=180&q=80'},
 {name:'Azizbek Rahmonov',agency:'Toshkent Home',rating:4.9,reviews:31,deals:29,listings:24,experience:'6 yil',specialty:'Uylar va yer uchastkalari',image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=180&q=80'},
 {name:'Dilnoza Ismoilova',agency:'Real Estate Pro',rating:4.8,reviews:26,deals:22,listings:15,experience:'5 yil',specialty:'Ijara va tijorat ko‘chmas mulki',image:'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=180&q=80'},
 {name:'Jasur Tursunov',agency:'Prohouse Partners',rating:4.9,reviews:57,deals:44,listings:27,experience:'7 yil',specialty:'Sotuv va ipoteka',image:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=180&q=80'},
]

const advice = {
 choice:{uz:{title:'Rieltorni qanday tanlash kerak?',intro:'Yaxshi rieltor sizga obyekt topishdan tashqari hujjatlarni tekshirish, muzokara va bitim jarayonini xavfsiz tashkil qilishda yordam beradi.',items:[['Reyting va sharhlar','Mijozlarning real tajribasini ko‘ring. Ko‘p va sifatli sharhlar mutaxassisning tajribasi haqida yaxshi signal beradi.'],['Profil','Tasdiqlangan profil, fotosurat, ish tajribasi va mutaxassislik yo‘nalishi ko‘rsatilgan rieltorni tanlang.'],['E’lonlar','Rieltorning faol e’lonlarini ko‘ring. E’lonlar soni va sifati uning bozordagi faolligini baholashga yordam beradi.'],['Bitimlar tajribasi','So‘nggi davrdagi bitimlar soni va aynan siz izlayotgan ko‘chmas mulk turidagi tajribasiga e’tibor bering.'],['Muloqot va shaffoflik','Komissiya, xizmat doirasi va bitim bosqichlarini oldindan aniq kelishib oling.']]},ru:{title:'Как выбрать риелтора?',intro:'Хороший риелтор помогает не только найти объект, но и проверить документы, провести переговоры и безопасно организовать сделку.',items:[['Рейтинг и отзывы','Изучите реальный опыт клиентов. Количество и качество отзывов помогают оценить специалиста.'],['Профиль','Выбирайте риелтора с подтверждённым профилем, фото, опытом и понятной специализацией.'],['Объявления','Посмотрите активные объявления и оцените качество работы специалиста на рынке.'],['Опыт сделок','Уточните количество недавних сделок и опыт с нужным вам типом недвижимости.'],['Общение и прозрачность','Заранее согласуйте комиссию, услуги и этапы сделки.']]}},
 agent:{uz:{title:'Rieltor nimalarni bilishi kerak?',intro:'Prohouse rieltorlaridan mijoz bilan ishlash, hujjatlar, muzokara va xavfsiz bitim bo‘yicha professional yondashuv kutiladi.',items:[['Bozorni bilish','Hududlar, narxlar va talabni tushunish mijozga aniq tavsiya berish imkonini beradi.'],['Hujjatlarni tekshirish','Obyekt hujjatlari va mulk huquqiga oid ma’lumotlarni bitimdan oldin tekshirish muhim.'],['Muzokara','Sotuvchi va xaridor manfaatlarini muvozanatlashtirib, kelishuvni aniq shartlar asosida olib boring.'],['Mijoz xavfsizligi','Shaxsiy ma’lumotlar va to‘lov jarayonlariga ehtiyotkorlik bilan yondashing.'],['Bitimdan keyingi aloqa','Mijozga ro‘yxatdan o‘tkazish va keyingi jarayonlarda ham yo‘l-yo‘riq bering.']]},ru:{title:'Что нужно знать риелтору?',intro:'От риелторов Prohouse ожидается профессиональный подход к клиентам, документам, переговорам и безопасному проведению сделок.',items:[['Знание рынка','Понимание районов, цен и спроса помогает давать клиенту точные рекомендации.'],['Проверка документов','До сделки важно проверить документы на объект и право собственности.'],['Переговоры','Балансируйте интересы продавца и покупателя и фиксируйте договорённости.'],['Безопасность клиента','Бережно обращайтесь с персональными данными и финансовой частью сделки.'],['После сделки','Помогайте клиенту с регистрацией и другими необходимыми шагами.']]}}
} as const

type AdviceKey = keyof typeof advice

export default function RealtorsPage(){
 const [lang,setLang]=useState<Lang>('uz'); const [deal,setDeal]=useState(''); const [specialty,setSpecialty]=useState(''); const [district,setDistrict]=useState(''); const [query,setQuery]=useState(''); const [sort,setSort]=useState('default'); const [modal,setModal]=useState<AdviceKey|null>(null)
 const ru=lang==='ru'
 const filtered=useMemo(()=>{let a=agents.filter(x=>!query||`${x.name} ${x.agency}`.toLowerCase().includes(query.toLowerCase()));if(deal==='rent')a=a.filter(x=>x.specialty.toLowerCase().includes('ijara'));if(deal==='sale')a=a.filter(x=>!x.specialty.toLowerCase().includes('ijara'));if(specialty==='commercial')a=a.filter(x=>x.specialty.toLowerCase().includes('tijorat'));if(specialty==='mortgage')a=a.filter(x=>x.specialty.toLowerCase().includes('ipoteka'));if(sort==='rating')a=[...a].sort((x,y)=>y.rating-x.rating);if(sort==='deals')a=[...a].sort((x,y)=>y.deals-x.deals);return a},[query,deal,specialty,sort])
 const t=ru?{buy:'Покупка',rent:'Аренда',new:'Новостройки',services:'Услуги',realtors:'Риелторы',post:'Разместить объявление',cabinet:'Личный кабинет',title:'Поиск риелторов в Ташкенте',sub:'Выберите специалиста по рейтингу, отзывам и опыту',allDeals:'Все типы сделок',allSpec:'Все специализации',allDistricts:'Все районы',search:'ФИО риелтора',default:'По умолчанию',rating:'По рейтингу',deals:'По сделкам',found:'Найдено',people:'риелторов',reviews:'оценок',phone:'Показать телефон',chat:'Написать в чат',choice:'Как выбрать риелтора',agent:'Что нужно знать риелтору',agency:'Агентства недвижимости',verified:'Подтверждённый профиль'}:{buy:'Sotuv',rent:'Ijara',new:'Yangi uylar',services:'Xizmatlar',realtors:'Rieltorlar',post:'E’lon joylashtirish',cabinet:'Shaxsiy kabinet',title:'Toshkentdagi rieltorlarni izlash',sub:'Rieltorni reytingi, sharhlari va tajribasiga qarab tanlang',allDeals:'Barcha bitim turlari',allSpec:'Barcha mutaxassisliklar',allDistricts:'Barcha tumanlar',search:'Rieltor F.I.Sh.',default:'Odatiy',rating:'Reyting bo‘yicha',deals:'Bitimlar bo‘yicha',found:'Topildi',people:'rieltor',reviews:'baholar',phone:'Telefonni ko‘rsatish',chat:'Chatga yozish',choice:'Rieltorni qanday tanlash',agent:'Rieltor nimalarni bilishi kerak?',agency:'Ko‘chmas mulk agentliklari',verified:'Tasdiqlangan profil'}
 const openPhone=(a:Agent)=>alert(ru?`${a.name} telefoni: +998 90 123 45 67`:`${a.name} telefoni: +998 90 123 45 67`)
 return <main className="min-h-screen bg-[#f1f3f5] text-slate-900">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex min-h-[78px] max-w-[1440px] items-center gap-7 px-5"><a href="/" className="text-2xl font-black">Pro<span className="text-emerald-500">house</span></a><nav className="hidden flex-1 items-center gap-6 text-sm font-semibold lg:flex"><a href="/listings?tab=sale">{t.buy}</a><a href="/listings?tab=rent">{t.rent}</a><a href="/listings?tab=sale&type=new_building">{t.new}</a><a href="/listings">{t.services}</a><a href="/realtors" className="text-emerald-600">{t.realtors}</a></nav><button onClick={()=>setLang(ru?'uz':'ru')} className="rounded-xl border border-slate-300 px-3 py-2 text-xs font-bold">{ru?'Ru / O‘z':'O‘z / Ru'}</button><a href="/account" className="rounded-xl bg-emerald-600 px-4 py-3 text-xs font-black text-white">{t.cabinet}</a></div></header>
  <div className="border-b border-slate-200 bg-white px-4 py-3"><div className="mx-auto grid max-w-[1320px] gap-2 md:grid-cols-[auto_1fr_1fr_1fr_1.4fr]"><div className="flex rounded-xl border border-slate-200 p-1 text-sm font-bold"><button className="rounded-lg bg-emerald-50 px-4 py-2 text-emerald-700">{t.realtors}</button><button className="px-4 py-2 text-slate-400">{t.agency}</button></div><select value={deal} onChange={e=>setDeal(e.target.value)} className="rounded-xl bg-slate-100 px-4 py-3 text-sm outline-none"><option value="">{t.allDeals}</option><option value="sale">{t.buy}</option><option value="rent">{t.rent}</option></select><select value={specialty} onChange={e=>setSpecialty(e.target.value)} className="rounded-xl bg-slate-100 px-4 py-3 text-sm outline-none"><option value="">{t.allSpec}</option><option value="commercial">{ru?'Коммерция':'Tijorat'}</option><option value="mortgage">{ru?'Ипотека':'Ipoteka'}</option><option value="apartment">{ru?'Квартиры':'Kvartiralar'}</option></select><select value={district} onChange={e=>setDistrict(e.target.value)} className="rounded-xl bg-slate-100 px-4 py-3 text-sm outline-none"><option value="">{t.allDistricts}</option><option>Yunusobod</option><option>Mirzo Ulug‘bek</option><option>Chilonzor</option><option>Yakkasaroy</option><option>Shayxontohur</option></select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} className="rounded-xl bg-slate-100 px-4 py-3 text-sm outline-none"/></div></div>
  <section className="mx-auto max-w-[1320px] px-5 py-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-black">{t.title}</h1><p className="mt-2 text-sm text-slate-500">{t.sub}</p></div><div className="flex gap-2"><button onClick={()=>setModal('choice')} className="rounded-2xl bg-white px-4 py-3 text-left text-sm font-black shadow-sm ring-1 ring-slate-200 hover:ring-emerald-400">{t.choice}<span className="mt-1 block text-xs font-normal text-slate-500">{ru?'Полезные советы':'Foydali maslahatlar'}</span></button><button onClick={()=>setModal('agent')} className="rounded-2xl bg-white px-4 py-3 text-left text-sm font-black shadow-sm ring-1 ring-slate-200 hover:ring-emerald-400">{t.agent}<span className="mt-1 block text-xs font-normal text-slate-500">{ru?'Советы для специалистов':'Mutaxassislar uchun maslahatlar'}</span></button></div></div>
   <div className="mt-6 flex items-center justify-between"><div><span className="font-black">{t.found} {filtered.length*431} {t.people}</span><span className="ml-3 text-sm text-slate-400">{filtered.length} {ru?'показано':'ta ko‘rsatilmoqda'}</span></div><select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold"><option value="default">{t.default}</option><option value="rating">{t.rating}</option><option value="deals">{t.deals}</option></select></div>
   <div className="mt-4 overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200"><div className="hidden grid-cols-[1.5fr_1fr_100px_110px_180px] gap-4 border-b border-slate-200 px-6 py-4 text-xs font-bold text-slate-400 md:grid"><span>{ru?'Риелтор':'Rieltor'}</span><span>{ru?'Рейтинг':'Reyting'}</span><span>{ru?'Сделки':'Bitimlar'}</span><span>{ru?'Объявления':'E’lonlar'}</span><span>{ru?'Действия':'Harakatlar'}</span></div>{filtered.map(a=><article key={a.name} className="grid gap-4 border-b border-slate-200 px-5 py-5 last:border-0 md:grid-cols-[1.5fr_1fr_100px_110px_180px] md:items-center md:px-6"><div className="flex items-center gap-4"><div className="relative"><img src={a.image} alt="" className="h-16 w-16 rounded-full object-cover"/><span className="absolute bottom-0 right-0 flex h-5 w-5 items-center justify-center rounded-full bg-emerald-500 text-xs font-bold text-white">✓</span></div><div><div className="font-black">{a.name}</div><div className="mt-1 text-xs text-slate-500">{a.agency}</div><div className="mt-1 text-xs text-slate-400">{a.experience} · {a.specialty}</div><span className="mt-2 inline-block rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">✓ {t.verified}</span></div></div><div><div className="font-black"><span className="text-amber-400">★</span> {a.rating}</div><div className="mt-1 text-xs text-slate-400">{a.reviews} {t.reviews}</div></div><div className="font-bold">{a.deals}</div><div className="font-bold">{a.listings}</div><div className="flex flex-col gap-2"><button onClick={()=>openPhone(a)} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white">{t.phone}</button><button onClick={()=>alert(ru?'Чат будет доступен после авторизации.':'Chatga yozish avtorizatsiyadan so‘ng ishlaydi.')} className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold">{t.chat}</button></div></article>)}</div>
  </section>
  {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" onClick={()=>setModal(null)}><div onClick={e=>e.stopPropagation()} className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><div className="text-xs font-black tracking-wider text-emerald-600">PROHOUSE MASLAHATLARI</div><h2 className="mt-2 text-2xl font-black sm:text-3xl">{advice[modal][lang].title}</h2></div><button onClick={()=>setModal(null)} className="rounded-full bg-slate-100 px-4 py-2 text-xl font-bold">×</button></div><img src={modal==='choice'?'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=80':'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1000&q=80'} alt="" className="mt-5 h-48 w-full rounded-2xl object-cover"/><p className="mt-5 text-sm leading-6 text-slate-600">{advice[modal][lang].intro}</p><div className="mt-5 space-y-3">{advice[modal][lang].items.map(([title,body])=><div key={title} className="rounded-2xl bg-slate-50 p-5"><div className="font-black">{title}</div><p className="mt-1 text-sm leading-6 text-slate-600">{body}</p></div>)}</div><button onClick={()=>setModal(null)} className="mt-6 rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold">{ru?'Закрыть':'Yopish'}</button></div></div>}
 </main>
}
