'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/utils/supabase/client'

type Lang='uz'|'ru'
type Listing={id:string;title:string;title_ru?:string|null;price:number;currency:string;city:string;district:string|null;listing_type:string;taxonomy_code:string|null;seller_name:string|null;is_verified:boolean;is_trusted_seller:boolean;listing_images?:{image_url:string;sort_order:number|null}[]}
const normalize=(v:string)=>v.toLowerCase().replace(/[ʻʼ`’']/g,'').replace(/ tumani/g,'').replace(/ shahar/g,'').trim()
const money=(v:number,c:string)=>`${new Intl.NumberFormat('ru-RU').format(Number(v))} ${c==='USD'?'$':'so‘m'}`

export default function RealtorsPage(){
 const[lang,setLang]=useState<Lang>('uz');const[category,setCategory]=useState('');const[district,setDistrict]=useState('');const[query,setQuery]=useState('');const[sort,setSort]=useState('default');const[items,setItems]=useState<Listing[]>([]);const[loading,setLoading]=useState(true)
 useEffect(()=>{const saved=localStorage.getItem('prohouse-lang');if(saved==='ru')setLang('ru');const q=new URLSearchParams(window.location.search);setCategory(q.get('taxonomy')||'');setDistrict(q.get('district')||'');setQuery(q.get('q')||'');(async()=>{try{const db=createClient();const{data,error}=await db.from('listings').select('id,title,title_ru,price,currency,city,district,listing_type,taxonomy_code,seller_name,is_verified,is_trusted_seller,listing_images(image_url,sort_order)').eq('status','active').eq('listing_type','realtor');if(!error)setItems((data||[]) as Listing[])}finally{setLoading(false)}})()},[])
 const ru=lang==='ru'
 const cats=[['','Rieltorlar','Риелторы'],['realtor_agent','Rieltor','Риелтор'],['realtor_agency','Ko‘chmas mulk agentligi','Агентство недвижимости'],['realtor_company','Ko‘chmas mulk kompaniyasi','Компания недвижимости']]
 const filtered=useMemo(()=>items.filter(x=>!category||x.taxonomy_code===category).filter(x=>!district||normalize(x.district||'')===normalize(district)).filter(x=>!query||`${x.title} ${x.seller_name||''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='priceLow'?a.price-b.price:sort==='priceHigh'?b.price-a.price:0),[items,category,district,query,sort])
 const labels={title:ru?'Риелторы в Ташкенте':'Toshkentdagi rieltorlar',sub:ru?'Выберите специалиста или агентство по категории и опыту':'Mutaxassis yoki agentlikni kategoriya va tajribaga qarab tanlang',all:ru?'Все':'Barchasi',search:ru?'Поиск':'Qidirish',district:ru?'Район':'Tuman',sort:ru?'Сортировка':'Saralash',default:ru?'По умолчанию':'Odatiy',low:ru?'Дешевле':'Arzonidan',high:ru?'Дороже':'Qimmatidan',post:ru?'Разместить объявление':'E’lon joylashtirish',cabinet:ru?'Личный кабинет':'Shaxsiy kabinet',empty:ru?'Активных объявлений риелторов пока нет.':'Hozircha faol rieltor e’lonlari yo‘q.'}
 return <main className="min-h-screen bg-[#f1f3f5] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex min-h-[72px] max-w-[1400px] items-center gap-7 px-5"><Link href="/" className="text-2xl font-black">Pro<span className="text-emerald-500">house</span></Link><nav className="hidden flex-1 items-center gap-6 text-sm font-semibold lg:flex"><Link href="/listings?tab=sale">{ru?'Покупка':'Sotib olish'}</Link><Link href="/listings?tab=rent">{ru?'Аренда':'Ijara'}</Link><Link href="/listings?tab=sale&type=new_building">{ru?'Новостройки':'Yangi uylar'}</Link><Link href="/uy-qurish">{ru?'Строительство':'Uy qurish'}</Link><Link href="/listings?tab=all&taxonomy=services_repair">{ru?'Услуги':'Xizmatlar'}</Link><Link href="/realtors" className="text-emerald-600">{ru?'Риелторы':'Rieltorlar'}</Link></nav><Link href="/listings/new" className="hidden rounded-xl border border-slate-200 px-4 py-2 text-xs font-bold sm:block">{labels.post}</Link><Link href="/account" className="rounded-xl bg-emerald-600 px-4 py-3 text-xs font-black text-white">{labels.cabinet}</Link></div></header>
 <section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-[1320px] px-5 py-5"><div className="flex flex-wrap gap-2">{cats.map(([code,uzv,ruv])=><button key={code} onClick={()=>setCategory(code)} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${category===code?'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200':'bg-slate-100 text-slate-600'}`}>{ru?ruv:uzv}</button>)}</div></div></section>
 <section className="mx-auto max-w-[1320px] px-5 py-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-black">{labels.title}</h1><p className="mt-2 text-sm text-slate-500">{labels.sub}</p></div><div className="flex gap-2"><select value={district} onChange={e=>setDistrict(e.target.value)} className="rounded-xl border bg-white px-4 py-3 text-sm"><option value="">{labels.district}</option>{['Yunusobod','Mirzo Ulug‘bek','Chilonzor','Yakkasaroy','Shayxontohur'].map(x=><option key={x}>{x}</option>)}</select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={labels.search} className="rounded-xl border bg-white px-4 py-3 text-sm"/><select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-xl border bg-white px-4 py-3 text-sm"><option value="default">{labels.default}</option><option value="priceLow">{labels.low}</option><option value="priceHigh">{labels.high}</option></select></div></div>
 <div className="mt-6 flex items-center justify-between"><b>{filtered.length} {ru?'объявлений':'ta e’lon'}</b><span className="text-sm text-slate-400">{category?cats.find(x=>x[0]===category)?.[ru?2:1]:labels.all}</span></div>
 {loading?<div className="mt-5 rounded-3xl bg-white p-10 text-center text-slate-500">{ru?'Загрузка...':'Yuklanmoqda...'}</div>:!filtered.length?<div className="mt-5 rounded-3xl bg-white p-12 text-center text-slate-500">{labels.empty}</div>:<div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map(x=>{const image=x.listing_images?.slice().sort((a,b)=>(a.sort_order??0)-(b.sort_order??0))[0]?.image_url;return <Link key={x.id} href={`/listings/${x.id}`} className="overflow-hidden rounded-2xl border bg-white shadow-sm hover:-translate-y-0.5 hover:shadow-lg"><div className="aspect-[4/3] bg-slate-100">{image&&<img src={image} alt={x.title} className="h-full w-full object-cover"/>}</div><div className="p-4"><div className="flex gap-2">{x.is_verified&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[11px] font-bold text-emerald-700">✓ {ru?'Проверено':'Tasdiqlangan'}</span>}{x.is_trusted_seller&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[11px] font-bold text-emerald-700">✓ {ru?'Надёжный':'Ishonchli'}</span>}</div><h2 className="mt-3 text-lg font-black">{money(x.price,x.currency)}</h2><p className="mt-1 font-bold">{ru?(x.title_ru||x.title):x.title}</p><p className="mt-2 text-xs text-slate-500">⌖ {x.city}{x.district?`, ${x.district}`:''}</p><p className="mt-3 border-t pt-3 text-xs font-semibold text-slate-600">{x.seller_name||'Rieltor'}</p></div></Link>})}</div>}
 </section></main>
}
